const {chromium}=require('playwright');const {createServer}=require('node:http');const {readFile,mkdir}=require('node:fs/promises');const {resolve,extname,sep}=require('node:path');const {createHash,randomUUID}=require('node:crypto');const assert=require('node:assert/strict');
(async()=>{const {syntheticHWP}=await import('../bulletin.test.mjs');const root=resolve('web-editor'),server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://x').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const dialogs=[];let dismiss=false;page.on('dialog',d=>{dialogs.push(d.message());if(dismiss){dismiss=false;d.dismiss();}else d.accept();});
 const libraryId=randomUUID(),docs=new Map(),nodes=[],puts=[],patches=[];let pv=1,template='',dropboxReady=false;const dropboxPaths=[],documentSearches=[],contentReads=[];
 const meta=id=>{const d=docs.get(id);return {id,name:d.path.split('/').pop(),path:d.path,version:d.version,category:d.category||null,sha256:createHash('sha256').update(d.xml).digest('hex'),available:true,updatedAt:'2026-10-03T00:00:00Z'};};
 const byName=name=>[...docs.keys()].find(id=>docs.get(id).path===name+'.pro6');const hash=n=>createHash('sha256').update(JSON.stringify(n.items)).digest('hex');
 const library=()=>({id:libraryId,path:'기본.pro6pl',version:pv,playlists:nodes.map(n=>({id:n.id,name:n.name,itemCount:n.items.length})),updatedAt:'2026-10-03T00:00:00Z'});
 const names=node=>nodes.find(n=>n.name===node).items.map(x=>docs.get(x.doc).path.replace(/\.pro6$/,''));
 const BOOKS='창세기 출애굽기 레위기 민수기 신명기 여호수아 사사기 룻기 사무엘상 사무엘하 열왕기상 열왕기하 역대상 역대하 에스라 느헤미야 에스더 욥기 시편 잠언 전도서 아가 이사야 예레미야 예레미야애가 에스겔 다니엘 호세아 요엘 아모스 오바댜 요나 미가 나훔 하박국 스바냐 학개 스가랴 말라기 마태복음 마가복음 누가복음 요한복음 사도행전 로마서 고린도전서 고린도후서 갈라디아서 에베소서 빌립보서 골로새서 데살로니가전서 데살로니가후서 디모데전서 디모데후서 디도서 빌레몬서 히브리서 야고보서 베드로전서 베드로후서 요한일서 요한이서 요한삼서 유다서 요한계시록'.split(' ');
 const bible={books:BOOKS.map(name=>({name,chapters:[1,2,3,13,22].map(number=>({number,verses:Array.from({length:40},(_,k)=>({number:k+1,text:`${name} ${number}:${k+1} 합성 본문`+(k===1?' 아주 긴 합성 본문 문장이 이어지며 여러 줄로 나뉘어야 하는 경우를 어절 단위로 시험합니다'.repeat(2):'')}))}))}))};
 await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname;let data={};if(path==='/api/documents'&&req.method()==='GET'&&u.searchParams.get('q'))documentSearches.push(u.searchParams.get('sort')+'/'+u.searchParams.get('includeIndexed'));
  if(path==='/api/session')data={ready:true,authenticated:true,name:'시험'};else if(path==='/api/sync-observations')data={items:{}};else if(path==='/api/sync/devices')data={head:0,devices:[]};else if(path==='/api/editing')data={others:[]};else if(path==='/api/dropbox/config')data={ready:dropboxReady};
  else if(path==='/api/dropbox/list'){dropboxPaths.push(u.searchParams.get('path'));data={entries:[{kind:'folder',name:'예배별 주보 자료와 오래된 자료 폴더',path:'예배별 주보 자료와 오래된 자료 폴더'},{kind:'file',name:'0927 주보.hwp',size:1200,path:'0927.hwp',modified:'2026-09-26T09:00:00Z'},{kind:'folder',name:'가 폴더',path:'가'},{kind:'file',name:'아주 긴 이름의 합성 주보 자료 2026년 10월 첫째 주.hwp',size:1200,path:'synthetic.hwp',modified:'2026-10-03T09:00:00Z'},{kind:'file',name:'합성 안내 자료.png',size:1200,path:'synthetic.png'}],next:null};}
  else if(path==='/api/playlists')data={libraries:[library()],next:null};
  else if(path.endsWith('/plan')){const n=nodes.find(x=>x.id===u.searchParams.get('node'));data={library:library(),playlist:{id:n.id,name:n.name,editable:true,sha256:hash(n)},items:n.items.map(x=>({id:x.id,kind:'document',document:meta(x.doc),name:meta(x.doc).name.normalize('NFD')})),ready:true};}
  else if(path==='/api/playlists/'+libraryId&&req.method()==='PATCH'){const n=nodes.find(x=>x.id===u.searchParams.get('node')),body=JSON.parse(req.postData());if(body.baseNodeHash)assert.equal(body.baseNodeHash,hash(n));else assert.equal(req.headers()['if-match'],`"${pv}"`);n.items=body.items.map(x=>x.id?{...n.items.find(y=>y.id===x.id)}:{id:randomUUID(),doc:x.documentId});assert.ok(n.items.every(x=>docs.has(x.doc)));pv++;patches.push(n.name);data={library:library(),playlist:{sha256:hash(n)}};}
  else if(path==='/api/documents')data={documents:[...docs.keys()].filter(id=>docs.get(id).path.includes(u.searchParams.get('q')||'')).map(meta),next:null};
  else if(path.startsWith('/api/documents/')){const id=path.split('/')[3],d=docs.get(id);if(!d){await route.fulfill({status:404,json:{message:'없음'}});return;}
   if(path.endsWith('/content')){contentReads.push(id);await route.fulfill({body:d.xml,contentType:'application/xml'});return;}
   if(req.method()==='PUT'){assert.equal(req.headers()['if-match'],`"${d.version}"`);d.xml=req.postData();d.version++;puts.push(d.path);}data={document:meta(id)};}
  else throw Error('Unexpected '+path);await route.fulfill({json:data});});
 await page.route('**/resources/**',async route=>{const name=new URL(route.request().url()).pathname.split('/').pop();await route.fulfill({json:name==='catalog.json'?{fonts:[],media:[]}:name==='templates.json'?[{id:'104',name:'말씀',label:'본문',width:1920,height:1080,xml:template}]:bible});});
 try{await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.YebaeonBulletin&&YebaeonCloud.authenticated());
  const made=await page.evaluate(()=>{const make=slides=>{const m=PP6.parse(YebaeonLibraryActions.blankDocument('예배순서'),'x'),first=PP6.slides(m)[0],holder=first.parentNode,proto=first.cloneNode(true);first.remove();
    for(const s of slides){const slide=proto.cloneNode(true);PP6.refreshIDs(slide);const box=PP6.textElements(slide)[0],boxes=[box];for(let i=1;i<s.boxes.length;i++){const b=box.cloneNode(true);PP6.refreshIDs(b);box.parentNode.append(b);boxes.push(b);}if(!s.boxes.length)box.remove();s.boxes.forEach((t,i)=>PP6.setText(boxes[i],t));if(s.small)PP6.formatRange(boxes[0],0,s.small,{size:40});if(s.label)slide.setAttribute('label',s.label);holder.append(slide);}return PP6.serialize(m);};
   const title=t=>({boxes:[t]}),verse=(ref)=>({boxes:['옛 본문',ref],label:ref+' (NKRV)'});
   return {plain:make([title('자료')]),template:(()=>{const m=PP6.parse(make([verse('창세기 1:1')]),'t');return new XMLSerializer().serializeToString(PP6.slides(m)[0]);})(),
    prayer:make([{boxes:[],label:'표지'},title('대표기도 임효일 집사'),title('대표기도\n홍길동 집사')]),prayer2:make([title('대표기도 남윤옥 권사'),{boxes:[],label:'표지'}]),prayer3:make([title('대표기도\n김철수형제')]),
    sermon:make([{boxes:[],label:'표지'},title('옛 시리즈\n옛 제목\n(창세기 2:1)'),verse('창세기 2:1'),{boxes:['What? 옛 질문\n옛 문장입니다.']},verse('요한복음 1:1'),{boxes:['예배 후 광고'],label:'광고'}]),
    simple:make([title('옛 제목\n(요한복음 1:1)'),verse('요한복음 1:1')]),separate:(()=>{const xml=make([{boxes:['옛 청년 제목','옛 시리즈','(요한복음 1:1)']},verse('요한복음 1:1')]),m=PP6.parse(xml,'s'),b=PP6.textElements(PP6.slides(m)[0]),r=PP6.rect(b[0]);PP6.setRect(b[0],{...r,y:r.y+300});PP6.setRect(b[2],{...r,y:r.y+600});return PP6.serialize(m);})(),split:make([{boxes:[],label:'금요기도회_PPT'},{boxes:[],label:'KakaoTalk_Image'},verse('누가복음 11:1'),verse('누가복음 11:2'),{boxes:['광고 끝장']}]),fridayText:make([{boxes:[],label:'표지'},{boxes:['옛 시리즈\n\n옛 금요 제목','(누가복음 1:1)'],small:4,label:'옛 제목 장'},verse('누가복음 1:1')]),plainTitle:make([{boxes:['보고 듣고 배우는\n복된 삶!','(마태복음 13:10-17)']},verse('마태복음 13:10')])};});
  const balanced=await page.evaluate(async xml=>{
   const m=PP6.parse(xml,'wrap'),text='가나다라마 바사아자차 카타파하가 나다라마바사',ctx=document.createElement('canvas').getContext('2d');
   for(const slide of PP6.slides(m))for(const box of PP6.textElements(slide)){
    const parsed=PP6.parseRTF(PP6.textNode(box).textContent),style=parsed.emptyStyle;
    const width=PP6Render.layout(ctx,{runs:[{text,style}],emptyStyle:style},{w:1e9,h:1e9}).lines[0].width;
    PP6.setRect(box,{...PP6.rect(box),w:width*.62,h:1000});
   }
   const input=PP6.serialize(m),data={series:'시리즈',title:text,ref:'창세기 1:1',passage:'',groups:[{question:'Who? 짧은 질문',points:[{template:'가나다라마 _______ 카타파하가 나다라마바사',fills:['바사아자차'],quotes:[]}]}]};
   const result=await YebaeonBulletinDocuments.sermon(input,'wrap',data,{}),slides=PP6.slides(PP6.parse(result.xml,'out'));
   const title=PP6.parseRTF(PP6.textNode(PP6.textElements(slides[1])[0]).textContent).text;
   const point=slides.find(s=>PP6.textElements(s).some(b=>PP6.parseRTF(PP6.textNode(b).textContent).text.startsWith('Who?'))),parsed=PP6.parseRTF(PP6.textNode(PP6.textElements(point)[0]).textContent);
   const short=await YebaeonBulletinDocuments.sermon(input,'short',{...data,title:'짧은 제목',groups:[]},{});
   const manual=await YebaeonBulletinDocuments.sermon(input,'manual',{...data,title:'가나다라마\n바사아자차 카타파하가 나다라마바사',groups:[]},{});
   const getTitle=x=>PP6.parseRTF(PP6.textNode(PP6.textElements(PP6.slides(PP6.parse(x.xml,'t'))[1])[0]).textContent).text;
   return {title,short:getTitle(short),point:parsed.text,underlined:parsed.runs.filter(r=>r.style.underline).map(r=>r.text).join(''),manual:getTitle(manual)};
  },made.sermon);
  assert.equal(balanced.title,'시리즈\n가나다라마 바사아자차\n카타파하가 나다라마바사\n(창세기 1:1)','long titles split near the middle word boundary');
  assert.equal(balanced.point,'Who? 짧은 질문\n가나다라마 바사아자차\n카타파하가 나다라마바사','long points use the same balanced split');assert.equal(balanced.underlined,'바사아자차','answer underline survives the inserted break');
  assert.equal(balanced.short,'시리즈\n짧은 제목\n(창세기 1:1)','short title stays on one line');
  assert.equal(balanced.manual,'시리즈\n가나다라마\n바사아자차 카타파하가 나다라마바사\n(창세기 1:1)','manual line breaks take priority');
  template=made.template;const add=(name,xml,category)=>{const id=randomUUID();docs.set(id,{path:name+'.pro6',xml,version:1,category});return id;};
  for(const n of ['첫화면','사도신경(구)','광고','2026엔딩','나의 모습 나의 소유','마무리','주일예배말씀 목사님 ppt','옛 곡 1','옛 곡 2','옛 설교후','옛 헌금','합성 찬양 A','합성 찬양 B','합성 찬양 C','합성 찬양 D','합성 찬양 E','합성 찬양 F'])add(n,made.plain,'가사찬양');
  add('100 주 이름 가사',made.plain,'가사찬양');add('100 주 이름 악보',made.plain,'악보찬양');add('1부기도',made.prayer);add('2부 기도',made.prayer2);add('3부 기도',made.prayer3);add('주일예배말씀',made.sermon);add('청년부 말씀',made.separate);add('수요예배',made.simple);add('금요예배말씀',made.split);add('청년부 말씀 서식',made.plainTitle);
  const node=(name,list)=>nodes.push({id:randomUUID(),name,items:list.map(n=>({id:randomUUID(),doc:byName(n)}))});
  node('1부 예배(품성)',['첫화면','사도신경(구)','옛 곡 1','1부기도','광고','주일예배말씀','주일예배말씀 목사님 ppt','옛 설교후','옛 헌금','2026엔딩','마무리']);node('1부 예배(클래식)',['첫화면','사도신경(구)','옛 곡 1','1부기도','광고','주일예배말씀','옛 설교후','옛 헌금','2026엔딩']);
  node('2부 예배',['첫화면','사도신경(구)','옛 곡 1','옛 곡 2','2부 기도','광고','주일예배말씀','옛 설교후','옛 헌금','2026엔딩']);node('청년예배',['첫화면','사도신경(구)','옛 곡 2','3부 기도','주일예배말씀','주일예배말씀 목사님 ppt','옛 설교후','광고','나의 모습 나의 소유','2026엔딩']);
  node('수요예배',['첫화면','수요예배']);node('금요예배',['첫화면','금요예배말씀']);
  await page.reload();await page.waitForFunction(()=>window.YebaeonBulletin&&YebaeonCloud.authenticated()&&YebaeonPlaylists.libraries().length);
  if(process.env.BULLETIN_FIXTURE_DIR){const fs=require('node:fs');for(const name of fs.readdirSync(process.env.BULLETIN_FIXTURE_DIR).filter(n=>n.endsWith('.hwp'))){const bytes=fs.readFileSync(require('node:path').join(process.env.BULLETIN_FIXTURE_DIR,name));const r=await page.evaluate(bytes=>{const p=YebaeonBulletinParser.parse(Uint8Array.from(bytes));return {date:p.date,songs:p.services.map(s=>s.songs.length),groups:p.sermonGroups.length};},[...bytes]);assert.equal(r.songs.length,3);console.log('Private HWP verified:',JSON.stringify(r));}}
  await page.locator('#bulletinOpen').click();assert.equal(await page.locator('.bulletin-empty').isVisible(),true);
  await page.locator('#bulletinFile').setInputFiles({name:'synthetic.hwp',mimeType:'application/octet-stream',buffer:syntheticHWP()});await page.waitForFunction(()=>YebaeonBulletin.state()?.date==='2026-10-04');
  assert.equal(await page.locator('#bulletinStart .file-start-name').textContent(),'synthetic.hwp');assert.equal(await page.locator('#bulletinDate').inputValue(),'2026. 10. 04.');assert.equal(await page.locator('#bulletinWork input[type=date]').count(),0);
  const slot=label=>page.locator('.bulletin-slot').filter({has:page.locator('label',{hasText:label})}).first();
  assert.equal(await page.locator('.bulletin-target select').evaluate(s=>s.selectedOptions[0].text),'1부 예배(품성)','first Sunday uses 품성');
  const navState=()=>page.evaluate(()=>{const w=YebaeonBulletin.state();return [w.step,w.svc];});
  assert.equal(await page.locator('#bulletinPrev').isDisabled(),true);
  for(const expected of [['song',1],['song',2],['prayer',2]]){await page.locator('#bulletinNext').click();assert.deepEqual(await navState(),expected);}
  for(const expected of [['song',2],['song',1],['song',0]]){await page.locator('#bulletinPrev').click();assert.deepEqual(await navState(),expected);}
  assert.equal(await page.locator('#bulletinUndo').isDisabled(),true,'navigation alone is not an edit');
  await page.getByRole('tab',{name:/기도/}).click();const prayerInput=slot('1부 기도').locator('input'),oldPrayer=await prayerInput.inputValue();
  await prayerInput.click();await prayerInput.fill('가나다 권사');await prayerInput.press('Control+z');assert.equal(await prayerInput.inputValue(),oldPrayer,'undo works before leaving the input');
  await prayerInput.press('Control+Shift+z');assert.equal(await prayerInput.inputValue(),'가나다 권사');
  await page.getByRole('tab',{name:/주일말씀/}).click();await page.locator('#bulletinUndo').click();assert.deepEqual(await navState(),['prayer',0]);assert.equal(await prayerInput.inputValue(),oldPrayer,'undo returns to the edited field after switching steps');
  await page.locator('#bulletinRedo').click();assert.equal(await prayerInput.inputValue(),'가나다 권사');await page.locator('#bulletinUndo').click();
  await prayerInput.click();await prayerInput.fill('가나다 장로');assert.equal(await page.locator('#bulletinRedo').isDisabled(),true,'new edit clears redo');await page.locator('#bulletinUndo').click();
  await page.getByRole('tab',{name:/찬양/}).click();
  const sourceTable=page.locator('#bulletinSource .bulletin-source-grid');
  assert.equal(await sourceTable.count(),1);
  const tableText=await sourceTable.innerText();for(const word of ['1부예배','2부예배','3부예배','합성 찬양 A','합성 찬양 C'])assert.ok(tableText.includes(word),'all services retain their place in the source table');
  assert.equal(await page.getByRole('button',{name:/이 칸을 .* 찬양으로/}).count(),0);
  assert.equal(await sourceTable.locator('td',{hasText:'합성 찬양 A'}).getAttribute('rowspan'),'2');
  await page.screenshot({path:'artifacts/bulletin-songs-only.png'});assert.equal(await sourceTable.locator('th').count(),3);assert.doesNotMatch(tableText,/신앙고백|부름의 찬양|합심기도|대표기도|합성 설교|축복의 선포|드림의 찬양/);assert.equal(await sourceTable.locator('td',{hasText:'합성 찬양 D'}).getAttribute('colspan'),'2');
  // A previously unchanged (automatically unchecked) service becomes included after a song is selected.
  await page.getByRole('tab',{name:'검토·적용',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#bulletinDialog').matches('[aria-busy=true]')&&document.querySelectorAll('.bulletin-compare').length>0);
  assert.equal(await page.locator('.bulletin-op>label',{hasText:'1부 예배(품성)'}).locator('input').isChecked(),false);
  await page.locator('#bulletinSteps button',{hasText:'찬양'}).click();
  // Songs: candidates only; nothing is replaced until the user picks a document.
  await slot('찬양 1').click();await page.locator('.bulletin-cands .cand',{hasText:'100 주 이름 가사'}).waitFor();assert.match(await page.locator('.bulletin-cands .cand',{hasText:'100 주 이름 악보'}).textContent(),/악보찬양/);
  assert.equal(await page.locator('.bulletin-cands input').count(),0,'the slot box is the search box; candidates show results only');
  const songBox=slot('찬양 1').locator('[id^=bulletin-]');await songBox.fill('악보');await page.locator('.bulletin-cands .cand',{hasText:'100 주 이름 가사'}).waitFor({state:'detached'});assert.equal(await page.locator('.bulletin-cands .cand',{hasText:'100 주 이름 악보'}).count(),1,'typing in the slot box searches again');
  await songBox.fill('100 주');await songBox.press('Enter');await page.locator('.bulletin-cands .cand',{hasText:'100 주 이름 가사'}).waitFor();
  await page.locator('.bulletin-cands .cand',{hasText:'100 주 이름 가사'}).click();
  await page.locator('#bulletinUndo').click();assert.doesNotMatch(await slot('찬양 1').textContent(),/고름: 100 주 이름 가사/);await page.locator('#bulletinRedo').click();assert.match(await slot('찬양 1').textContent(),/고름: 100 주 이름 가사/,'song choices are undoable after the row was rebuilt');
  await slot('설교 후 찬양').click();await page.locator('.bulletin-cands .cand',{hasText:'합성 찬양 D'}).waitFor();assert.equal(await page.locator('.bulletin-cands .cand',{hasText:'지금 이 자리'}).count(),0);
  await page.locator('.bulletin-cands .cand',{hasText:'합성 찬양 D'}).click();
  await page.locator('.bulletin-svc button',{hasText:'2부'}).click();assert.equal(await sourceTable.innerText(),tableText,'switching service keeps the complete source table');await slot('찬양 1').click();assert.match(await sourceTable.locator('.w.act').allTextContents().then(a=>a.join(' ')),/합성 찬양 A/);
  await page.locator('#bulletinSource .w',{hasText:/^합성$/}).first().click();await page.locator('#bulletinSource .w',{hasText:/^B$/}).first().click();
  assert.equal(await slot('찬양 1').locator('[id^=bulletin-]').inputValue(),'합성 B','first word replaces, next word appends');
  await page.locator('#bulletinSource .bulletin-line',{hasText:'합성 찬양 A'}).locator('.pil').click();assert.equal(await slot('찬양 1').locator('[id^=bulletin-]').inputValue(),'합성 찬양 A');
  await page.locator('.bulletin-svc button',{hasText:'청년예배'}).click();await slot('찬양 1').click();await page.locator('.bulletin-cands .cand',{hasText:'합성 찬양 C'}).click();
  assert.equal(await slot('헌금 찬양').locator('[id^=bulletin-]').isDisabled(),true);
  await page.locator('#bulletinSteps button',{hasText:'기도'}).click();assert.match(await slot('1부 기도').textContent(),/이름 가나다 · 직함 집사/);assert.match(await slot('2부 기도').textContent(),/직함 시무집사/);
  await page.locator('#bulletinSteps button',{hasText:'주일말씀'}).click();assert.equal(await slot('빈칸 1').locator('[id^=bulletin-]').inputValue(),'의심');
  const titleBox=()=>slot('제목').locator('textarea');assert.equal(await titleBox().inputValue(),'합성 설교 제목!');await titleBox().click();await titleBox().fill('합성 설교\n제목!');await titleBox().dispatchEvent('change');assert.equal(await page.evaluate(()=>Object.values(YebaeonBulletin.state().slots).find(s=>s.label==='제목').value),'합성 설교\n제목!');const pointBox=()=>slot('대지 문장').locator('textarea');const pointText=await pointBox().inputValue();assert.match(pointText,/^믿음은 /);await pointBox().click();await pointBox().fill(pointText.replace('믿음은 ','믿음은\n'));await pointBox().dispatchEvent('change');
  await slot('빈칸 1').click();assert.equal(await page.locator('#bulletinSource .bulletin-cell.zone').count(),1,'blank shows the summary box');
  const renderedLines=async locator=>locator.evaluate(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),lines=new Map();let node;while(node=walker.nextNode())for(let i=0;i<node.textContent.length;i++){const range=document.createRange();range.setStart(node,i);range.setEnd(node,i+1);const rect=range.getBoundingClientRect();if(rect.width>0){const y=Math.round(rect.top);lines.set(y,(lines.get(y)||'')+node.textContent[i]);}}return [...lines.values()].map(s=>s.trim()).filter(Boolean);});
  const simplePreview=page.locator('.bulletin-slides').first();await simplePreview.scrollIntoViewIfNeeded();
  assert.equal(await simplePreview.locator('.sl').count(),12);assert.equal(await page.locator('#bulletinWork canvas').count(),0,'input stages keep lightweight cards');
  assert.deepEqual(await renderedLines(simplePreview.locator('.ttl').first()),['합성 설교','제목!'],'manual title breaks are visible');
  assert.equal(await simplePreview.locator('u').first().textContent(),'의심','filled answers retain underline');
  const previewReads=contentReads.length,longTitle='Alpha Bravo Charlie Delta Echo';
  await titleBox().click();await titleBox().fill(longTitle);await titleBox().dispatchEvent('change');await simplePreview.scrollIntoViewIfNeeded();
  const titleLines=await renderedLines(simplePreview.locator('.ttl').first());assert.equal(titleLines.length,2,'long title balances into two lines');assert.equal(titleLines.join(' '),longTitle,'words are not broken');
  await titleBox().click();await titleBox().fill('합성 설교\n제목!');await titleBox().dispatchEvent('change');
  assert.equal(contentReads.length,previewReads,'simple preview does not fetch slide documents');assert.match(await page.locator('.bulletin-group',{hasText:'청년부 말씀'}).textContent(),/청년 합성 설교/);
  await page.locator('#bulletinSteps button',{hasText:'주중말씀'}).click();assert.match(await page.locator('.bulletin-group',{hasText:'수요예배'}).textContent(),/파하가전도사 준비/);
  const friday=page.locator('.bulletin-group').filter({has:page.locator('h4',{hasText:'금요예배'})}),fridayTitle=friday.locator('.bulletin-slot').filter({has:page.locator('label',{hasText:/^제목$/})}).locator('textarea');
  const oldFridayTitle=await fridayTitle.inputValue();await fridayTitle.click();await fridayTitle.fill(longTitle);await fridayTitle.dispatchEvent('change');
  assert.deepEqual(await renderedLines(friday.locator('.bulletin-slides .ttl').first()),titleLines,'weekday titles use the same balanced preview');
  await fridayTitle.click();await fridayTitle.fill('Alpha Bravo\nCharlie Delta');await fridayTitle.dispatchEvent('change');assert.deepEqual(await renderedLines(friday.locator('.bulletin-slides .ttl').first()),['Alpha Bravo','Charlie Delta'],'weekday manual breaks remain visible');
  await fridayTitle.click();await fridayTitle.fill(oldFridayTitle);await fridayTitle.dispatchEvent('change');
  // 서버 plan처럼 연결 문서는 document.id로만, 이름은 Mac이 올린 꼴(NFD)로 준다.
  const prayerID=byName('1부기도');await page.evaluate(id=>{window.__pending=YebaeonCloud.pendingDocuments;YebaeonCloud.pendingDocuments=ids=>ids.includes(id)?[{id}]:[];},prayerID);
  await page.locator('#bulletinNext').click();await page.locator('.bulletin-op').first().waitFor();
  const ops=await page.locator('.bulletin-op>label').allTextContents();const kinds=ops.map(t=>/기도/.test(t)?'prayer':/금요|수요/.test(t)?'weekday':/말씀/.test(t)?'sermon':'playlist');assert.deepEqual(kinds,[...kinds].sort((x,y)=>['playlist','prayer','sermon','weekday'].indexOf(x)-['playlist','prayer','sermon','weekday'].indexOf(y)),'review follows the work steps: '+ops.join('|'));assert.ok(['1부기도','2부 기도','3부 기도'].every(n=>ops.some(t=>t.startsWith(n))),'prayer documents are listed for each service: '+ops.join('|'));assert.ok(ops.some(t=>t.includes('청년부 말씀'))&&ops.some(t=>t.includes('금요예배말씀'))&&!ops.some(t=>t.startsWith('수요예배문서')),ops.join('|'));
  assert.equal(puts.length+patches.length,0,'nothing is saved before approval');
  await page.waitForFunction(()=>document.querySelector('#bulletinNext').textContent==='적용');await page.locator('.bulletin-op.bulletin-staged .bulletin-compare').first().waitFor();
  assert.equal(await page.locator('.bulletin-op ul').count(),0,'review cards show the preview, not a change list');
  assert.match(await page.locator('.bulletin-op',{hasText:'2부 예배'}).locator('.bulletin-compare-side').nth(1).textContent(),/합성 찬양 D/,'the after-sermon song chosen for 1부 carries over to 2부');
  assert.match(await page.locator('.bulletin-op',{hasText:'2부 예배'}).textContent(),/찬양 2곡은 고르지 않아/);
  await page.locator('#bulletinSteps button',{hasText:'찬양'}).click();await page.locator('.bulletin-svc button',{hasText:'2부'}).click();await slot('찬양 1').click();await page.locator('.bulletin-cands .cand',{hasText:'합성 찬양 A'}).click();await slot('찬양 2').locator('.skip').click();
  await page.getByRole('tab',{name:'검토·적용',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#bulletinDialog').matches('[aria-busy=true]')&&[...document.querySelectorAll('.bulletin-op')].some(e=>e.textContent.includes('2부 예배')&&e.querySelector('.added')?.textContent.includes('합성 찬양 A')));
  assert.doesNotMatch(await page.locator('.bulletin-op',{hasText:'2부 예배'}).textContent(),/고르지 않아/,'returning to review refreshes picks and skipped songs');
  const reads=()=>contentReads.length,readsBefore=reads(),toggle=page.locator('.bulletin-op>label',{hasText:'3부 기도'}).locator('input[type=checkbox]');
  await toggle.uncheck();await toggle.check();await page.waitForTimeout(300);assert.equal(reads(),readsBefore,'turning a check off and on again keeps the built preview');assert.equal(await page.locator('#bulletinNext').textContent(),'적용');
  assert.equal(puts.length+patches.length,0,'미리 보기 saves nothing');assert.equal(await page.locator('#bulletinNext').textContent(),'적용');assert.equal(await page.locator('.bulletin-compare .bulletin-thumbs').first().evaluate(e=>getComputedStyle(e).flexWrap),'nowrap','slides scroll sideways');assert.ok(await page.locator('.bulletin-compare .bulletin-compare-side').count()>=4,'before and after are compared');assert.ok(await page.locator('.bulletin-compare.stack .bulletin-thumbs canvas').count()>0,'the sermon is shown as two scrolling rows');assert.ok(await page.locator('.bulletin-order-pane .added').count()>0&&await page.locator('.bulletin-order-pane .removed, .bulletin-order-pane .replaced').count()>0,'order panes mark what changes');await mkdir('artifacts',{recursive:true});await page.locator('.bulletin-staged').first().scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/bulletin-compare-1440.png'});await page.locator('.bulletin-compare.stack').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/bulletin-compare-sermon-1440.png'});assert.match(await page.locator('.bulletin-staged.bad').textContent(),/먼저 서버 저장/);
  await page.locator('#bulletinNext').click();await page.locator('.bulletin-results').waitFor();assert.match(await page.locator('.bulletin-results .bad').textContent(),/먼저 서버 저장/);await page.waitForFunction(()=>document.querySelector('#bulletinNext').textContent==='미리 보기 다시 만들기');assert.equal(await page.locator('#bulletinDialog').evaluate(d=>d.open),true,'a failure keeps the window open');
  await page.evaluate(()=>{YebaeonCloud.pendingDocuments=window.__pending;});await page.locator('#bulletinNext').click();await page.waitForFunction(()=>document.querySelector('#bulletinNext').textContent==='적용');await page.locator('#bulletinNext').click();await page.waitForFunction(()=>!document.querySelector('#bulletinDialog').open);assert.match(await page.locator('#status').textContent(),/Studio에 적용/);
  assert.equal(puts.length+patches.length,0,'적용 leaves everything as unsaved Studio work');
  const marked=async()=>(await page.locator('#playlistsList button').allTextContents()).filter(t=>/저장 (필요|안 됨)/.test(t)).map(t=>t.replace(/ · .*/,'')).sort();
  assert.deepEqual(await marked(),['1부 예배(품성)','2부 예배','금요예배','청년예배'],'every touched playlist is marked');
  await page.reload();await page.waitForFunction(()=>window.YebaeonBulletin&&YebaeonCloud.authenticated()&&YebaeonPlaylists.libraries().length);await page.waitForFunction(()=>/저장 필요/.test(document.querySelector('#playlistsList').textContent));
  assert.deepEqual(await marked(),['1부 예배(품성)','2부 예배','금요예배','청년예배'],'marks survive a reload');assert.equal(puts.length+patches.length,0);
  await page.waitForFunction(()=>!document.querySelector('#cloudSave').disabled);assert.match(await page.locator('#saveScope').textContent(),/문서 \d+ · 순서 3 수정/,'the save button counts every unsaved document and order');
  await page.locator('#cloudSave').click();await page.waitForFunction(()=>!YebaeonSave.busy()&&/저장됨|✓/.test(document.querySelector('#saveScope').textContent));
  assert.deepEqual(await marked(),[],'one save clears every playlist');assert.deepEqual([...patches].sort(),['1부 예배(품성)','2부 예배','청년예배']);assert.match(await page.locator('#status').textContent(),/서버 저장 완료/);
  await page.locator('#bulletinOpen').click();
  assert.equal(await page.locator('.bulletin-results .bad').count(),0);
  assert.deepEqual(names('1부 예배(품성)'),['첫화면','사도신경(구)','100 주 이름 가사','1부기도','광고','주일예배말씀','주일예배말씀 목사님 ppt','합성 찬양 D','옛 헌금','2026엔딩','마무리']);
  assert.deepEqual(names('청년예배'),['첫화면','사도신경(구)','합성 찬양 C','3부 기도','청년부 말씀','주일예배말씀 목사님 ppt','옛 설교후','광고','나의 모습 나의 소유','2026엔딩']);
  assert.deepEqual(names('2부 예배'),['첫화면','사도신경(구)','합성 찬양 A','2부 기도','광고','주일예배말씀','합성 찬양 D','옛 헌금','2026엔딩']);assert.deepEqual(patches.sort(),['1부 예배(품성)','2부 예배','청년예배']);
  assert.ok(!puts.includes('수요예배.pro6'));
  const x_split=made.split;const check=await page.evaluate(x=>{const t=xml=>{const m=PP6.parse(xml,'c');return PP6.slides(m).map(s=>({label:s.getAttribute('label'),boxes:PP6.textElements(s).map(b=>PP6.parseRTF(PP6.textNode(b).textContent))}));};
   const sermon=t(x.sermon),point=sermon.find(s=>s.boxes[0]?.text.startsWith('What?'));
   const runs=b=>b.runs.filter(r=>r.text.trim()).map(r=>[r.text.trim(),r.style.size,r.style.align]);return {p1:t(x.p1).map(s=>s.boxes.map(b=>b.text)),p1runs:runs(t(x.p1)[1].boxes[0]),p2:t(x.p2).map(s=>s.boxes.map(b=>b.text)),p2runs:runs(t(x.p2)[0].boxes[0]),prayer3:t(x.p3)[0].boxes[0].text,count:sermon.length,title:sermon[1].boxes[0].text,edges:[sermon[0].label,sermon.at(-1).label],labels:sermon.map(s=>s.label).filter(l=>/NKRV/.test(l)),point:point.boxes[0].text,underlined:point.boxes[0].runs.filter(r=>r.style.underline).map(r=>r.text),youth:t(x.youth).map(s=>s.boxes[0].text),youthBoxes:t(x.youth)[0].boxes.map(b=>b.text),friday:t(x.friday).length,fridayTitle:t(x.friday)[1].boxes.map(b=>b.text),fridaySizes:t(x.friday)[1].boxes[0].runs.filter(r=>r.text.trim()).map(r=>[r.text,r.style.size]),fridayLabels:t(x.friday).map(s=>s.label),fridayEnd:t(x.friday).at(-1).boxes.map(b=>b.text)};},
   {sermon:docs.get(byName('주일예배말씀')).xml,p1:docs.get(byName('1부기도')).xml,p2:docs.get(byName('2부 기도')).xml,p3:docs.get(byName('3부 기도')).xml,youth:docs.get(byName('청년부 말씀')).xml,friday:docs.get(byName('금요예배말씀')).xml,split:x_split});
  assert.deepEqual(check.p1,[[],['대표기도\n가나다 집사']],'the cover stays; of two prayer slides only the canonical two-line one remains');assert.deepEqual(check.p1runs,[['대표기도',120,'center'],['가나다 집사',150,'center']]);
  assert.deepEqual(check.p2,[['대표기도\n라마바 시무집사'],[]],'a one-line prayer slide becomes the canonical two lines');assert.deepEqual(check.p2runs,[['대표기도',120,'center'],['라마바 시무집사',150,'center']]);assert.equal(check.prayer3,'대표기도\n사아자 형제');
  assert.equal(check.count,14);assert.equal(check.title,'합성 시리즈3\n합성 설교\n제목!\n(창세기 1:1-3)','a line break typed in the title reaches the slide');
  assert.deepEqual(check.labels,['창세기 1:1 (NKRV)','창세기 1:2 (NKRV)','창세기 1:3 (NKRV)','창세기 1:1 (NKRV)','요한복음 13:36 (NKRV)','요한복음 13:37 (NKRV)']);
  assert.equal(check.point,'What? 합성 믿음의 원리는?\n믿음은\n의심이 아닙니다.\n믿기 위해 기도하십시오.','a line break typed in the point sentence reaches the slide');assert.deepEqual(check.edges,['표지','광고'],'slides outside the sermon format stay, gathered at the front and back');
  // 글상자가 있는 지난 제목 장은 그 장의 디자인(글꼴 크기 등)을 그대로 두고 글자만 바꾼다(10-05 금요예배: 말씀 서식으로 만들어 깨졌음).
 const textTitle=await page.evaluate(async xml=>{const r=await YebaeonBulletinDocuments.titlePassage(xml,'금요.pro6',{series:'새 시리즈',title:'새 제목',ref:'누가복음 11:1-2',passage:''},await YebaeonResources.bulletinMaterials(),{made:true});const s=PP6.slides(PP6.parse(r.xml,'t')),box=PP6.textElements(s[1])[0];return {labels:s.map(x=>x.getAttribute('label')),boxes:PP6.textElements(s[1]).map(b=>PP6.parseRTF(PP6.textNode(b).textContent).text),seriesSize:PP6.parseRTF(PP6.textNode(box).textContent).runs.find(x=>x.text.trim()).style.size};},made.fridayText);
 assert.deepEqual(textTitle,{labels:['표지','새 제목','새 제목'],boxes:['새 시리즈\n\n새 제목','(누가복음 11:1-2)'],seriesSize:40},'the old title slide keeps its own design');
 const wraps=await page.evaluate(xml=>{const m=PP6.parse(xml,'w'),ctx=document.createElement('canvas').getContext('2d');return PP6.slides(m).filter(s=>/NKRV/.test(s.getAttribute('label')||'')).map(s=>{const box=PP6.textElements(s)[0],parsed=PP6.parseRTF(PP6.textNode(box).textContent);return {text:parsed.text,drawn:PP6Render.layout(ctx,parsed,PP6.rect(box)).lines.length};});},docs.get(byName('주일예배말씀')).xml);
  const long=wraps.filter(w=>w.text.includes('\n'));assert.ok(long.length,'a long verse is split into lines');for(const w of wraps)assert.equal(w.drawn,w.text.split('\n').length,'verse lines break only between words, never by the renderer: '+w.text);
  assert.ok(wraps.every(w=>w.text.split('\n').every(l=>l===l.trim()&&l.length)),'no line starts or ends inside spacing');assert.deepEqual(check.underlined,['의심','기도']);
  assert.deepEqual(check.youthBoxes,['청년 합성 설교','','(요한복음 3:16)'],'boxes are filled by screen position; no series leaves the series box empty');assert.equal(check.friday,5);assert.deepEqual(check.fridayTitle,['합성 기도2\n\n금요 합성 제목','(누가복음 22:31-32)']);assert.ok(check.fridaySizes[0][1]<check.fridaySizes.at(-1)[1],'made title: the series is smaller than the title');assert.deepEqual(check.fridayLabels.filter(l=>!/NKRV/.test(l)),['금요기도회_PPT','금요 합성 제목','금요 합성 제목'],'the cover stays first; the old image title and trailing slides give way to the made title slide');
  // 주중 말씀 문서: [표지 → 제목 → 말씀 → 제목]. 끝 제목 장은 앞 제목 장과 글자가 같다.
  assert.deepEqual(check.fridayLabels.map(l=>/NKRV/.test(l)?'말씀':l==='금요기도회_PPT'?'표지':'제목').filter((k,i,a)=>k!==a[i-1]),['표지','제목','말씀','제목']);assert.deepEqual(check.fridayEnd,check.fridayTitle,'the closing title slide repeats the opening one');
  // Changed format: automatic regions are missed, so the user designates them from the full bulletin.
  await page.locator('#bulletinFile').setInputFiles({name:'changed.hwp',mimeType:'application/octet-stream',buffer:syntheticHWP({changed:true})});await page.waitForFunction(()=>YebaeonBulletin.state()?.file==='changed.hwp');
  await page.locator('.bulletin-svc button',{hasText:'2부'}).click();assert.equal(await slot('찬양 1').locator('[id^=bulletin-]').inputValue(),'');
  await page.locator('#bulletinSource .bulletin-source-bar input').check();const cell=text=>page.locator('#bulletinSource .bulletin-cell',{hasText:text});
  await slot('찬양 1').click();await cell('합성 찬양 A').locator('.bulletin-line',{hasText:'합성 찬양 A'}).locator('.pil').click();
  await page.getByRole('button',{name:'+ 찬양 추가',exact:true}).click();await cell('합성 찬양 B').locator('.bulletin-line',{hasText:'합성 찬양 B'}).locator('.pil').click();
  assert.deepEqual(await page.locator('.bulletin-slot input[id^=bulletin-]').evaluateAll(xs=>xs.slice(0,2).map(x=>x.value)),['합성 찬양 A','합성 찬양 B']);
  await page.locator('#bulletinSteps button',{hasText:'기도'}).click();await slot('1부 기도').click();await page.locator('#bulletinSource .bulletin-line',{hasText:'가나다집사 /'}).locator('.pil').click();
  assert.deepEqual(await page.locator('.bulletin-slot input[id^=bulletin-]').evaluateAll(xs=>xs.map(x=>x.value)),['가나다집사','라마바시무집사','사아자형제'],'one prayer line fills all services');
  await page.locator('#bulletinSteps button',{hasText:'주일말씀'}).click();await cell('질문 합성').locator('.bulletin-cell-tools button',{hasText:'설교 노트로'}).click();
  assert.equal(await slot('대지 질문').locator('[id^=bulletin-]').inputValue(),'질문 합성 믿음의 원리는?');assert.equal(await slot('빈칸 1').locator('[id^=bulletin-]').inputValue(),'');
  await cell('하나, 믿음은').locator('.bulletin-cell-tools button',{hasText:'말씀 요약으로'}).click();assert.equal(await slot('빈칸 1').locator('[id^=bulletin-]').inputValue(),'의심');assert.match(await page.locator('#bulletinMessage').textContent(),/빈칸 3개/);
  await page.locator('#bulletinSteps button',{hasText:'주중말씀'}).click();await cell('파하가전도사').locator('.bulletin-cell-tools button',{hasText:'주중예배 칸으로'}).click();
  assert.match(await page.locator('.bulletin-group',{hasText:'금요예배'}).textContent(),/금요 합성 제목/);
  await page.locator('#bulletinSource .bulletin-source-bar input').uncheck();
  // Mobile: the work column is primary and the bulletin opens as a sheet; lines expand into word buttons.
  await page.setViewportSize({width:390,height:844});await page.locator('#bulletinSteps button',{hasText:'찬양'}).click();await page.locator('.bulletin-svc button',{hasText:'2부'}).click();
  assert.equal(await page.locator('#bulletinSource').isVisible(),false);await slot('찬양 2').locator('.src').click();await page.locator('#bulletinSheet').waitFor();
  await page.locator('#bulletinSheet .bulletin-mline',{hasText:'합성 찬양 B'}).click();await page.locator('#bulletinSheet .bulletin-chips button',{hasText:/^B$/}).click();assert.equal(await page.locator('#bulletinSheet .bulletin-sheet-head span').textContent(),'B');
  await page.locator('#bulletinSheet .primary').click();assert.equal(await page.locator('#bulletinSheet').isVisible(),false);assert.equal(await slot('찬양 2').locator('[id^=bulletin-]').inputValue(),'B');
  // 파란 단추는 마우스를 올려도 흰 글씨가 보일 만큼 진한 배경을 유지한다.
  await page.locator('#bulletinStart .file-start-dropbox').hover();assert.equal(await page.locator('#bulletinStart .file-start-dropbox').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(58, 65, 160)');
  await page.locator('#bulletinStart .file-start-dropbox').click();await page.waitForFunction(()=>document.querySelector('#bulletinStart .dropbox-picker').textContent.includes('최초 연결'));await page.locator('#bulletinStart .file-start-dropbox').click();
  const catalog=JSON.parse(await readFile('church-resources/catalog.json','utf8'));const chosenFont=catalog.fonts.find(f=>f.name==='NanumBarunGothicOTF-YetHangul');if(chosenFont){const font=await readFile('church-resources/'+chosenFont.file);await page.addStyleTag({content:`@font-face{font-family:TestKorean;src:url(data:font/woff2;base64,${font.toString('base64')})}body,button,input,select,textarea{font-family:TestKorean,sans-serif!important}`});await page.evaluate(()=>document.fonts.ready);}
  await mkdir('artifacts',{recursive:true});
  for(const step of ['찬양','주일말씀']){await page.locator('#bulletinSteps button',{hasText:step}).click();
   for(const [w,h] of [[1440,960],[768,1024],[390,844],[320,568],[390,480]]){await page.setViewportSize({width:w,height:h});
    const layout=await page.evaluate(()=>{const d=document.querySelector('#bulletinDialog'),body=d.querySelector('#bulletinWork'),foot=d.querySelector('.bulletin-actions'),header=d.querySelector('header'),tabs=d.querySelector('#bulletinStart');body.scrollTop=body.scrollHeight;const b=body.getBoundingClientRect(),f=foot.getBoundingClientRect(),r=d.getBoundingClientRect(),c=header.getBoundingClientRect();const btns=[...foot.querySelectorAll('button')].filter(b=>!b.hidden).map(b=>b.getBoundingClientRect());return {buttons:btns.every(x=>x.left>=r.left-1&&x.right<=r.right+1&&x.width>=40),horizontal:body.scrollWidth>body.clientWidth+1||tabs.scrollWidth>tabs.clientWidth+1,dialog:r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1,footer:f.top>=b.bottom-1&&f.bottom<=r.bottom+1,header:c.top>=r.top,scrolls:body.scrollHeight>body.clientHeight,atEnd:body.scrollTop>0};});
    assert.equal(layout.horizontal,false,`modal overflow ${step} ${w}`);assert.ok(layout.dialog&&layout.footer&&layout.header&&layout.buttons,JSON.stringify({step,w,...layout}));if(h<=568)assert.ok(layout.scrolls&&layout.atEnd,`body scroll ${w}`);
    await page.locator('#bulletinWork').evaluate(el=>el.scrollTop=0);await page.screenshot({path:`artifacts/bulletin-${step==='찬양'?'song':'sermon'}-${w}-${h}.png`});}}
  dropboxReady=true;await page.locator('#bulletinStart .file-start-dropbox').click();await page.locator('#bulletinStart .dropbox-row').first().waitFor();assert.deepEqual(await page.locator('#bulletinStart .dropbox-row>span').allTextContents(),['가 폴더','예배별 주보 자료와 오래된 자료 폴더','아주 긴 이름의 합성 주보 자료 2026년 10월 첫째 주.hwp','0927 주보.hwp'],'folders by name, newest bulletin first');assert.equal(dropboxPaths.at(-1),'HANWOORI/06주보/주일주보','bulletin opens the Sunday bulletin folder');assert.ok(documentSearches.length&&documentSearches.every(x=>x==='relevance/1'),'bulletin searches use the shared relevance + body-index search: '+[...new Set(documentSearches)].join(','));
  for(const [w,h] of [[1440,960],[768,1024],[390,844],[320,568]]){await page.setViewportSize({width:w,height:h});assert.equal(await page.locator('#bulletinStart').evaluate(el=>el.scrollWidth>el.clientWidth+1),false,`Dropbox overflow ${w}`);await page.screenshot({path:`artifacts/dropbox-${w}.png`});}
  await page.locator('#bulletinClose').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await page.locator('#bulletinOpen').isVisible(),true);assert.deepEqual(errors,[]);
  // Hand edits: leaving a changed playlist asks to save it first.
  await page.setViewportSize({width:1440,height:960});const openList=async n=>{await page.evaluate(n=>[...document.querySelectorAll('#playlistsList button')].find(b=>b.textContent.startsWith(n)).click(),n);await page.waitForFunction(n=>document.querySelector('#playlistsList button.active')?.textContent.startsWith(n)&&!YebaeonSave.busy()&&!YebaeonPlaylists.state().busy,n);};
  await openList('수요예배');await page.evaluate(async()=>{const d=(await YebaeonSearch.query('마무리')).documents.find(x=>x.name==='마무리.pro6');YebaeonPlaylists.appendDocuments([d]);});assert.equal(await page.evaluate(()=>YebaeonPlaylists.state().dirty),true);
  const patched=patches.length;dialogs.length=0;await openList('금요예배');assert.ok(dialogs.some(m=>/저장하고 넘어갈까요/.test(m)),dialogs.join('|'));assert.equal(patches.length,patched+1);assert.deepEqual(names('수요예배'),['첫화면','수요예배','마무리']);
  await page.evaluate(async()=>{const d=(await YebaeonSearch.query('마무리')).documents.find(x=>x.name==='마무리.pro6');YebaeonPlaylists.appendDocuments([d]);});dismiss=true;await openList('수요예배');assert.equal(patches.length,patched+1,'cancel moves on without saving');
  await page.waitForFunction(()=>/금요예배 · 저장 필요/.test(document.querySelector('#playlistsList').textContent));  assert.deepEqual(await marked(),['금요예배'],'the left playlist waits as 저장 필요');await page.locator('#cloudSave').click();await page.waitForFunction(()=>!YebaeonSave.busy()&&/저장됨|✓/.test(document.querySelector('#saveScope').textContent));
  assert.equal(patches.at(-1),'금요예배');assert.deepEqual(names('금요예배'),['첫화면','금요예배말씀','마무리']);assert.deepEqual(await marked(),[]);
  console.log('Bulletin browser passed: HWP understanding, region designation after a format change, song candidates without auto replace, word/line picking, review before save, pending-document guard and retry, prayer/sermon/weekday documents edited in place, playlist slots and youth sermon swap, mobile sheet, Dropbox, bounded dialogs at 320/390/768/1440px.');
 }catch(e){console.error('UI errors',errors,await page.locator('#bulletinMessage').textContent().catch(()=>''),await page.evaluate(()=>({status:document.querySelector('#status').textContent,pl:document.querySelector('#playlistsMessage').textContent,scope:document.querySelector('#saveScope').textContent,save:document.querySelector('#cloudSave').disabled,lists:[...document.querySelectorAll('#playlistsList button')].map(b=>b.textContent+(b.classList.contains('active')?'*':'')),st:YebaeonPlaylists.state()})).catch(()=>''),e.stack);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
