const {chromium}=require('playwright');const {createServer}=require('node:http');const {readFile,mkdir}=require('node:fs/promises');const {resolve,extname,sep}=require('node:path');const {createHash,randomUUID}=require('node:crypto');const assert=require('node:assert/strict');
(async()=>{const {syntheticHWP}=await import('../bulletin.test.mjs');const root=resolve('web-editor'),server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://x').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const libraryId=randomUUID(),docs=new Map();let order=[],pv=1,xml='',template='',writes=0,failCreate=false;const hash=()=>createHash('sha256').update(JSON.stringify(order)).digest('hex');const metadata=id=>({id,name:docs.get(id).path.split('/').pop(),path:docs.get(id).path,version:1,sha256:createHash('sha256').update(docs.get(id).xml).digest('hex'),available:true,updatedAt:'2026-10-03T00:00:00Z'});const library=()=>({id:libraryId,path:'기본.pro6pl',version:pv,playlists:[{id:'A',name:'1부예배',itemCount:order.length}],updatedAt:'2026-10-03T00:00:00Z'});
 await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname;let data={};if(path==='/api/session')data={ready:true,authenticated:true,name:'시험'};else if(path==='/api/sync-observations')data={items:{}};else if(path==='/api/dropbox/config')data={ready:false};else if(path==='/api/playlists')data={libraries:[library()],next:null};else if(path.endsWith('/plan'))data={library:library(),playlist:{id:'A',name:'1부예배',editable:true,sha256:hash()},items:order.map((x,i)=>({id:String(i),kind:'document',documentId:x,document:metadata(x),name:metadata(x).name})),ready:true};else if(path==='/api/playlists/'+libraryId&&req.method()==='PATCH'){assert.equal(req.headers()['if-match'],`"${pv}"`);order=JSON.parse(req.postData()).items.map(x=>x.documentId);pv++;data={library:library(),playlist:{sha256:hash()}};}else if(path==='/api/documents'&&req.method()==='POST'){if(failCreate){failCreate=false;await route.fulfill({status:503,json:{message:'시험용 일시 실패'}});return;}const existing=[...docs.keys()].find(id=>docs.get(id).path===u.searchParams.get('path'));const id=existing||randomUUID();if(existing)assert.equal(docs.get(id).xml,req.postData());else{docs.set(id,{path:u.searchParams.get('path'),xml:req.postData()});writes++;}data={document:metadata(id)};}else if(path==='/api/documents')data={documents:[...docs.keys()].filter(id=>docs.get(id).path.includes(u.searchParams.get('q')||'')).map(metadata),next:null};else if(path.startsWith('/api/documents/')){const id=path.split('/')[3];if(!docs.has(id)){await route.fulfill({status:404,json:{message:'없음'}});return;}if(path.endsWith('/content')){await route.fulfill({body:docs.get(id).xml,contentType:'application/xml'});return;}data={document:metadata(id)};}else throw Error('Unexpected '+path);await route.fulfill({json:data});});
 await page.route('**/resources/**',async route=>{const name=new URL(route.request().url()).pathname.split('/').pop();await route.fulfill({json:name==='catalog.json'?{fonts:[],media:[]}:name==='templates.json'?[{id:'104',name:'말씀',label:'본문',width:1920,height:1080,xml:template}]:{books:[{name:'창세기',chapters:[{number:1,verses:[{number:1,text:'첫째 절'},{number:2,text:'둘째 절'}]}]}]}});});
 try{await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.YebaeonBulletin&&YebaeonCloud.authenticated());xml=await page.evaluate(()=>YebaeonLibraryActions.blankDocument('예배순서'));template=await page.evaluate(xml=>{const m=PP6.parse(xml,'template'),s=PP6.slides(m)[0],b=PP6.textElements(s)[0],ref=b.cloneNode(true);PP6.refreshIDs(ref);b.parentNode.append(ref);return new XMLSerializer().serializeToString(s);},xml);for(const name of ['찬송가 100','합성 찬양 A','합성 찬양 B','합성 찬양 C','합성 찬양 D'])docs.set(randomUUID(),{path:name+'.pro6',xml});await page.reload();await page.waitForFunction(()=>window.YebaeonBulletin&&YebaeonCloud.authenticated());
 if(process.env.BULLETIN_FIXTURE_DIR){const fs=require('node:fs');for(const name of fs.readdirSync(process.env.BULLETIN_FIXTURE_DIR).filter(n=>n.endsWith('.hwp'))){const bytes=fs.readFileSync(require('node:path').join(process.env.BULLETIN_FIXTURE_DIR,name));const extracted=await page.evaluate(bytes=>YebaeonBulletinParser.parse(Uint8Array.from(bytes)),[...bytes]);assert.equal(extracted.services.length,3);assert.equal(extracted.warnings.length,0);console.log('Private HWP verified:',extracted.date,extracted.services.map(s=>s.items.filter(i=>i.kind==='song').length).join('/'));}}
 await page.locator('#bulletinOpen').click();await page.locator('#bulletinFile').setInputFiles({name:'synthetic.hwp',mimeType:'application/octet-stream',buffer:syntheticHWP()});await page.waitForFunction(()=>YebaeonBulletin.state()?.date==='2026-10-04');assert.equal(await page.locator('#bulletinDate').inputValue(),'2026-10-04');await page.locator('#bulletinFind').click();await page.waitForFunction(()=>!document.querySelector('#bulletinFind').disabled);assert.equal(await page.evaluate(()=>YebaeonBulletin.state().services[0].items.find(r=>r.kind==='song').document.name),'찬송가 100.pro6');
 // Explicitly omit unlisted/fixed items for this synthetic preparation.
 await page.evaluate(()=>{for(const r of YebaeonBulletin.state().services[0].items)if(['fixed','unknown'].includes(r.kind))r.skip=true;});
 await page.locator('#bulletinService').selectOption('0');
 const preview=page.locator('.bulletin-row').filter({has:page.locator('textarea[aria-label="말씀 본문 주보 내용"]')});await preview.getByText('생성 미리보기',{exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('#bulletinPreview canvas').length===2&&!document.querySelector('#bulletinFind').disabled);
 // Actual generated XML must preserve two separate Bible verses.
 const prayer=page.locator('.bulletin-row').filter({has:page.locator('textarea[aria-label="대표기도 주보 내용"]')});await prayer.getByText('생성 미리보기',{exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#bulletinFind').disabled);
 failCreate=true;await page.locator('#bulletinApply').click();await page.waitForFunction(()=>document.querySelector('#bulletinMessage').textContent.includes('시험용 일시 실패'));assert.equal(order.length,0);await page.reload();await page.waitForFunction(()=>window.YebaeonBulletin&&YebaeonCloud.authenticated());await page.locator('#bulletinOpen').click();await page.waitForFunction(()=>YebaeonBulletin.state());await page.locator('#bulletinApply').click();await page.waitForFunction(()=>!document.querySelector('#bulletinDialog').open);assert.equal(writes,3);assert.equal(order.length,0);assert.equal(await page.evaluate(()=>YebaeonPlaylists.state().dirty),true);await page.evaluate(()=>YebaeonSave.save());assert.equal(order.length,5);assert.equal(await page.evaluate(()=>YebaeonPlaylists.state().dirty),false);assert.equal(docs.size,8);
 await page.locator('#bulletinOpen').click();await page.locator('#dropboxTab').click();await page.waitForFunction(()=>document.querySelector('#dropboxMessage').textContent.includes('최초 연결'));await page.locator('#bulletinTab').click();await page.locator('#bulletinService').selectOption('1');assert.equal(await page.locator('#bulletinRows textarea[aria-label="대표기도 주보 내용"]').inputValue(),'나권사');
 const catalog=JSON.parse(await readFile('church-resources/catalog.json','utf8'));const chosenFont=catalog.fonts.find(f=>f.name==='NanumBarunGothicOTF-YetHangul');if(chosenFont){const font=await readFile('church-resources/'+chosenFont.file);await page.addStyleTag({content:`@font-face{font-family:TestKorean;src:url(data:font/woff2;base64,${font.toString('base64')})}body,button,input,select,textarea{font-family:TestKorean,sans-serif!important}`});await page.evaluate(()=>document.fonts.ready);} 
 await mkdir('artifacts',{recursive:true});for(const [w,h] of [[1440,960],[820,1180],[390,844]]){await page.setViewportSize({width:w,height:h});await page.screenshot({path:`artifacts/bulletin-${w}.png`});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,`overflow ${w}`);}
 await page.locator('#bulletinClose').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await page.locator('#bulletinOpen').isVisible(),true);assert.deepEqual(errors,[]);console.log('Bulletin browser passed: HWP upload, title match, Bible generation, failure/reload/retry, staged playlist save, Dropbox unconfigured, 3 sizes.');
 }catch(e){console.error('UI errors',errors,await page.locator('#bulletinMessage').textContent().catch(()=>''));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
