const {chromium}=require('playwright');const {createServer}=require('node:http');const {readFile,mkdir}=require('node:fs/promises');const {resolve,extname,sep}=require('node:path');const {createHash,randomUUID}=require('node:crypto');const assert=require('node:assert/strict');
(async()=>{const {zipSync,strToU8}=await import('fflate');const root=resolve('dist'),server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://x').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const libraryId=randomUUID(),docs=new Map();const media=new Map();let order=[],pv=1,xml='',template='',writes=0,failCreate=false;const hash=()=>createHash('sha256').update(JSON.stringify(order)).digest('hex');const metadata=id=>({id,name:docs.get(id).path.split('/').pop(),path:docs.get(id).path,version:1,sha256:createHash('sha256').update(docs.get(id).xml).digest('hex'),available:true,updatedAt:'2026-10-03T00:00:00Z'});const library=()=>({id:libraryId,path:'기본.pro6pl',version:pv,playlists:[{id:'A',name:'1부예배',itemCount:order.length}],updatedAt:'2026-10-03T00:00:00Z'});
 await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname;let data={};if(path==='/api/session')data={ready:true,authenticated:true,name:'시험'};else if(path==='/api/sync-observations')data={items:{}};else if(path==='/api/dropbox/config')data={ready:false};else if(path==='/api/playlists')data={libraries:[library()],next:null};else if(path.endsWith('/plan'))data={library:library(),playlist:{id:'A',name:'1부예배',editable:true,sha256:hash()},items:order.map((x,i)=>({id:String(i),kind:'document',documentId:x,document:metadata(x),name:metadata(x).name})),ready:true};else if(path==='/api/playlists/'+libraryId&&req.method()==='PATCH'){assert.equal(req.headers()['if-match'],`"${pv}"`);order=JSON.parse(req.postData()).items.map(x=>x.documentId);pv++;data={library:library(),playlist:{sha256:hash()}};}else if(path==='/api/media'){data={assets:u.searchParams.getAll('hash').filter(h=>media.has(h)).map(sha256=>({sha256}))};}else if(path.startsWith('/api/media/')){const digest=path.split('/')[3];if(req.method()==='PUT'){const b=req.postDataBuffer();assert.equal(createHash('sha256').update(b).digest('hex'),digest);media.set(digest,b);data={asset:{sha256:digest}};}else{assert.ok(media.has(digest));await route.fulfill({body:media.get(digest),contentType:'image/png'});return;}}else if(path==='/api/documents'&&req.method()==='POST'){if(failCreate){failCreate=false;await route.fulfill({status:503,json:{message:'시험용 일시 실패'}});return;}const existing=[...docs.keys()].find(id=>docs.get(id).path===u.searchParams.get('path'));const id=existing||randomUUID();if(existing)assert.equal(docs.get(id).xml,req.postData());else{docs.set(id,{path:u.searchParams.get('path'),xml:req.postData()});writes++;}data={document:metadata(id)};}else if(path==='/api/documents')data={documents:[...docs.keys()].filter(id=>docs.get(id).path.includes(u.searchParams.get('q')||'')).map(metadata),next:null};else if(path.startsWith('/api/documents/')){const id=path.split('/')[3];if(!docs.has(id)){await route.fulfill({status:404,json:{message:'없음'}});return;}if(path.endsWith('/content')){await route.fulfill({body:docs.get(id).xml,contentType:'application/xml'});return;}data={document:metadata(id)};}else throw Error('Unexpected '+path);await route.fulfill({json:data});});
 await page.route('**/resources/**',async route=>{const name=new URL(route.request().url()).pathname.split('/').pop();await route.fulfill({json:name==='catalog.json'?{fonts:[],media:[]}:name==='templates.json'?[{id:'104',name:'말씀',label:'본문',width:1920,height:1080,xml:template}]:{books:[{name:'창세기',chapters:[{number:1,verses:[{number:1,text:'첫째 절'},{number:2,text:'둘째 절'}]}]}]}});});
 try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.YebaeonPPTImport&&YebaeonCloud.authenticated());
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=450;const x=c.getContext('2d');x.fillStyle='orange';x.fillRect(15,5,250,60);x.fillStyle='black';for(let y=100;y<200;y+=12)x.fillRect(30,y,730,3);x.font='28px sans-serif';x.fillText('SYNTHETIC SCORE',50,260);return c.toDataURL().split(',')[1];});
 const ns='xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"';
 const files={'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/></Types>','ppt/presentation.xml':`<p:presentation ${ns}><p:sldIdLst><p:sldId id="256" r:id="r1"/><p:sldId id="257" r:id="r2"/></p:sldIdLst><p:sldSz cx="9144000" cy="5143500"/></p:presentation>`,'ppt/_rels/presentation.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/><Relationship Id="r2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide2.xml"/></Relationships>'};
 for(let i=1;i<=2;i++){files[`ppt/slides/slide${i}.xml`]=`<p:sld ${ns}><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="C8D8E8"/></a:solidFill></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr/><p:grpSpPr/><p:pic><p:nvPicPr><p:cNvPr id="2" name="score"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="img"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="9144000" cy="5143500"/></a:xfrm><a:prstGeom prst="rect"/></p:spPr></p:pic><p:sp><p:nvSpPr><p:cNvPr id="3" name="footer"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="0" y="4800000"/><a:ext cx="9144000" cy="300000"/></a:xfrm></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr sz="1200"/><a:t>1 5 9 11</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>`;files[`ppt/slides/_rels/slide${i}.xml.rels`]='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="img" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/score.png"/></Relationships>';}
 const zipped={};for(const[k,v]of Object.entries(files))zipped[k]=strToU8(v);zipped['ppt/media/score.png']=Buffer.from(png,'base64');const fixture=Buffer.from(zipSync(zipped));
 await page.locator('#pptOpen').click();await page.locator('#pptFile').setInputFiles({name:'synthetic.pptx',mimeType:'application/octet-stream',buffer:fixture});await page.waitForFunction(()=>!YebaeonPPTImport.state().busy);assert.equal(await page.evaluate(()=>YebaeonPPTImport.state().deck?.slides.length),2);
 await page.locator('#pptPreview').click();await page.waitForFunction(()=>!YebaeonPPTImport.state().busy);assert.equal(await page.evaluate(()=>YebaeonPPTImport.state().outputs.length),2,await page.locator('#pptMessage').textContent());
 await page.locator('[name=pptMode][value=score]').check();await page.locator('#pptPreview').click();await page.waitForFunction(()=>!YebaeonPPTImport.state().busy);assert.equal(await page.evaluate(()=>YebaeonPPTImport.state().outputs.length),2,await page.locator('#pptMessage').textContent());
 const alpha=await page.evaluate(async()=>{const a=[];for(const o of YebaeonPPTImport.state().outputs){const im=await createImageBitmap(o.foreground),c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0);a.push(c.getContext('2d').getImageData(100,60,1,1).data[3]);im.close();}return a;});assert.deepEqual(alpha,[255,0]);
 failCreate=true;await page.locator('#pptReviewed').check();await page.locator('#pptSave').click();await page.waitForFunction(()=>!YebaeonPPTImport.state().busy);assert.match(await page.locator('#pptMessage').textContent(),/시험용 일시 실패/);assert.equal(writes,0);
 await page.reload();await page.waitForFunction(()=>window.YebaeonPPTImport&&YebaeonCloud.authenticated());await page.locator('#pptOpen').click();await page.waitForFunction(()=>!document.querySelector('#pptRecovery').hidden);await page.locator('#pptResume').click();await page.waitForFunction(()=>!document.querySelector('#pptDialog').open);assert.equal(writes,1);assert.ok(media.size===3);assert.equal(await page.evaluate(()=>YebaeonPlaylists.memberIDs().length),1);
 const importedXML=[...docs.values()][0].xml;assert.equal((importedXML.match(/<RVDisplaySlide /g)||[]).length,2);assert.equal((importedXML.match(/<RVMediaCue /g)||[]).length,2);assert.equal((importedXML.match(/<RVTextElement/g)||[]).length,0);
 await page.locator('#pptOpen').click();await page.locator('#pptBackgroundEdit').evaluate(el=>el.open=true);const before=await page.evaluate(()=>PP6.slides(YebaeonEditor.model()).map(s=>PP6.ivar(s,'array','displayElements').innerHTML));await page.locator('#pptEditColor').fill('#e9dbef');await page.locator('#pptEditApply').click();await page.waitForFunction(()=>!document.querySelector('#pptDialog').open);assert.deepEqual(await page.evaluate(()=>PP6.slides(YebaeonEditor.model()).map(s=>PP6.ivar(s,'array','displayElements').innerHTML)),before);assert.equal(await page.evaluate(()=>YebaeonEditor.state().dirty),true);
 await page.locator('#pptOpen').click();await page.locator('#pptBackgroundEdit').evaluate(el=>el.open=false);
 if(process.env.PPT_FIXTURE_DIR){const fs=require('node:fs');for(const name of fs.readdirSync(process.env.PPT_FIXTURE_DIR).filter(n=>/\.pptx?$/i.test(n))){const bytes=fs.readFileSync(resolve(process.env.PPT_FIXTURE_DIR,name));await page.locator('#pptFile').setInputFiles({name,mimeType:'application/octet-stream',buffer:bytes});await page.waitForFunction(()=>!YebaeonPPTImport.state().busy);assert.equal(await page.evaluate(()=>YebaeonPPTImport.state().deck?.slides.length),12,await page.locator('#pptMessage').textContent());await page.locator('[name=pptMode][value=score]').check();await page.locator('#pptPreview').click();await page.waitForFunction(()=>!YebaeonPPTImport.state().busy);assert.equal(await page.evaluate(()=>YebaeonPPTImport.state().outputs.length),12,await page.locator('#pptMessage').textContent());console.log('Private score 12 slides passed:',name.endsWith('.PPT')?'PPT':'PPTX');}}
 await mkdir('artifacts',{recursive:true});const catalog=JSON.parse(await readFile('church-resources/catalog.json','utf8')),chosen=catalog.fonts.find(f=>f.name==='NanumBarunGothicOTF-YetHangul');if(chosen){const font=await readFile('church-resources/'+chosen.file);await page.addStyleTag({content:`@font-face{font-family:TestKorean;src:url(data:font/woff2;base64,${font.toString('base64')})}body,button,input,select,textarea{font-family:TestKorean,sans-serif!important}`});await page.evaluate(()=>document.fonts.ready);}
 for(const [width,height]of[[1440,960],[820,1180],[390,844]]){await page.setViewportSize({width,height});await page.screenshot({path:`artifacts/ppt-${width}.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}
 await page.locator('#pptClose').click();assert.ok(await page.locator('#pptOpen').isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(errors,[]);console.log('PPT browser passed: full/score, alpha crop, save/reload/retry, playlist draft, background-only edit, 3 viewports.');
 }catch(e){console.error(errors,await page.locator('#pptMessage').textContent().catch(()=>''));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
