const {chromium}=require('playwright');
const {createServer}=require('node:http');
const {readFile,mkdir}=require('node:fs/promises');
const {resolve,extname}=require('node:path');
const {createHash}=require('node:crypto');
const assert=require('node:assert/strict');
(async()=>{
 const root=resolve('web-editor');const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 let xml='',version=1,playlistVersion=1,order=[];
 const id='11111111-1111-4111-a111-111111111111',libraryID='22222222-2222-4222-a222-222222222222';
 const doc=()=>({id,path:'시험 문서.pro6',name:'시험 문서.pro6',version,updatedBy:'시험',updatedAt:'2026-10-02T00:00:00Z',lastDateUsed:'2026-10-01T00:00:00Z',useCount:1,sha256:createHash('sha256').update(xml).digest('hex')});
 const library=()=>({id:libraryID,path:'기본.pro6pl',version:playlistVersion,updatedBy:'시험',updatedAt:'2026-10-02T00:00:00Z',playlists:[{id:'A',name:'금요기도회',itemCount:order.length}]});
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url()),path=u.pathname,method=route.request().method();let data={};
 if(path==='/api/session')data={ready:true,authenticated:true,name:'시험'};
 else if(path==='/api/documents')data={documents:xml?[doc()]:[],next:null};
 else if(path==='/api/documents/'+id+'/content'){await route.fulfill({body:xml,contentType:'application/xml'});return;}
 else if(path==='/api/documents/'+id){if(method==='PUT'){xml=route.request().postData();version++;}data={document:doc()};}
 else if(path==='/api/playlists')data={libraries:xml?[library()]:[],next:null};
 else if(path.endsWith('/plan'))data={library:library(),playlist:{id:'A',name:'금요기도회',editable:true},ready:true,items:order.map((x,i)=>({kind:'document',id:x.id||'cue'+i,name:doc().name,document:doc(),sharedWith:[]}))};
 else if(path==='/api/playlists/'+libraryID&&method==='PATCH'){order=JSON.parse(route.request().postData()).items;playlistVersion++;data={library:library()};}
 else if(path==='/api/activity')data={items:[{kind:'document',...doc(),author:'시험',createdAt:doc().updatedAt}],next:null};
 else if(path.endsWith('/versions'))data={versions:[],next:null};
 else throw Error('Unhandled '+path);
 await route.fulfill({json:data});});
 let template;
 const books=Array.from({length:66},(_,i)=>({name:i===42?'요한복음':'책'+i,chapters:[{number:3,verses:Array.from({length:36},(_,i)=>({number:i+1,text:'하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니 믿는 자마다 영생을 얻게 하려 하심이라.'}))},{number:4,verses:[{number:1,text:'첫 번째 절입니다.'},{number:2,text:'두 번째 절입니다.'}]}]}));
 await page.route('**/resources/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('.png')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});return;}await route.fulfill({json:path.endsWith('catalog.json')?{fonts:[],media:[{name:'교회 배경',file:'fixture.png',source:'file:///Users/procg/Media/%EB%B0%B0%EA%B2%BD%20%3A%20%253A.png'}]}:path.endsWith('templates.json')?(template?[template]:[]):{books}});});
 await mkdir('artifacts',{recursive:true});
 try{
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.YebaeonCloud&&window.YebaeonResources);
 await page.addScriptTag({path:'web-editor/sample-demo.js'});
 xml=await page.evaluate(()=>{const m=PP6.parse(PP6_SAMPLE.xml,'test.pro6');for(const slide of PP6.slides(m)){const box=PP6.textElements(slide)[0],ref=box.cloneNode(true);PP6.refreshIDs(ref);PP6.setText(ref,'요한복음 3:16');ref.querySelector('RVRect3D').textContent='{120 900 0 1680 100}';box.parentNode.append(ref);}return PP6.serialize(m);});
 order=[{id:'cue0'},{id:'cue1'}];await page.evaluate(()=>YebaeonCloud.refresh());await page.locator('#libraryList .document-item').click();await page.waitForFunction(()=>YebaeonEditor.ready());await page.evaluate(()=>YebaeonPlaylists.show());
 assert.equal(await page.locator('.slide-card').count(),3);
 await page.locator('.slide-card').first().click();await page.locator('.slide-card').nth(2).click({modifiers:['Shift']});assert.equal(await page.locator('.slide-card.selected').count(),3);await page.locator('.slide-card').nth(1).click({modifiers:['Control']});assert.equal(await page.locator('.slide-card.selected').count(),2);
 await page.locator('#libraryList .document-item').dragTo(page.locator('#playlistItems .order-item').first());await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,3);
 await page.locator('.slide-card').first().click();await page.keyboard.press('Enter');await page.locator('#quickInputs textarea').first().waitFor();await page.locator('#quickInputs textarea').first().fill('빠른 편집 시험');await page.keyboard.press('Escape');await page.locator('#quickDialog').waitFor({state:'hidden'});
 await page.locator('#slidePane').focus();await page.keyboard.press('Control+z');assert.notEqual(await page.evaluate(()=>PP6.parseRTF(PP6.textNode(PP6.textElements(YebaeonEditor.current())[0]).textContent).text),'빠른 편집 시험');await page.keyboard.press('Control+Shift+z');
 await page.keyboard.press('Control+s');await page.waitForFunction(()=>!YebaeonEditor.state().dirty);assert.equal(version,2);
 await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');assert.equal(await page.locator('.slide-card').count(),4);await page.keyboard.press('Delete');assert.equal(await page.locator('.slide-card').count(),3);
 await page.keyboard.down('AltLeft');await page.keyboard.press('KeyR');await page.keyboard.up('AltLeft');await page.locator('#reflowRows textarea').first().fill('앞부분 뒷부분');await page.locator('#reflowRows textarea').first().evaluate(e=>e.setSelectionRange(3,3));await page.keyboard.down('AltLeft');await page.keyboard.press('Enter');await page.keyboard.up('AltLeft');assert.equal(await page.locator('#reflowRows textarea').count(),4);await page.keyboard.press('Backspace');assert.equal(await page.locator('#reflowRows textarea').count(),3);
 await page.locator('#reflowClose').click();await page.locator('.slide-card').first().click({button:'right'});const chosen=await page.evaluate(()=>YebaeonEditor.selected());await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>YebaeonEditor.selected()),chosen);await page.keyboard.press('Escape');
 await page.locator('#slidePane').focus();await page.evaluate(()=>document.getElementById('slidePane').dispatchEvent(new KeyboardEvent('keydown',{code:'Delete',isComposing:true,bubbles:true})));assert.equal(await page.locator('.slide-card').count(),3);
 await page.locator('#mediaOpen').click();await page.locator('#mediaGrid button').first().dragTo(page.locator('.slide-card').first());assert.equal(await page.evaluate(()=>PP6.attr(PP6.mediaElements(YebaeonEditor.current())[0],'source')),'file:///Users/procg/Media/%EB%B0%B0%EA%B2%BD%20%3A%20%253A.png');assert.equal(await page.evaluate(async()=>!!(await YebaeonResources.media('/Users/procg/Media/배경 : %3A.png'))),true);assert.equal(await page.evaluate(async()=>!!(await YebaeonResources.media('/Users/procg/Media/배경 : :.png'))),false);await page.locator('#mediaClose').click();
 await page.locator('#resourceOpen').click();await page.locator('#bibleQuery').fill('요 3 16 4 2');await page.waitForFunction(()=>document.getElementById('bibleParsed').textContent.includes('23절'));await page.locator('#bibleAdd').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('bibleAdd').disabled);assert.ok(await page.locator('.bible-card').count()>=23);await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/studio-bible.png'});await page.locator('.bible-card').first().dblclick();await page.locator('.bible-card textarea').fill('하나\n둘\n셋\n넷\n다섯\n여섯\n일곱');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.getElementById('bibleLong').textContent==='1');assert.equal(await page.locator('.bible-card').count(),23);await page.locator('[data-bible-filter=long]').click();await page.waitForFunction(()=>document.querySelectorAll('.bible-card').length===1);await page.locator('[data-bible-filter=all]').click();await page.waitForFunction(()=>document.querySelectorAll('.bible-card').length===23);await page.locator('#bibleAdd').click();assert.ok(await page.locator('.slide-card').count()>=26);assert.equal(await page.evaluate(()=>PP6.attr(YebaeonEditor.current(),'label')),'요한복음 3:16 (NKRV)');assert.equal(await page.evaluate(()=>PP6.parseRTF(PP6.textNode(PP6.textElements(YebaeonEditor.current())[1]).textContent).text),'요한복음 3:16');
 await page.locator('#orderPane').focus();await page.keyboard.press('Home');await page.keyboard.press('Delete');await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,2);await page.keyboard.press('Control+z');await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,3);
 await page.screenshot({path:'artifacts/studio-main.png'});await page.locator('#cloudAccount').click();await page.locator('#activityOpen').click();await page.waitForFunction(()=>document.getElementById('activityList').children.length>0);assert.deepEqual(errors,[]);console.log('Studio browser flows passed: editing, save, undo, clipboard, reflow, IME, menu, Bible, order autosave and activity');
 }finally{await page.screenshot({path:'artifacts/studio-final.png'}).catch(()=>{});await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
