const {chromium}=require('playwright');
const {createServer}=require('node:http');
const {readFile,mkdir}=require('node:fs/promises');
const {resolve,extname,sep}=require('node:path');
const {createHash}=require('node:crypto');
const assert=require('node:assert/strict');
(async()=>{
 const root=resolve('web-editor');const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']}:undefined);const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const openResult=async locator=>{await locator.click({button:'right'});await page.getByRole('menuitem',{name:'열기 Enter',exact:true}).click();};
 const documentMenu=async name=>{await page.locator('#locationTitle').click();await page.getByRole('menuitem',{name,exact:true}).click();};
 const MEDIA_PATH='/Users/Shared/Renewed Vision Media/Images/배경 : %3A.png',mediaRows=[{path:MEDIA_PATH,sha256:'a'.repeat(64),size:68}],favorites=new Map(),favoritePuts=[],mediaListings=[],thumbnailPuts=[],thumbnails=new Set(),allocations=[],uploads=[];
 let documentQueries=0,maintenanceCalls=0,xml='',version=1,playlistVersion=1,order=[],contentReads=0,orderPatches=0,failOrderSave=false;
 const id='11111111-1111-4111-a111-111111111111',libraryID='22222222-2222-4222-a222-222222222222';
 let catalogEnabled=false,policyRevision=0,policyCalls=0,searchEnabled=true,historyEnabled=true,category=null,archiveQuery=null;
 const pendingDoc={id:'33333333-3333-4333-a333-333333333333',name:'아직 안 올라온 찬양.pro6',path:'아직 안 올라온 찬양.pro6',available:false,version:null,slideCount:3};
 const doc=()=>({id,policyRevision,searchEnabled,historyEnabled,category,categoryManaged:!!category,path:'시험 문서.pro6',name:'시험 문서.pro6',version,updatedBy:'시험',updatedAt:'2026-10-02T00:00:00Z',lastDateUsed:'2026-10-01T00:00:00Z',useCount:1,sha256:createHash('sha256').update(xml).digest('hex')});
 const nodeHash=()=>createHash('sha256').update(JSON.stringify(order)).digest('hex');
 const library=()=>({id:libraryID,path:'기본.pro6pl',version:playlistVersion,updatedBy:'시험',updatedAt:'2026-10-02T00:00:00Z',playlists:[{id:'A',name:'금요기도회',itemCount:order.length}]});
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url()),path=u.pathname,method=route.request().method();let data={};
 if(path==='/api/sync-observations')data={items:{['document/'+id+'/']:{state:'pending',observedAt:'2026-10-02T00:00:00Z'},['playlist/'+libraryID+'/A']:{state:'synced',observedAt:'2026-10-02T00:00:00Z'}}};
 else if(path==='/api/search-index'){maintenanceCalls++;data={next:null,processed:0};}
 else if(path==='/api/session')data={ready:true,authenticated:true,name:'시험'};
 else if(path==='/api/documents'){documentQueries++;archiveQuery=u.searchParams.get('includeArchived');const q=u.searchParams.get('q')||'';data={documents:xml?(catalogEnabled?(q==='본문만검색'?[{...doc(),matchedBy:'content'}]:[doc(),pendingDoc].filter(d=>q==='문서전체시험'||d.name.includes(q))):[doc()]):[],next:null};}
 else if(path==='/api/documents/'+id+'/policy'){const body=JSON.parse(route.request().postData());assert.equal(body.policyRevision,policyRevision);searchEnabled=body.searchEnabled;historyEnabled=body.historyEnabled;policyRevision++;policyCalls++;data={document:doc()};}
 else if(path==='/api/documents/'+id+'/content'){contentReads++;await route.fulfill({body:xml,contentType:'application/xml'});return;}
 else if(path==='/api/documents/'+id){if(method==='PUT'){xml=route.request().postData();version++;}data={document:doc()};}
 else if(path==='/api/playlists')data={libraries:xml?[library()]:[],next:null};
 else if(path.endsWith('/plan'))data={library:library(),playlist:{id:'A',name:'금요기도회',editable:true,version:playlistVersion,sha256:nodeHash()},ready:true,items:order.map((x,i)=>x.documentId===pendingDoc.id?{kind:'document',id:x.id||'cue'+i,name:pendingDoc.name,document:null,indexedDocument:pendingDoc,issue:'missing'}:{kind:'document',id:x.id||'cue'+i,name:doc().name,document:doc(),sharedWith:['수요예배','금요예배']})};
 else if(path==='/api/playlists/'+libraryID&&method==='PATCH'){orderPatches++;if(failOrderSave){await route.fulfill({status:409,json:{message:'서버 순서가 먼저 바뀌었습니다.'}});return;}const body=JSON.parse(route.request().postData());assert.equal(body.baseNodeHash,nodeHash());order=body.items;playlistVersion++;data={library:library(),playlist:{sha256:nodeHash()}};}
 else if(path==='/api/activity')data={items:[{kind:'document',...doc(),author:'시험',createdAt:doc().updatedAt}],next:null};
 else if(path.endsWith('/versions'))data={versions:[],next:null};
 else if(path==='/api/sync/devices')data={head:0,devices:[]};else if(path==='/api/editing')data={others:[]};else if(path==='/api/categories')data={categories:['가사찬양','악보찬양','예배순서','특별순서','옛날자료'].map(name=>({name,searchEnabled:true,historyEnabled:true}))};
 else if(path==='/api/favorites'){if(method==='PUT'){const b=JSON.parse(route.request().postData());favoritePuts.push(b);if(b.on)favorites.set(b.kind+':'+b.key,{kind:b.kind,key:b.key,label:b.label,addedBy:'시험',addedAt:'2026-10-05T00:00:00Z'});else favorites.delete(b.kind+':'+b.key);data=b;}else data={items:[...favorites.values()]};}
 else if(path==='/api/media/paths'&&method==='POST'){const body=JSON.parse(route.request().postData());allocations.push(body);data={paths:body.items.map(i=>({path:'/Users/Shared/Renewed Vision Media/YebaeOn/'+body.name+'-1.'+(body.ext||'png'),sha256:i.sha256}))};}
 else if(path==='/api/media/paths'){const folder=u.searchParams.get('folder');if(folder){mediaListings.push(folder+'/'+(u.searchParams.get('q')||''));data={paths:folder==='Images'?mediaRows:[],next:null};}else{const asked=u.searchParams.getAll('path');data={paths:mediaRows.filter(r=>asked.includes(r.path)).map(r=>({...r,state:'active'}))};}}
 else if(/^\/api\/media\/[a-f0-9]{64}\/thumbnail$/.test(path)){const sha=path.split('/')[3];if(method==='PUT'){thumbnailPuts.push(sha);thumbnails.add(sha);data={thumbnail:sha};}else if(thumbnails.has(sha)){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAAEElEQVR4nGNQSDgARww4OQAdNg8BkwvKGAAAAABJRU5ErkJggg==','base64')});return;}else{await route.fulfill({status:404,json:{error:'thumbnail_not_found',message:'없음'}});return;}}
 else if(/^\/api\/media\/[a-f0-9]{64}\/content$/.test(path)&&method==='PUT'){uploads.push(route.request().headers()['content-type']);data={asset:{}};}
 else if(/^\/api\/media\/[a-f0-9]{64}\/content$/.test(path)){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAAEElEQVR4nGNQSDgARww4OQAdNg8BkwvKGAAAAABJRU5ErkJggg==','base64'),headers:{'Cache-Control':'private, max-age=31536000, immutable'}});return;}
 else throw Error('Unhandled '+path);
 await route.fulfill({json:data});});
 let templateXML='',templateReads=0;const template={id:'104',name:'성경',label:'본문',width:1920,height:1080,file:'template-aaaaaaaaaaaaaaaaaaaaaaaa.json'};
 const books=Array.from({length:66},(_,i)=>({name:i===42?'요한복음':'책'+i,chapters:[{number:3,verses:Array.from({length:36},(_,i)=>({number:i+1,text:'하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니 믿는 자마다 영생을 얻게 하려 하심이라.'}))},{number:4,verses:[{number:1,text:'첫 번째 절입니다.'},{number:2,text:'두 번째 절입니다.'}]}]}));
 await page.route('**/resources/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith(template.file)){templateReads++;await route.fulfill({json:{xml:templateXML}});return;}if(path.endsWith('.png')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAAEElEQVR4nGNQSDgARww4OQAdNg8BkwvKGAAAAABJRU5ErkJggg==','base64')});return;}await route.fulfill({json:path.endsWith('catalog.json')?{fonts:[],media:[]}:path.endsWith('templates.json')?(template?[template]:[]):{books}});});
 await mkdir('artifacts',{recursive:true});
 try{
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.YebaeonCloud&&window.YebaeonResources);
 await page.addScriptTag({path:'web-editor/sample-demo.js'});
 xml=await page.evaluate(()=>{const m=PP6.parse(PP6_SAMPLE.xml,'test.pro6');for(const slide of PP6.slides(m)){const box=PP6.textElements(slide)[0],ref=box.cloneNode(true);PP6.refreshIDs(ref);PP6.setText(ref,'요한복음 3:16');ref.querySelector('RVRect3D').textContent='{120 900 0 1680 100}';box.parentNode.append(ref);}return PP6.serialize(m);});
 assert.equal(documentQueries,0,'initial studio must not query the document library');assert.match(await page.locator('#libraryList').textContent(),/검색어를 입력해주세요/);
 await page.locator('#libraryQuery').fill('시험');await page.waitForTimeout(400);assert.equal(documentQueries,0,'typing must not query D1');assert.equal(maintenanceCalls,0);
 order=[{id:'cue0'},{id:'cue1'}];await page.locator('#libraryQuery').press('Enter');await openResult(page.locator('#libraryList .document-item'));await page.waitForFunction(()=>YebaeonEditor.ready());await page.evaluate(()=>YebaeonPlaylists.show());
 assert.equal(await page.locator('#libraryList .sync-pending').count(),1);assert.equal(await page.locator('#playlistsList .sync-synced').count(),1);assert.match(await page.locator('#libraryList .sync-light').getAttribute('title'),/마지막 Mac 적용 보고/);
 await page.evaluate(async()=>{const api=YebaeonCloud.api;YebaeonCloud.api=(path,...args)=>path.startsWith('/sync-observations')?Promise.reject(new Error('fixture offline')):api(path,...args);await YebaeonSyncLights.refresh();YebaeonCloud.api=api;});assert.equal(await page.locator('#playlistsList .sync-synced').count(),0);assert.match(await page.locator('#playlistsList .sync-light').getAttribute('title'),/조회 실패/);await page.evaluate(()=>YebaeonSyncLights.refresh());
 await documentMenu('검색·이력 설정');await page.locator('#policySong').click();assert.equal(await page.locator('#policySearch').isChecked(),true);assert.equal(await page.locator('#policyHistory').isChecked(),false);await page.locator('#policySave').click();await page.locator('#documentPolicyDialog').waitFor({state:'hidden'});assert.equal(policyCalls,1);assert.equal(historyEnabled,false);
 await documentMenu('검색·이력 설정');await page.locator('#policyWeekly').click();assert.equal(await page.locator('#policySearch').isChecked(),true);assert.equal(await page.locator('#policyHistory').isChecked(),true);await page.locator('#policySave').click();await page.locator('#documentPolicyDialog').waitFor({state:'hidden'});assert.equal(policyCalls,2);
 // Reuse the initial search/policy flow as a focused check for this change.
 assert.equal(archiveQuery,null);await page.locator('#libraryArchived').check();await page.waitForFunction(()=>document.getElementById('libraryMessage').textContent==='');assert.equal(archiveQuery,'1');await page.locator('#libraryArchived').uncheck();await page.waitForFunction(()=>document.getElementById('libraryMessage').textContent==='');assert.equal(archiveQuery,null);
 category='예배순서';await documentMenu('검색·이력 설정');await page.locator('#documentPolicyDialog').waitFor({state:'visible'});assert.equal(await page.locator('#policySearch').isChecked(),true);assert.equal(await page.locator('#policyHistory').isChecked(),true);for(const control of ['policySearch','policyHistory','policySong','policyWeekly','policySave'])assert.equal(await page.locator('#'+control).isDisabled(),true);assert.match(await page.locator('#policyMessage').textContent(),/예배순서 카테고리/);await page.screenshot({path:'artifacts/studio-category-policy.png'});await page.locator('#policyClose').click();assert.equal(policyCalls,2);
 category=null;await documentMenu('검색·이력 설정');await page.locator('#documentPolicyDialog').waitFor({state:'visible'});assert.equal(await page.locator('#policySave').isEnabled(),true);await page.locator('#policyClose').click();
 if(process.env.STUDIO_CHECK_SCOPE==='category-policy'){assert.deepEqual(errors,[]);console.log('Category policy UI passed: empty/typing requests, explicit archived search, managed policy, legacy presets');return;}
 templateXML=await page.evaluate(xml=>new XMLSerializer().serializeToString(PP6.slides(PP6.parse(xml,'template'))[0]),xml);assert.equal(templateReads,0);assert.equal(await page.locator('#playlistItems').getByText(/함께 사용:/).count(),0);
 assert.equal(await page.locator('.slide-card').count(),3);
 await page.locator('#slideColumns').evaluate(e=>{e.value='6';e.dispatchEvent(new Event('input'));});assert.equal(await page.locator('#slideColumnsValue').textContent(),'6개');assert.equal(await page.evaluate(()=>getComputedStyle(document.getElementById('slides')).gridTemplateColumns.split(' ').length),6);
 await page.locator('#slideColumns').evaluate(e=>{e.value='4';e.dispatchEvent(new Event('input'));});
 const firstReads=contentReads;
 await page.evaluate(()=>YebaeonEditor.open(PP6_SAMPLE.xml,'other.pro6',true,'other'));
 await page.evaluate(id=>YebaeonCloud.openDocument(id),id);assert.equal(contentReads,firstReads,'unchanged original should not download again');
 version++;await page.evaluate(id=>YebaeonCloud.openDocument(id),id);assert.equal(contentReads,firstReads+1,'new server version must download');
 const previewCheck=await page.evaluate(async()=>{const model=YebaeonEditor.model(),slide=YebaeonEditor.current(),canvas=()=>{const c=document.createElement('canvas');c.width=400;c.height=225;return c;};await PP6Fonts.ensure(slide);PP6Render.clear();let calls=0;const ensure=PP6Fonts.ensure;PP6Fonts.ensure=(...args)=>{calls++;return ensure(...args);};try{const a=canvas();await PP6Render.draw(a,model,slide,new Map());const first=calls,b=canvas();await PP6Render.draw(b,model,slide,new Map());const reused=calls===first&&a.toDataURL()===b.toDataURL();const changed=slide.cloneNode(true);PP6.setText(PP6.textElements(changed)[0],'새로운 본문');await PP6Render.draw(canvas(),model,changed,new Map());const edited=calls>first,after=calls;window.dispatchEvent(new Event('pp6fontschange'));await PP6Render.draw(canvas(),model,slide,new Map());return {reused,edited,fontInvalidated:calls>after};}finally{PP6Fonts.ensure=ensure;}});
 assert.deepEqual(previewCheck,{reused:true,edited:true,fontInvalidated:true});
 await page.locator('.slide-card').first().click();await page.locator('.slide-card').nth(2).click({modifiers:['Shift']});assert.equal(await page.locator('.slide-card.selected').count(),3);await page.locator('.slide-card').nth(1).click({modifiers:['Control']});assert.equal(await page.locator('.slide-card.selected').count(),2);
 const patchesBefore=orderPatches;await page.locator('#libraryList .document-item').dragTo(page.locator('#playlistItems .order-item').first());await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent.includes('초안 보존됨'));await page.waitForTimeout(350);assert.equal(orderPatches,patchesBefore,'order changes must stay local until explicit save');assert.equal(order.length,2);assert.match(await page.locator('#playlistState').textContent(),/저장 안 됨/);
 const localOrder=await page.evaluate(async()=>{const records=await YebaeonDrafts.all();return records.find(r=>r.kind==='playlist');});assert.equal(localOrder.items.length,3);await page.reload();await page.addScriptTag({path:'web-editor/sample-demo.js'});await page.waitForFunction(()=>window.YebaeonPlaylists?.state().dirty&&document.querySelectorAll('#playlistItems .order-item').length===3);assert.equal(orderPatches,patchesBefore,'reload recovery must not write the server');await page.locator('#libraryQuery').fill('시험');await page.locator('#libraryQuery').press('Enter');await openResult(page.locator('#libraryList .document-item'));await page.waitForFunction(()=>YebaeonEditor.ready());
 await page.evaluate(()=>YebaeonPlaylists.openNode('22222222-2222-4222-a222-222222222222','A'));assert.equal(await page.locator('#playlistItems .order-item').count(),3,'opening the playlist must offer draft recovery');assert.equal(orderPatches,patchesBefore);
 failOrderSave=true;await page.locator('#cloudSave').click();await page.waitForFunction(()=>YebaeonPlaylists.state().blocked&&!YebaeonPlaylists.state().busy);assert.equal(await page.evaluate(()=>YebaeonPlaylists.state().dirty),true);assert.equal(await page.locator('#playlistItems .order-item').count(),3);assert.ok((await page.evaluate(()=>YebaeonDrafts.all())).some(r=>r.kind==='playlist'));
 failOrderSave=false;await page.locator('#cloudSave').click();await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,3);
 await page.locator('.slide-card').first().click();await page.keyboard.press('Enter');await page.locator('#quickInputs textarea').first().waitFor();await page.evaluate(()=>window.fixtureCanvas=document.querySelector('.slide-card canvas'));await page.locator('#quickInputs textarea').first().fill('빠른 편집 시험');await page.waitForFunction(()=>document.getElementById('quickCanvas').width>400);assert.equal(await page.locator('#quickCanvas').isVisible(),true);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.fixtureCanvas===document.querySelector('.slide-card canvas')),true);await page.keyboard.press('Escape');await page.locator('#quickDialog').waitFor({state:'hidden'});
 await page.locator('#slidePane').focus();await page.keyboard.press('Control+z');assert.notEqual(await page.evaluate(()=>PP6.parseRTF(PP6.textNode(PP6.textElements(YebaeonEditor.current())[0]).textContent).text),'빠른 편집 시험');await page.keyboard.press('Control+Shift+z');
 await page.keyboard.press('Control+s');await page.waitForFunction(()=>!YebaeonEditor.state().dirty);assert.equal(version,3);await page.waitForFunction(()=>!document.querySelector('#playlistItems .unsaved'));
 await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');assert.equal(await page.locator('.slide-card').count(),4);await page.keyboard.press('Delete');assert.equal(await page.locator('.slide-card').count(),3);
 await page.keyboard.down('AltLeft');await page.keyboard.press('KeyR');await page.keyboard.up('AltLeft');await page.locator('#reflowRows textarea').first().fill('앞부분 뒷부분');await page.locator('#reflowRows textarea').first().evaluate(e=>e.setSelectionRange(3,3));await page.keyboard.down('AltLeft');await page.keyboard.press('Enter');await page.keyboard.up('AltLeft');assert.equal(await page.locator('#reflowRows textarea').count(),4);await page.keyboard.press('Backspace');assert.equal(await page.locator('#reflowRows textarea').count(),3);
 await page.locator('#reflowClose').click();await page.locator('.slide-card').first().click({button:'right'});const chosen=await page.evaluate(()=>YebaeonEditor.selected());await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>YebaeonEditor.selected()),chosen);await page.keyboard.press('Escape');
 await page.locator('#slidePane').focus();await page.evaluate(()=>document.getElementById('slidePane').dispatchEvent(new KeyboardEvent('keydown',{code:'Delete',isComposing:true,bubbles:true})));assert.equal(await page.locator('.slide-card').count(),3);
 // Old minimal Studio documents are repaired to the PP6 shape on save; a PP6-made document is sent untouched.
 const repair=await page.evaluate(pp6=>{const old='<RVPresentationDocument UUID="AAAA" versionNumber="600" width="1920" height="1080" category="미결" lastDateUsed="" usedCount="0"><array rvXMLIvarName="groups"><RVSlideGrouping UUID="BBBB" name="기본"><array rvXMLIvarName="slides"><RVDisplaySlide UUID="CCCC" label="" enabled="true" drawingBackgroundColor="true" backgroundColor="0 0 0 1"><array rvXMLIvarName="displayElements"><RVTextElement UUID="DDDD" opacity="1" verticalAlignment="0" drawingFill="false" drawingShadow="false"><RVRect3D rvXMLIvarName="position">{80 90 0 1760 900}</RVRect3D><NSString rvXMLIvarName="RTFData">e30=</NSString></RVTextElement></array><array rvXMLIvarName="cues"/></RVDisplaySlide></array></RVSlideGrouping></array></RVPresentationDocument>';
  const fixed=PP6.repairXML(old),d=new DOMParser().parseFromString(fixed,'application/xml').documentElement,text=d.querySelector('RVTextElement');
  return {timeline:!!d.querySelector(':scope>RVTimeline[rvXMLIvarName=timeline]'),arrangements:!!d.querySelector(':scope>array[rvXMLIvarName=arrangements]'),build:d.getAttribute('buildNumber'),rootId:[d.getAttribute('uuid'),d.hasAttribute('UUID')],groupId:d.querySelector('RVSlideGrouping').getAttribute('uuid'),slideId:d.querySelector('RVDisplaySlide').getAttribute('UUID'),textKept:[text.getAttribute('opacity'),text.querySelector('RVRect3D').textContent,text.querySelector('NSString').textContent],textAdded:[!!text.querySelector(':scope>shadow'),!!text.querySelector(':scope>dictionary[rvXMLIvarName=stroke]'),text.getAttribute('displayName'),text.getAttribute('source')],again:PP6.repairXML(fixed)===fixed,pp6Untouched:PP6.repairXML(pp6)===pp6};},'<RVPresentationDocument CCLIArtistCredits="" CCLIAuthor="" CCLICopyrightYear="" CCLIDisplay="false" CCLIPublisher="" CCLISongNumber="" CCLISongTitle="" backgroundColor="" buildNumber="100991749" category="악보찬양" chordChartPath="" docType="0" drawingBackgroundColor="false" height="1080" lastDateUsed="" notes="" os="2" resourcesDirectory="" selectedArrangementID="" usedCount="0" uuid="4771FEB7-4207-403C-8AD9-AC6C5AB6DB44" versionNumber="600" width="1920"><RVTimeline duration="0.000000" loop="false" playBackRate="0.000000" rvXMLIvarName="timeline" selectedMediaTrackIndex="0" timeOffset="0.000000"><array rvXMLIvarName="timeCues"></array><array rvXMLIvarName="mediaTracks"></array></RVTimeline><array rvXMLIvarName="groups"><RVSlideGrouping color="0.2637968361377716 0.2637968361377716 0.2637968361377716 1" name="그룹" uuid="A8842790-80BB-4F37-ADC0-9CB09F143F6A"><array rvXMLIvarName="slides"><RVDisplaySlide UUID="BA4ADB74-4B6D-47CA-87C4-49672E5FC842" backgroundColor="0 0 0 1" chordChartPath="" drawingBackgroundColor="false" enabled="true" highlightColor="0 0 0 0" hotKey="" label="x" notes="" socialItemCount="0"><array rvXMLIvarName="cues"></array><array rvXMLIvarName="displayElements"></array></RVDisplaySlide></array></RVSlideGrouping></array><array rvXMLIvarName="arrangements"></array></RVPresentationDocument>');
 assert.deepEqual(repair,{timeline:true,arrangements:true,build:'100991749',rootId:['AAAA',false],groupId:'BBBB',slideId:'CCCC',textKept:['1','{80 90 0 1760 900}','e30='],textAdded:[true,true,'TextElement',''],again:true,pp6Untouched:true},'PP6 cannot open a text element without source=""');
 const fresh=await page.evaluate(()=>PP6.repairXML(YebaeonLibraryActions.blankDocument('미결')));assert.match(fresh,/^<RVPresentationDocument CCLIArtistCredits=""/);assert.equal(await page.evaluate(x=>PP6.repairXML(x)===x,fresh),true,'a new Studio document already has the PP6 shape');
 // Media drawer: shared favorites, backgrounds the open playlist uses, the rest from the server (ImportedImages never listed).
 await page.locator('#mediaOpen').click();const rest=page.locator('#mediaGrid .media-section').nth(2);await rest.locator('.media-pick').first().waitFor();
 const headings=await page.locator('#mediaGrid .media-section h3').allTextContents();assert.match(headings[0],/★ 즐겨찾기/);assert.match(headings[1],/배경으로 쓰는 그림/);assert.match(headings[2],/나머지 그림/);assert.deepEqual(mediaListings,['Images/']);for(let i=0;i<50&&!thumbnailPuts.length;i++)await new Promise(r=>setTimeout(r,100));await new Promise(r=>setTimeout(r,300));assert.deepEqual(thumbnailPuts,['a'.repeat(64)],'a missing preview is made once from the original and shared');
 const backgrounds=()=>page.evaluate(()=>PP6.slides(YebaeonEditor.model()).map(s=>{const cue=PP6.ivar(s,'RVMediaCue','backgroundMediaCue');return cue?PP6.attr(PP6.mediaElements(cue)[0],'source'):'';}));
 await rest.locator('.media-pick').first().dragTo(page.locator('.slide-card').first());assert.deepEqual((await backgrounds()).map(Boolean),[true,false,false],'one slide without a selection group');assert.equal((await backgrounds())[0],'file://'+MEDIA_PATH.split('/').map(encodeURIComponent).join('/'),'documents get the PP6 file:// form');
 assert.equal(await page.evaluate(async p=>!!(await YebaeonResources.media(p)),MEDIA_PATH),true,'server bytes render');assert.equal(await page.evaluate(async()=>!!(await YebaeonResources.media('/Users/procg/Media/배경 : :.png'))),false);
 await page.keyboard.press('Control+z');await page.locator('.slide-card').nth(1).click();await page.locator('.slide-card').nth(2).click({modifiers:['Shift']});await rest.locator('.media-pick').first().dragTo(page.locator('.slide-card').nth(2));assert.deepEqual((await backgrounds()).map(Boolean),[false,true,true],'dropping on a chosen slide covers all chosen slides');
 await page.keyboard.press('Control+z');await page.locator('.slide-card').first().click();const tileBox=await rest.locator('.media-pick').first().boundingBox();await page.mouse.move(tileBox.x+20,tileBox.y+20);await page.mouse.down();const card=await page.locator('.slide-card').first().boundingBox();await page.mouse.move(card.x+30,card.y+30,{steps:5});await page.locator('#mediaDropAll').waitFor();const zone=await page.locator('#mediaDropAll').boundingBox();await page.mouse.move(zone.x+20,zone.y+10,{steps:5});await page.mouse.up();
 assert.deepEqual((await backgrounds()).map(Boolean),[true,true,true],'the top zone covers every slide');assert.equal(await page.locator('#mediaDropAll').isVisible(),false);await page.keyboard.press('Control+z');assert.deepEqual((await backgrounds()).map(Boolean),[false,false,false],'one undo removes the whole batch');
 await rest.locator('.media-star').first().click();await page.locator('#mediaGrid .media-section').first().locator('.media-pick').first().waitFor();assert.deepEqual(favoritePuts.map(x=>[x.kind,x.key,x.on]),[['media','a'.repeat(64),true]]);
 await rest.locator('.media-more').click();await page.locator('#mediaAllDialog[open] .media-all-grid .media-pick').first().waitFor();assert.equal(await page.locator('#mediaAllDialog .media-star.on').count(),1);await page.screenshot({path:'artifacts/studio-media-all.png'});await page.locator('#mediaAllDialog [data-close]').click();
 // Background fit and crop from the slide menu: the original stays, the cut part becomes a new image.
 await page.locator('.slide-card').first().click();await rest.locator('.media-pick').first().click();assert.equal(await page.evaluate(()=>PP6.attr(PP6.mediaElements(PP6.ivar(YebaeonEditor.current(),'RVMediaCue','backgroundMediaCue'))[0],'scaleBehavior')),'1','new backgrounds fill');
 await page.locator('.slide-card').first().click({button:'right'});await page.getByRole('menuitem',{name:'맞추기 (그림 전체, 빈 곳 생김)'}).click();assert.equal(await page.evaluate(()=>PP6.attr(PP6.mediaElements(PP6.ivar(YebaeonEditor.current(),'RVMediaCue','backgroundMediaCue'))[0],'scaleBehavior')),'0');
 const pp6Shape=await page.evaluate(()=>{const cue=PP6.ivar(YebaeonEditor.current(),'RVMediaCue','backgroundMediaCue'),img=PP6.mediaElements(cue)[0];return {behavior:cue.getAttribute('behavior'),name:cue.getAttribute('displayName'),position:PP6.ivar(img,'RVRect3D','position')?.textContent,shadow:!!PP6.ivar(img,'shadow','shadow'),stroke:!!PP6.ivar(img,'dictionary','stroke'),format:img.getAttribute('format')};});
 assert.deepEqual(pp6Shape,{behavior:'2',name:'배경 : %3A',position:'{0 0 0 0 0}',shadow:true,stroke:true,format:'PNG 이미지'},'backgrounds are written the way PP6 writes them');
 await page.locator('.slide-card').first().click({button:'right'});await page.getByRole('menuitem',{name:'늘이기 (비율 무시)'}).click();assert.equal(await page.evaluate(()=>PP6.attr(PP6.mediaElements(PP6.ivar(YebaeonEditor.current(),'RVMediaCue','backgroundMediaCue'))[0],'scaleBehavior')),'3','PP6 stretch is 3');
 await page.locator('.slide-card').first().click({button:'right'});await page.getByRole('menuitem',{name:'맞추기 (그림 전체, 빈 곳 생김)'}).click();
 await page.locator('.slide-card').first().click({button:'right'});assert.ok(await page.getByRole('menuitem',{name:'맞추기 (그림 전체, 빈 곳 생김) ✓'}).isVisible(),'the current fit is marked');await page.getByRole('menuitem',{name:'배경 자르기…'}).click();await page.locator('#mediaCropDialog[open] canvas').waitFor();
 await page.locator('#mediaCropDialog input[type=range]').fill('50');await page.screenshot({path:'artifacts/studio-background-crop.png'});await page.locator('#mediaCropDialog [data-apply]').click();await page.waitForFunction(()=>!document.querySelector('#mediaCropDialog').open);
 assert.deepEqual(allocations.at(-1).ext,'png');assert.match(allocations.at(-1).name,/ 자름$/);assert.equal(uploads.at(-1),'image/png');
 assert.match(await page.evaluate(()=>PP6.attr(PP6.mediaElements(PP6.ivar(YebaeonEditor.current(),'RVMediaCue','backgroundMediaCue'))[0],'source')),/YebaeOn\/.*%20%EC%9E%90%EB%A6%84-1\.png$/,'the cut image replaces the background; the original path is untouched');
 await page.locator('.slide-card').first().click({button:'right'});await page.getByRole('menuitem',{name:'배경 빼기'}).click();assert.equal(await page.evaluate(()=>!!PP6.ivar(YebaeonEditor.current(),'RVMediaCue','backgroundMediaCue')),false);
 await page.screenshot({path:'artifacts/studio-media.png'});await page.locator('#mediaClose').click();
 await page.locator('#resourceOpen').click();await page.locator('#bibleTemplate').selectOption(template.id);await page.locator('#bibleQuery').fill('요 3 16 4 2');await page.waitForFunction(()=>document.getElementById('bibleParsed').textContent.includes('23절'));await page.locator('#bibleAdd').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('bibleAdd').disabled);assert.ok(await page.locator('.bible-card').count()>=23);assert.equal(templateReads,1);await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/studio-bible.png'});await page.locator('.bible-card').first().dblclick();await page.locator('#bibleQuickText').fill('하나\n둘\n셋\n넷\n다섯\n여섯\n일곱');assert.equal(await page.locator('#bibleQuickCanvas').isVisible(),true);await page.screenshot({path:'artifacts/studio-bible-quick.png'});await page.keyboard.press('Escape');await page.waitForFunction(()=>document.getElementById('bibleLong').textContent==='1');assert.equal(await page.locator('.bible-card').count(),23);await page.locator('[data-bible-filter=long]').click();await page.waitForFunction(()=>document.querySelectorAll('.bible-card').length===1);await page.locator('[data-bible-filter=all]').click();await page.waitForFunction(()=>document.querySelectorAll('.bible-card').length===23);await page.locator('#bibleViewReflow').click();await page.locator('.bible-card textarea').first().fill('리플로우 본문\n미리보기 유지');assert.equal(await page.locator('.bible-card canvas').first().isVisible(),true);await page.screenshot({path:'artifacts/studio-bible-reflow.png'});await page.locator('#bibleViewSlides').click();await page.locator('#bibleAdd').click();assert.ok(await page.locator('.slide-card').count()>=26);assert.equal(await page.evaluate(()=>PP6.attr(YebaeonEditor.current(),'label')),'요한복음 3:16 (NKRV)');assert.equal(await page.evaluate(()=>PP6.parseRTF(PP6.textNode(PP6.textElements(YebaeonEditor.current())[1]).textContent).text),'요한복음 3:16');
 await page.locator('#orderPane').focus();await page.keyboard.press('Home');await page.keyboard.press('Delete');await page.locator('#cloudSave').click();await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,2);await page.waitForFunction(()=>YebaeonPlaylists.historyState().undo>0);await page.keyboard.press('Control+z');await page.locator('#cloudSave').click();await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,3);
 await page.screenshot({path:'artifacts/studio-main.png'});await page.locator('#cloudAccount').focus();await page.keyboard.press('Enter');await page.locator('#activityOpen').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('activityList').children.length>0);assert.deepEqual(errors,[]);
 await page.locator('#activityDialog').evaluate(e=>e.close());
 await page.evaluate(()=>{const model=PP6.parse(PP6_SAMPLE.xml,'large.pro6'),first=PP6.slides(model)[0],container=first.parentNode;PP6.slides(model).forEach(s=>s.remove());for(let i=0;i<200;i++){const copy=first.cloneNode(true);PP6.refreshIDs(copy);container.append(copy);}window.fixtureDraws=0;const draw=PP6Render.draw;PP6Render.draw=(...args)=>{window.fixtureDraws++;return draw(...args);};YebaeonEditor.open(PP6.serialize(model),'large.pro6',true,'large');YebaeonEditor.setView('slides');});
 await page.waitForTimeout(300);const initialDraws=await page.evaluate(()=>window.fixtureDraws);assert.ok(initialDraws>0&&initialDraws<100,'offscreen slides should not all render');
 await page.locator('.slide-card').last().scrollIntoViewIfNeeded();await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>window.fixtureDraws)>initialDraws,'scrolling should render newly visible slides');
 await page.locator('.slide-card').first().scrollIntoViewIfNeeded();await page.locator('.slide-card').first().click();
 await page.locator('#templateOpen').click();await page.locator('#templateDialog[open]').waitFor();assert.match(await page.locator('#templateScopeLabel').textContent(),/고른 1장에 적용/);const sectionTitles=await page.locator('#templateList .template-section>summary').allTextContents();assert.deepEqual(sectionTitles.map(t=>t.replace(/ \(\d+\)$/,'').replace(/\(.*\)/,'')),['이 문서에서 쓰는 서식','이 재생목록에서 쓰는 서식','★ 즐겨찾기','교회 서식','ProPresenter 기본 서식']);
 await page.locator('#templateQuery').fill('104');await page.waitForFunction(()=>document.querySelector('#templateList summary')?.textContent==='검색 결과 (1)');await page.locator('#templateList .template-star').click();await page.waitForFunction(()=>YebaeonFavorites.has('template','104'));assert.deepEqual(favoritePuts.at(-1),{kind:'template',key:'104',label:'성경 · 본문 · #104',on:true});
 await page.locator('#templateList .template-pick').first().click();await page.waitForFunction(()=>!document.querySelector('#templateDialog').open&&YebaeonResources.templateLabel()==='성경 · 본문 · #104');
 await page.locator('#templateOpen').click();await page.waitForFunction(()=>[...document.querySelectorAll('#templateList .template-section>summary')].map(s=>s.textContent).join('|').includes('이 문서에서 쓰는 서식 (1)'));assert.match(await page.locator('#templateList .template-section').first().textContent(),/이 문서 1장/);assert.match(await page.locator('#templateList .template-section').nth(2).textContent(),/성경 · 본문/);await page.screenshot({path:'artifacts/studio-template-dialog.png'});await page.locator('#templateClose').click();
 assert.equal(await page.locator('#bibleTemplate').inputValue(),'104');
 const applied=await page.evaluate(()=>YebaeonEditor.document().xml);await page.evaluate(()=>YebaeonEditor.open(PP6_SAMPLE.xml,'other.pro6',true,'other'));await page.evaluate(xml=>YebaeonEditor.open(xml,'applied.pro6',true,'applied'),applied);
 await page.waitForFunction(()=>YebaeonResources.templateLabel()==='성경 · 본문 · #104');
 await page.screenshot({path:'artifacts/studio-template-name.png'});
 await page.evaluate(()=>{const slide=PP6.slides(YebaeonEditor.model())[1];PP6.textElements(slide)[0].setAttribute('rotation','17');YebaeonEditor.redraw();});
 await page.locator('.slide-card').nth(1).click({modifiers:['Shift']});await page.waitForFunction(()=>YebaeonResources.templateLabel()==='여러 서식 선택됨');
 const {templateFormatHash}=await import('../../scripts/build.mjs');
 const browserFormat=await page.evaluate(async xml=>{const slide=new DOMParser().parseFromString(xml,'application/xml').documentElement;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(PP6.templateFormat(slide)))),n=>n.toString(16).padStart(2,'0')).join('');},templateXML);
 assert.equal(browserFormat,templateFormatHash(templateXML),'build and browser must agree on the template format');
 template.format=templateFormatHash(templateXML);xml='<?xml version="1.0"?><RVPresentationDocument width="1920" height="1080"><array rvXMLIvarName="groups"><RVSlideGrouping name="본문"><array rvXMLIvarName="slides">'+templateXML+'</array></RVSlideGrouping></array></RVPresentationDocument>';version++;
 await page.reload();await page.locator('#libraryQuery').fill('시험');await page.locator('#libraryQuery').press('Enter');await openResult(page.locator('#libraryList .document-item'));await page.waitForFunction(()=>YebaeonResources.templateLabel()==='성경 · 본문 · #104');
 catalogEnabled=true;await page.locator('#libraryQuery').fill('문서전체시험');await page.locator('#libraryQuery').press('Enter');
 await page.evaluate(()=>{PP6.setText(PP6.textElements(YebaeonEditor.current())[0],'전환 전에 편집한 초안');YebaeonEditor.markDirty();});
 const pendingRow=page.locator('#libraryList .document-item').filter({hasText:'아직 안 올라온 찬양'});await openResult(pendingRow);await page.waitForFunction(()=>!YebaeonEditor.ready());
 assert.equal(await page.evaluate(()=>YebaeonEditor.ready()),false);assert.equal(await page.locator('#cloudSave').isDisabled(),false,'the draft left on the previous document still waits for the shared save');assert.equal(await page.locator('#templateOpen').isDisabled(),true);assert.match(await page.locator('#emptyDocument').textContent(),/원본 미업로드/);assert.equal(await page.locator('.slide-card').count(),0);
 const beforeOrder=order.length;await pendingRow.dragTo(page.locator('#playlistItems .order-item').first(),{targetPosition:{x:24,y:2}});await page.locator('#cloudSave').click();await page.waitForFunction(()=>document.getElementById('playlistsMessage').textContent==='순서 저장됨');assert.equal(order.length,beforeOrder+1);assert.equal(order[0].documentId,pendingDoc.id);
 await page.locator('#playlistItems .order-item').first().click();assert.match(await page.locator('#emptyDocument').textContent(),/텍스트 편집과 미리보기를 사용할 수 없습니다/);
 await page.screenshot({path:'artifacts/studio-indexed-document.png'});
 await openResult(page.locator('#libraryList .document-item').filter({hasText:'시험 문서'}));await page.waitForFunction(()=>YebaeonEditor.ready());assert.equal(await page.evaluate(()=>YebaeonEditor.state().dirty),false);assert.equal(await page.evaluate(()=>PP6.parseRTF(PP6.textNode(PP6.textElements(YebaeonEditor.current())[0]).textContent).text),'전환 전에 편집한 초안');
 await page.locator('#libraryQuery').fill('본문만검색');await page.locator('#libraryQuery').press('Enter');await page.waitForFunction(()=>document.querySelectorAll('#libraryList .document-item').length===1);assert.equal(await page.locator('#libraryList small').textContent(),'본문 일치');
 assert.deepEqual(errors,[]);
 await page.addScriptTag({path:'web-editor/sample-demo.js'});
 await page.evaluate(()=>{YebaeonEditor.open(PP6_SAMPLE.xml,'배치 편집 시험.pro6',true,'layout-test');YebaeonEditor.setView('editor');});
 await page.locator('#layoutStagePane').waitFor({state:'visible'});await page.waitForFunction(()=>window.YebaeonLayout.active());
 const initialBoxes=await page.evaluate(()=>PP6.textElements(YebaeonEditor.current()).length);
 await page.locator('#layerAdd').click();assert.equal(await page.evaluate(()=>PP6.textElements(YebaeonEditor.current()).length),initialBoxes+1);
 const input=page.locator('#texts label:visible textarea');await input.fill('부분 서식 시험');await input.evaluate(e=>{e.setSelectionRange(0,2);e.dispatchEvent(new Event('select'));});
 await page.waitForFunction(()=>document.querySelector('#layerProperties .help').textContent.includes('선택한 글자'));
 await page.locator('#layerProperties label').filter({hasText:'글자 크기'}).locator('input').fill('120');await page.locator('#layerProperties label').filter({hasText:'글자 크기'}).locator('input').press('Tab');
 const formatted=await page.evaluate(()=>PP6.parseRTF(PP6.textNode(YebaeonLayout.active()).textContent));assert.equal(formatted.runs[0].text,'부분');assert.equal(formatted.runs[0].style.size,120);assert.notEqual(formatted.runs[1].style.size,120);
 const stage=page.locator('#layoutStage');const before=await page.evaluate(()=>PP6.rect(YebaeonLayout.active()));await stage.focus();await page.keyboard.press('Shift+ArrowRight');assert.equal(await page.evaluate(()=>PP6.rect(YebaeonLayout.active()).x),before.x+10);
 const selectedBox=page.locator('.layer-box.active');const bounds=await selectedBox.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2+30,bounds.y+bounds.height/2+20);await page.mouse.up();assert.ok((await page.evaluate(()=>PP6.rect(YebaeonLayout.active()).x))>before.x+10);
 const resize=await page.locator('.layer-resize').boundingBox(),oldWidth=await page.evaluate(()=>PP6.rect(YebaeonLayout.active()).w);await page.mouse.move(resize.x+6,resize.y+6);await page.mouse.down();await page.mouse.move(resize.x+36,resize.y+26);await page.mouse.up();assert.ok((await page.evaluate(()=>PP6.rect(YebaeonLayout.active()).w))>oldWidth);
 await page.locator('#inspector').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'artifacts/studio-layout-editor.png'});
 const savedXML=await page.evaluate(()=>YebaeonEditor.document().xml);await page.evaluate(xml=>{YebaeonEditor.open(xml,'재열기.pro6',true,'layout-reopen');YebaeonEditor.setView('editor');},savedXML);assert.equal(await page.evaluate(()=>PP6.parseRTF(PP6.textNode(YebaeonLayout.active()).textContent).runs[0].style.size),120);
 await page.locator('#layerList').getByRole('button',{name:'삭제',exact:true}).click();assert.equal(await page.evaluate(()=>PP6.textElements(YebaeonEditor.current()).length),initialBoxes);assert.equal(await page.locator('#undo').isEnabled(),true);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>PP6.textElements(YebaeonEditor.current()).length),initialBoxes+1);
 // Virtual time verifies idle screens do not keep querying the production DB.
 const beforeIdleLights=await page.evaluate(()=>{window.__idleLights=0;const api=YebaeonCloud.api;YebaeonCloud.api=(path,...args)=>{if(path.startsWith('/sync-observations'))window.__idleLights++;return api(path,...args);};return window.__idleLights;});
 await page.clock.install();await page.clock.fastForward(65000);assert.equal(await page.evaluate(()=>window.__idleLights),beforeIdleLights);
 const statusPage=await browser.newPage({viewport:{width:1440,height:960}});let statusReads=0,detailReads=0;
 await statusPage.clock.install();
 await statusPage.route('**/api/status*',async route=>{const detailed=new URL(route.request().url()).searchParams.has('details');statusReads++;if(detailed)detailReads++;const storage={currentDocuments:{count:3000,bytes:1024},currentPlaylists:{count:1,bytes:100},documentHistory:{count:2,bytes:200},playlistHistory:{count:0,bytes:0},trackedBytes:1324};await route.fulfill({json:{documents:3000,bytes:1024,playlists:1,images:{count:3412,bytes:1976000000},catalogDocuments:3107,unavailableDocuments:107,recent:[{id:'d1',path:'찬양/은혜.pro6',version:3,author:'본당 Mac',device:true,updatedAt:'2026-10-02T07:30:00Z',lastDateUsed:null}],studio:[{author:'김시험',at:'2026-10-02T07:20:00Z',docs:['은혜','광고','말씀'],docCount:5,nodes:['주일 1부'],nodeCount:1,images:0}],syncEvents:[{kind:'applied',device:'본당 Mac',at:'2026-10-02T07:31:00Z',names:['은혜'],count:1,images:1},{kind:'remote',device:'본당 Mac',at:'2026-10-02T07:25:00Z',action:'전체 확인',target:'',author:'김시험',state:'done'}],devices:[{name:'본당 Mac',statusAt:'2026-10-02T07:32:00Z'}],observedAt:'2026-10-02T07:35:00Z',...(detailed?{storage}:{})}});});
 await statusPage.route('**/resources/catalog.json',r=>r.fulfill({json:{expectedDocuments:3107,fonts:[],media:[],templateFiles:0,templates:0,bible:{name:'개역개정',verses:31103}}}));
 await statusPage.goto(`http://127.0.0.1:${server.address().port}/status.html`);await statusPage.locator('#dashboard').waitFor({state:'visible'});assert.equal(statusReads,1);assert.equal(detailReads,0);
 assert.equal(await statusPage.locator('#imageCount').textContent(),'3,412');assert.match(await statusPage.locator('#studio').textContent(),/순서주일 1부 · 문서은혜, 광고, 말씀 외 2/);
 assert.match(await statusPage.locator('#syncEvents').textContent(),/받기은혜 · 이미지 1/);assert.match(await statusPage.locator('#syncEvents').textContent(),/전체 확인 · 김시험 요청 · 완료/);assert.equal(await statusPage.locator('#recent .src.mac').textContent(),'Mac');
 await statusPage.clock.fastForward(65000);await statusPage.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));assert.equal(statusReads,1);
 await statusPage.locator('#refresh').click();await statusPage.waitForFunction(()=>document.getElementById('message').textContent.includes('확인했습니다'));assert.equal(statusReads,2);
 await statusPage.locator('#storageRefresh').click();await statusPage.locator('#storagePanel').waitFor({state:'visible'});assert.equal(detailReads,1);assert.equal(await statusPage.locator('#storage tr').count(),4);
 const batchPuts=[];await statusPage.route('**/api/media**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/media/paths'){const folder=u.searchParams.get('folder');await route.fulfill({json:{paths:folder==='Images'?[{path:'x/Images/a.jpg',sha256:'a'.repeat(64),size:1},{path:'x/Images/b.jpg',sha256:'b'.repeat(64),size:1}]:[{path:'x/YebaeOn/c.png',sha256:'c'.repeat(64),size:1}],next:null}});return;}if(u.pathname==='/api/media'){await route.fulfill({json:{thumbnails:['b'.repeat(64)]}});return;}if(u.pathname.endsWith('/content')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAAEElEQVR4nGNQSDgARww4OQAdNg8BkwvKGAAAAABJRU5ErkJggg==','base64')});return;}if(u.pathname.endsWith('/thumbnail')&&route.request().method()==='PUT'){batchPuts.push(u.pathname.split('/')[3]);await route.fulfill({json:{}});return;}await route.fulfill({status:404,json:{}});});
 await statusPage.locator('#thumbnailBatch').click();await statusPage.waitForFunction(()=>/^끝/.test(document.getElementById('thumbnailProgress').textContent));assert.deepEqual(batchPuts.sort(),['a'.repeat(64),'c'.repeat(64)],'only images without a preview are made');assert.match(await statusPage.locator('#thumbnailProgress').textContent(),/새로 만든 미리보기 2개 · 전체 3개 중 3개 있음/);await statusPage.evaluate(()=>scrollTo(0,0));await statusPage.screenshot({path:'artifacts/server-status-manual.png'});await statusPage.close();

 // A failed initial session probe must not permanently lock the login form.
 const retryPage=await browser.newPage({viewport:{width:900,height:700}});
 let loginAttempts=0;
 await retryPage.route('**/api/**',async route=>{
  const path=new URL(route.request().url()).pathname;
  if(path==='/api/session'){
   if(route.request().method()==='GET'){await route.abort('failed');return;}
   loginAttempts++;
   await route.fulfill(loginAttempts===1?{status:401,json:{error:'wrong_password',message:'공용 비밀번호가 맞지 않습니다.'}}:{json:{ready:true,authenticated:true,name:'재시도 시험'}});return;
  }
  await route.fulfill({json:path==='/api/playlists'?{libraries:[],next:null}:{items:{}}});
 });
 await retryPage.goto(`http://127.0.0.1:${server.address().port}/`);
 await retryPage.locator('#entryDialog').waitFor({state:'visible'});
 assert.equal(await retryPage.locator('#entrySubmit').isEnabled(),true);
 assert.match(await retryPage.locator('#entryMessage').textContent(),/다시 시도/);
 await retryPage.locator('#entryName').fill('재시도 시험');
 await retryPage.locator('#entryPassword').fill('test-only-invalid-password');
 await retryPage.locator('#entrySubmit').click();
 await retryPage.waitForFunction(()=>document.getElementById('entryMessage').textContent.includes('맞지 않습니다'));
 assert.equal(await retryPage.locator('#entrySubmit').isEnabled(),true);
 await retryPage.screenshot({path:'artifacts/studio-login-retry.png'});
 await retryPage.locator('#entryPassword').fill('test-only-correct-password');
 await retryPage.locator('#entrySubmit').click();
 await retryPage.waitForFunction(()=>YebaeonCloud.authenticated()&&!document.getElementById('entryDialog').open);
 assert.equal(loginAttempts,2);
 await retryPage.close();
 // Load original server files in Chromium; synthetic text avoids publishing church originals.
 const fontsPage=await browser.newPage({viewport:{width:1100,height:800},deviceScaleFactor:2});
 await fontsPage.route('**/resources/*.otf',async route=>{const file=new URL(route.request().url()).pathname.split('/').pop();await route.fulfill({contentType:'font/otf',body:await readFile('church-resources/'+file)});});
 await fontsPage.route('**/font-preview.html',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><body></body></html>'}));
 await fontsPage.goto(`http://127.0.0.1:${server.address().port}/font-preview.html`);await fontsPage.setContent('<canvas id="scene" width="1920" height="1080" style="width:960px"></canvas>');
 for(const file of ['pp6.js','fonts.js','render.js','sample-demo.js'])await fontsPage.addScriptTag({path:'web-editor/'+file});
 const actualCatalog=JSON.parse(await readFile('church-resources/catalog.json','utf8'));
 const actualFonts=await fontsPage.evaluate(async catalog=>{PP6Fonts.registerCatalog(catalog.fonts);const m=PP6.parse(PP6_SAMPLE.xml,'font-test'),slide=PP6.slides(m)[0],box=PP6.textElements(slide)[0];PP6.mediaElements(slide).forEach(e=>e.remove());slide.setAttribute('drawingBackgroundColor','true');slide.setAttribute('backgroundColor','.2 .2 .2 1');PP6.setRect(box,{x:50,y:100,w:1820,h:800});
  const verify=[];for(const f of catalog.fonts.filter(f=>f.name.startsWith('Arita-buri-'))){PP6.textNode(box).textContent=PP6.textRTF('원본 글꼴 시험',{font:f.name,size:99,color:'#ffffff',align:'center',bold:false,leading:-30,tracking:-5});const warnings=await PP6Fonts.ensure(slide);verify.push({name:f.name,weight:PP6Fonts.resolve({font:f.name}).weight,warnings});}
  PP6.textNode(box).textContent=PP6.textRTF('원본 글꼴과 아웃라인\n줄 간격과 자간',{font:'NanumGothicOTF',bold:true,size:110,color:'#ffffff',align:'center',leading:23,tracking:0,strokeWidth:-5,strokeColor:'#000000'});const canvas=document.getElementById('scene');await PP6Render.draw(canvas,m,slide,new Map());const outlined=canvas.toDataURL();PP6.formatRange(box,0,0,{strokeWidth:0});await PP6Render.draw(canvas,m,slide,new Map());const strokeChanged=outlined!==canvas.toDataURL();PP6.formatRange(box,0,0,{strokeWidth:-5});await PP6Render.draw(canvas,m,slide,new Map());
  const aritaBold=PP6Fonts.resolve({font:'Arita-buri-Medium_OTF',bold:true}),nanumBold=PP6Fonts.resolve({font:'NanumGothicOTF',bold:true});return {verify,aritaBold,nanumBold,strokeChanged,loaded:PP6Fonts.state()};
 },actualCatalog);
 assert.equal(actualFonts.verify.length,5);assert.ok(actualFonts.verify.every(f=>f.warnings.length===0));assert.equal(actualFonts.aritaBold.family,'YebaeFont-arita-burib-otf');assert.equal(actualFonts.aritaBold.note,'');assert.equal(actualFonts.nanumBold.family,'YebaeFont-nanumgothicbold-otf');assert.equal(actualFonts.strokeChanged,true);assert.ok(actualFonts.loaded.every(f=>f.status==='loaded'));
 await fontsPage.locator('#scene').screenshot({path:'artifacts/studio-original-fonts.png'});console.log('Original font files and outlined render verified:',JSON.stringify(actualFonts));await fontsPage.close();
 assert.deepEqual(errors,[]);
 console.log('Studio browser flows passed: original/preview reuse, version/edit/font invalidation, template names after apply/reopen/reload, editing, save, undo, clipboard, reflow, IME, menu, Bible, explicit order save, draft recovery/conflict and activity');
 }finally{await page.screenshot({path:'artifacts/studio-final.png'}).catch(()=>{});await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});






