import test from 'node:test';import assert from 'node:assert/strict';
import {folderPath,dropboxRoute} from '../cloudflare/dropbox.mjs';
test('Dropbox paths stay under configured folder and reject traversal',()=>{assert.equal(folderPath('/교회/주보','2026/a.hwp'),'/교회/주보/2026/a.hwp');for(const path of ['../private','a/../private','/private','a//b','a\\b'])assert.throws(()=>folderPath('/교회',path));assert.equal(folderPath('/'),'');assert.equal(folderPath('/','x'),'/x');for(const root of ['', '//', '/a/', '/a/../b'])assert.throws(()=>folderPath(root,'x'));for(const path of ['../x','/x','a//b'])assert.throws(()=>folderPath('/',path));});
test('Dropbox read-only route, Unicode pagination, scoped downloads and refresh credential isolation',async t=>{const old=globalThis.fetch;t.after(()=>globalThis.fetch=old);const env={SITE_PASSWORD:'test-password',DROPBOX_ROOT:'/교회',DROPBOX_APP_KEY:'key',DROPBOX_APP_SECRET:'secret',DROPBOX_REFRESH_TOKEN:'refresh-test'};let calls=[];
 globalThis.fetch=async(url,opts)=>{calls.push({url,opts});if(url.endsWith('/oauth2/token'))return Response.json({access_token:'hidden-access',expires_in:3600});if(url.endsWith('/list_folder'))return Response.json({entries:[{'.tag':'folder',name:'주보',path_display:'/교회/주보',path_lower:'/교회/주보'},{'.tag':'file',name:'private',path_lower:'/private'}],has_more:true,cursor:'opaque'});if(url.endsWith('/list_folder/continue'))return Response.json({entries:[],has_more:false});if(url.endsWith('/get_metadata'))return Response.json({'.tag':'file',name:'a.hwp',path_lower:'/교회/a.hwp'});return new Response('HWP');};
 const call=(action,query='')=>dropboxRoute(new Request('https://example.test/api/dropbox/'+action+query),env,action);
 const result=await(await call('list')).json();assert.equal(result.entries.length,1);assert.equal(result.entries[0].path,'주보');assert.ok(!JSON.stringify(result).includes('hidden-access'));await call('list','?cursor='+encodeURIComponent(result.next));await assert.rejects(()=>call('list','?path=주보&cursor='+encodeURIComponent(result.next)),/새로/);await assert.rejects(()=>call('list','?cursor=forged'),/새로/);const download=await call('file','?path=a.hwp');assert.equal(await download.text(),'HWP');assert.match(download.headers.get('content-disposition'),/^attachment/);assert.equal(calls.filter(c=>c.url.endsWith('/oauth2/token')).length,1);assert.deepEqual(await(await dropboxRoute(new Request('https://x.test/api/dropbox/config'),{},'config')).json(),{ready:false});await assert.rejects(()=>dropboxRoute(new Request('https://x.test/api/dropbox/list',{method:'POST'}),env,'list'),/지원/);
});

test('Dropbox account root lists, paginates and downloads nested files without losing path segments',async t=>{const old=globalThis.fetch;t.after(()=>globalThis.fetch=old);const env={SITE_PASSWORD:'test-password',DROPBOX_ROOT:'/',DROPBOX_APP_KEY:'key',DROPBOX_APP_SECRET:'secret',DROPBOX_REFRESH_TOKEN:'root-test'};const paths=[];
 globalThis.fetch=async(url,opts)=>{if(url.endsWith('/oauth2/token'))return Response.json({access_token:'hidden-root',expires_in:3600});const data=opts.body?JSON.parse(opts.body):null;if(url.endsWith('/list_folder')){paths.push(data.path);return Response.json({entries:[{'.tag':'folder',name:'HANWOORI',path_display:'/HANWOORI',path_lower:'/hanwoori'},{'.tag':'file',name:'other.hwp',path_display:'/Other/other.hwp',path_lower:'/other/other.hwp'}],has_more:true,cursor:'root-cursor'});}if(url.endsWith('/list_folder/continue'))return Response.json({entries:[],has_more:false});if(url.endsWith('/get_metadata')){assert.equal(data.path,'/HANWOORI/06주보/a.hwp');return Response.json({'.tag':'file',name:'a.hwp',path_lower:'/hanwoori/06주보/a.hwp'});}assert.equal(JSON.parse(opts.headers['Dropbox-API-Arg']).path,'/HANWOORI/06주보/a.hwp');return new Response('HWP');};
 const call=(action,query='',e=env)=>dropboxRoute(new Request('https://example.test/api/dropbox/'+action+query),e,action);
 const result=await(await call('list')).json();assert.deepEqual(result.entries.map(e=>e.path),['HANWOORI','Other/other.hwp']);await call('list','?cursor='+encodeURIComponent(result.next));await assert.rejects(()=>call('list','?cursor='+encodeURIComponent(result.next),{...env,DROPBOX_ROOT:'/교회'}),/새로/);await call('list','?path=HANWOORI');assert.deepEqual(paths,['','/HANWOORI']);assert.equal(await(await call('file','?path='+encodeURIComponent('HANWOORI/06주보/a.hwp'))).text(),'HWP');await assert.rejects(()=>call('file'),/파일/);
});

test('Dropbox download refuses files over the requested size before downloading',async t=>{const old=globalThis.fetch;t.after(()=>globalThis.fetch=old);const env={SITE_PASSWORD:'test-password',DROPBOX_ROOT:'/교회',DROPBOX_APP_KEY:'key',DROPBOX_APP_SECRET:'secret',DROPBOX_REFRESH_TOKEN:'size-test'};let downloads=0;
 globalThis.fetch=async url=>{if(url.endsWith('/oauth2/token'))return Response.json({access_token:'hidden',expires_in:3600});if(url.endsWith('/get_metadata'))return Response.json({'.tag':'file',name:'big.pptx',path_lower:'/교회/big.pptx',size:50*1048576});downloads++;return new Response('PPTX');};
 const call=query=>dropboxRoute(new Request('https://example.test/api/dropbox/file'+query),env,'file');
 await assert.rejects(()=>call('?path=big.pptx&max='+40*1048576),/40MB 이하/);assert.equal(downloads,0);
 assert.equal(await(await call('?path=big.pptx')).text(),'PPTX','no cap keeps the plain download');
});
