import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRs0AAAAASUVORK5CYII=','base64');
const hash=value=>createHash('sha256').update(value).digest('hex');
test('content-addressed image upload, retry, reference registration, download and protection CAS',{timeout:90000},async t=>{
  const bundled=await build({entryPoints:['cloudflare/worker.mjs'],bundle:true,write:false,format:'esm',platform:'browser'});
  const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-28',bindings:{SITE_PASSWORD:'media-test'},d1Databases:['DB'],r2Buckets:['FILES'],cf:false}));
  t.after(()=>mf.dispose());
  const origin='https://example.test';let cookie='';
  const call=(path,method='GET',body,extra={})=>mf.dispatchFetch(origin+'/api'+path,{method,body,headers:{Cookie:cookie,...method==='GET'||method==='HEAD'?{}:{Origin:origin},...extra}});
  const ok=async(response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
  assert.equal((await call('/media?hash='+hash(png))).status,401);
  const login=await call('/session','POST',JSON.stringify({name:'시험',password:'media-test'}),{'Content-Type':'application/json',Origin:origin});
  await ok(login);cookie=login.headers.get('Set-Cookie').split(';')[0];
  const digest=hash(png),uploadHeaders={'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':digest};
  assert.equal((await call('/media/'+digest+'/content','PUT',png,{'Origin':'https://other.test',...uploadHeaders})).status,403,'foreign Origin is rejected');
  assert.equal((await call('/media/'+digest+'/content','PUT',png,{'Origin':origin,'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':'0'.repeat(64)})).status,400);
  const first=await ok(await call('/media/'+digest+'/content','PUT',png,{'Origin':origin,...uploadHeaders}),201);
  assert.equal(first.asset.sha256,digest);assert.equal(first.asset.contentType,'image/png');assert.equal(first.asset.protected,true);
  const retry=await ok(await call('/media/'+digest+'/content','PUT',png,{'Origin':origin,...uploadHeaders}));
  assert.equal(retry.unchanged,true,'a lost response can be retried without duplicating the R2 object');
  const corrupt=Buffer.from(png);corrupt[corrupt.length-1]^=1;
  assert.equal((await call('/media/'+digest+'/content','PUT',corrupt,{'Origin':origin,...uploadHeaders})).status,422);
  let listed=await ok(await call('/media?hash='+digest+'&hash='+hash(Buffer.from('missing'))));
  assert.equal(listed.assets.length,1);assert.equal(listed.assets[0].sha256,digest);
  const file=await call('/media/'+digest+'/content');assert.equal(file.headers.get('X-Yebaeon-SHA256'),digest);assert.deepEqual(Buffer.from(await file.arrayBuffer()),png);
  assert.equal((await call('/media/'+digest+'/content','HEAD')).headers.get('Content-Length'),String(png.length));
  const made=await call('/documents?path=song.pro6','POST','<RVPresentationDocument category="가사찬양"><text>sample</text></RVPresentationDocument>',{'Origin':origin,'Content-Type':'application/xml'});
  const document=(await ok(made,201)).document;
  const refs=JSON.stringify({documentId:document.id,version:document.version,references:[{id:'slide-0-element-0',sha256:digest,source:'/old/배경.png',slide:0}]});
  const registered=await ok(await call('/media/references','PUT',refs,{'Origin':origin,'Content-Type':'application/json'}));
  assert.equal(registered.references,1);assert.equal(registered.uniqueAssets,1);
  const referenceRead=await ok(await call('/media/references?documentId='+document.id+'&version='+document.version));
  assert.equal(referenceRead.references.length,1);assert.equal(referenceRead.references[0].sha256,digest);
  assert.equal((await call('/media/references?documentId='+document.id+'&version=99')).status,409,'stale document media references cannot be downloaded as current');
  assert.equal((await call('/media/references','PUT',refs,{'Origin':origin,'Content-Type':'application/json'})).status,200,'same document version can retry reference registration');
  const db=await mf.getD1Database('DB');
  assert.equal((await db.prepare('SELECT count(*) AS n FROM yebaeon_media_references').first()).n,1);
  const protection=await ok(await call('/media/'+digest+'/protection','PUT',JSON.stringify({protected:false,revision:1}),{'Origin':origin,'Content-Type':'application/json'}));
  assert.equal(protection.asset.protected,false);assert.equal(protection.asset.revision,2);
  assert.equal((await call('/media/'+digest+'/protection','PUT',JSON.stringify({protected:true,revision:1}),{'Origin':origin,'Content-Type':'application/json'})).status,409);
  assert.equal((await call('/media/'+digest+'/protection','PUT',JSON.stringify({protected:true,revision:2}),{'Origin':origin,'Content-Type':'application/json'})).status,200);
  assert.equal((await call('/media/'+digest+'/protection')).status,405);
  assert.equal((await call('/media/references','PUT',JSON.stringify({...JSON.parse(refs),version:99}),{'Origin':origin,'Content-Type':'application/json'})).status,409,'stale document version cannot replace media references');
  const absent='f'.repeat(64);
  assert.equal((await call('/media/references','PUT',JSON.stringify({...JSON.parse(refs),references:[{id:'x',sha256:absent,source:'/x.png',slide:0}]}),{'Origin':origin,'Content-Type':'application/json'})).status,409,'references require uploaded immutable assets');
  assert.equal((await db.prepare('SELECT count(*) AS n FROM yebaeon_media_references').first()).n,1,'failed registration leaves existing references intact');
  // Browser-imported images register with the document transaction, and follow
  // edits/duplication without a second, failure-prone references request.
  const importedXML=(label='one',sha=digest)=>`<RVPresentationDocument width="1920" height="1080" category="악보찬양"><array rvXMLIvarName="groups"><RVSlideGrouping><array rvXMLIvarName="slides"><RVDisplaySlide label="${label}"><array rvXMLIvarName="displayElements"><RVImageElement source="file:///YebaeOn-Media/${sha}.png"/></array></RVDisplaySlide></array></RVSlideGrouping></array></RVPresentationDocument>`;
  const imported=(await ok(await call('/documents?path=imported.pro6','POST',importedXML(),{'Content-Type':'application/xml'}),201)).document;
  const importRefs=async version=>(await ok(await call('/media/references?documentId='+imported.id+'&version='+version))).references;
  assert.equal((await importRefs(1))[0].slide,1,'native Sync indexes slides from one');
  assert.equal((await importRefs(1))[0].sha256,digest);
  const updated=(await ok(await call('/documents/'+imported.id,'PUT',importedXML('two'),{'Content-Type':'application/xml','If-Match':'"1"'}))).document;
  assert.equal(updated.version,2);assert.equal((await importRefs(2)).length,1);
  assert.equal((await call('/documents/'+imported.id,'PUT',importedXML('three'),{'Content-Type':'application/xml','If-Match':'"1"'})).status,409);
  assert.equal((await importRefs(2)).length,1,'conflict cannot replace references');
  assert.equal((await call('/documents?path=missing-import.pro6','POST',importedXML('missing','a'.repeat(64)),{'Content-Type':'application/xml'})).status,409);
  assert.equal(await db.prepare('SELECT id FROM yebaeon_documents WHERE path=?').bind('missing-import.pro6').first(),null,'missing assets cannot commit a document');

});
