import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRs0AAAAASUVORK5CYII=','base64');
const hash=value=>createHash('sha256').update(value).digest('hex');
const ROOT='/Users/Shared/Renewed Vision Media/';
test('media library: folder listing without ImportedImages, cacheable bytes, shared favorites, status image totals',{timeout:90000},async t=>{
  const bundled=await build({entryPoints:['cloudflare/worker.mjs'],bundle:true,write:false,format:'esm',platform:'browser'});
  const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-28',bindings:{SITE_PASSWORD:'media-test'},d1Databases:['DB'],r2Buckets:['FILES'],cf:false}));
  t.after(()=>mf.dispose());
  const origin='https://example.test';let cookie='';
  const call=(path,method='GET',body,extra={})=>mf.dispatchFetch(origin+'/api'+path,{method,body,headers:{Cookie:cookie,...method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'},...extra}});
  const ok=async(response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
  const login=await call('/session','POST',JSON.stringify({name:'시험',password:'media-test'}));await ok(login);cookie=login.headers.get('Set-Cookie').split(';')[0];
  const a=png,b=Buffer.concat([png,Buffer.from([0])]);
  for(const bytes of [a,b])assert.ok([200,201].includes((await call('/media/'+hash(bytes)+'/content','PUT',bytes,{'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':hash(bytes)})).status));
  const items=[['Images/배경 하늘.png',a],['Images/광고 가을.png',b],['ImportedImages/X/Slide01.jpg',a],['YebaeOn/설교-1.png',b]].map(([p,bytes])=>({path:ROOT+p,sha256:hash(bytes),size:bytes.length}));
  await ok(await call('/media/paths','PUT',JSON.stringify({items})));
  const images=await ok(await call('/media/paths?folder=Images'));
  assert.deepEqual(images.paths.map(p=>p.path),[ROOT+'Images/광고 가을.png',ROOT+'Images/배경 하늘.png']);assert.equal(images.next,null);
  assert.deepEqual((await ok(await call('/media/paths?folder=Images&q='+encodeURIComponent('하늘')))).paths.map(p=>p.path),[ROOT+'Images/배경 하늘.png']);
  assert.deepEqual((await ok(await call('/media/paths?folder=Images&q=%25'))).paths,[],'a literal % does not match everything');
  assert.deepEqual((await ok(await call('/media/paths?folder=YebaeOn'))).paths.map(p=>p.path),[ROOT+'YebaeOn/설교-1.png']);
  assert.equal((await call('/media/paths?folder=ImportedImages')).status,400,'imported slide images are not listed');
  assert.equal((await call('/media/paths?folder=Images&after='+encodeURIComponent(ROOT+'YebaeOn/'))).status,400,'the cursor stays inside the folder');
  const bytes=await call('/media/'+hash(a)+'/content');assert.match(bytes.headers.get('Cache-Control'),/private, max-age=31536000, immutable/);
  assert.deepEqual((await ok(await call('/favorites'))).items,[]);
  await ok(await call('/favorites','PUT',JSON.stringify({kind:'media',key:hash(a),label:'배경 하늘.png',on:true})));
  await ok(await call('/favorites','PUT',JSON.stringify({kind:'template',key:'104',label:'성경 · 본문',on:true})));
  assert.equal((await call('/favorites','PUT',JSON.stringify({kind:'media',key:'not-a-sha',on:true}))).status,400);
  assert.equal((await call('/favorites','PUT',JSON.stringify({kind:'media',key:hash(a),on:true}),{Origin:'https://other.test'})).status,403);
  let favorites=(await ok(await call('/favorites'))).items;assert.deepEqual(favorites.map(f=>[f.kind,f.key,f.addedBy]).sort(),[['media',hash(a),'시험'],['template','104','시험']]);
  await ok(await call('/favorites','PUT',JSON.stringify({kind:'template',key:'104',on:false})));
  favorites=(await ok(await call('/favorites'))).items;assert.deepEqual(favorites.map(f=>f.kind),['media']);
  const status=await ok(await call('/status?details=1'));
  assert.deepEqual(status.storage.images,{count:2,bytes:a.length+b.length});
  assert.deepEqual(status.storage.imageFolders.map(f=>[f.folder,f.count]),[['Images',2],['ImportedImages',1],['YebaeOn',1]]);
});
