import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRs0AAAAASUVORK5CYII=','base64');
const hash=value=>createHash('sha256').update(value).digest('hex');
test('content-addressed image upload, retry, reference registration, download and protection CAS',{timeout:90000},async t=>{
  const bundled=await build({entryPoints:['cloudflare/worker.mjs'],bundle:true,write:false,format:'esm',platform:'browser'});
  const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-28',bindings:{SITE_PASSWORD:'media-test'},d1Databases:['DB'],r2Buckets:['FILES'],cf:false}));
  t.after(()=>mf.dispose());
  const origin='https://example.test';let cookie='';
  const call=(path,method='GET',body,extra={})=>mf.dispatchFetch(origin+'/api'+path,{method,body,headers:{Cookie:cookie,...method==='GET'||method==='HEAD'?{}:{Origin:origin},...extra}});
  const ok=async(response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
  assert.equal((await call('/media?hash='+hash(png))).status,401);
  const login=await call('/session','POST',JSON.stringify({name:'시험',password:'media-test'}),{'Content-Type':'application/json',Origin:origin});
  await ok(login);cookie=login.headers.get('Set-Cookie').split(';')[0];
  const digest=hash(png),uploadHeaders={'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':digest};
  assert.equal((await call('/media/'+digest+'/content','PUT',png,{'Origin':'https://other.test',...uploadHeaders})).status,403,'foreign Origin is rejected');
  assert.equal((await call('/media/'+digest+'/content','PUT',png,{'Origin':origin,'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':'0'.repeat(64)})).status,400);
  const first=await ok(await call('/media/'+digest+'/content','PUT',png,{'Origin':origin,...uploadHeaders}),201);
  assert.equal(first.asset.sha256,digest);assert.equal(first.asset.contentType,'image/png');assert.equal(first.asset.protected,true);
  const retry=await ok(await call('/media/'+digest+'/content','PUT',png,{'Origin':origin,...uploadHeaders}));
  assert.equal(retry.unchanged,true,'a lost response can be retried without duplicating the R2 object');
  const corrupt=Buffer.from(png);corrupt[corrupt.length-1]^=1;
  assert.equal((await call('/media/'+digest+'/content','PUT',corrupt,{'Origin':origin,...uploadHeaders})).status,422);
  let listed=await ok(await call('/media?hash='+digest+'&hash='+hash(Buffer.from('missing'))));
  assert.equal(listed.assets.length,1);assert.equal(listed.assets[0].sha256,digest);
  const file=await call('/media/'+digest+'/content');assert.equal(file.headers.get('X-Yebaeon-SHA256'),digest);assert.deepEqual(Buffer.from(await file.arrayBuffer()),png);
  assert.equal((await call('/media/'+digest+'/content','HEAD')).headers.get('Content-Length'),String(png.length));
  const made=await call('/documents?path=song.pro6','POST','<RVPresentationDocument category="가사찬양"><text>sample</text></RVPresentationDocument>',{'Origin':origin,'Content-Type':'application/xml'});
  const document=(await ok(made,201)).document;
  const refs=JSON.stringify({documentId:document.id,version:document.version,references:[{id:'slide-0-element-0',sha256:digest,source:'/old/배경.png',slide:0}]});
  const registered=await ok(await call('/media/references','PUT',refs,{'Origin':origin,'Content-Type':'application/json'}));
  assert.equal(registered.references,1);assert.equal(registered.uniqueAssets,1);
  const referenceRead=await ok(await call('/media/references?documentId='+document.id+'&version='+document.version));
  assert.equal(referenceRead.references.length,1);assert.equal(referenceRead.references[0].sha256,digest);
  assert.equal((await call('/media/references?documentId='+document.id+'&version=99')).status,409,'stale document media references cannot be downloaded as current');
  assert.equal((await call('/media/references','PUT',refs,{'Origin':origin,'Content-Type':'application/json'})).status,200,'same document version can retry reference registration');
  const db=await mf.getD1Database('DB');
  assert.equal((await db.prepare('SELECT count(*) AS n FROM yebaeon_media_references').first()).n,1);
  const protection=await ok(await call('/media/'+digest+'/protection','PUT',JSON.stringify({protected:false,revision:1}),{'Origin':origin,'Content-Type':'application/json'}));
  assert.equal(protection.asset.protected,false);assert.equal(protection.asset.revision,2);
  assert.equal((await call('/media/'+digest+'/protection','PUT',JSON.stringify({protected:true,revision:1}),{'Origin':origin,'Content-Type':'application/json'})).status,409);
  assert.equal((await call('/media/'+digest+'/protection','PUT',JSON.stringify({protected:true,revision:2}),{'Origin':origin,'Content-Type':'application/json'})).status,200);
  assert.equal((await call('/media/'+digest+'/protection')).status,405);
  assert.equal((await call('/media/references','PUT',JSON.stringify({...JSON.parse(refs),version:99}),{'Origin':origin,'Content-Type':'application/json'})).status,409,'stale document version cannot replace media references');
  const absent='f'.repeat(64);
  assert.equal((await call('/media/references','PUT',JSON.stringify({...JSON.parse(refs),references:[{id:'x',sha256:absent,source:'/x.png',slide:0}]}),{'Origin':origin,'Content-Type':'application/json'})).status,409,'references require uploaded immutable assets');
  assert.equal((await db.prepare('SELECT count(*) AS n FROM yebaeon_media_references').first()).n,1,'failed registration leaves existing references intact');
  // Browser-imported images register with the document transaction, and follow
  // edits/duplication without a second, failure-prone references request.
  const importedXML=(label='one',sha=digest)=>`<RVPresentationDocument width="1920" height="1080" category="악보찬양"><array rvXMLIvarName="groups"><RVSlideGrouping><array rvXMLIvarName="slides"><RVDisplaySlide label="${label}"><array rvXMLIvarName="displayElements"><RVImageElement source="file:///YebaeOn-Media/${sha}.png"/></array></RVDisplaySlide></array></RVSlideGrouping></array></RVPresentationDocument>`;
  const imported=(await ok(await call('/documents?path=imported.pro6','POST',importedXML(),{'Content-Type':'application/xml'}),201)).document;
  const importRefs=async version=>(await ok(await call('/media/references?documentId='+imported.id+'&version='+version))).references;
  assert.equal((await importRefs(1))[0].slide,1,'native Sync indexes slides from one');
  assert.equal((await importRefs(1))[0].sha256,digest);
  const updated=(await ok(await call('/documents/'+imported.id,'PUT',importedXML('two'),{'Content-Type':'application/xml','If-Match':'"1"'}))).document;
  assert.equal(updated.version,2);assert.equal((await importRefs(2)).length,1);
  assert.equal((await call('/documents/'+imported.id,'PUT',importedXML('three'),{'Content-Type':'application/xml','If-Match':'"1"'})).status,409);
  assert.equal((await importRefs(2)).length,1,'conflict cannot replace references');
  assert.equal((await call('/documents?path=missing-import.pro6','POST',importedXML('missing','a'.repeat(64)),{'Content-Type':'application/xml'})).status,409);
  assert.equal(await db.prepare('SELECT id FROM yebaeon_documents WHERE path=?').bind('missing-import.pro6').first(),null,'missing assets cannot commit a document');

});

test('import images get church Mac paths under YebaeOn/ and link to the document',{timeout:90000},async t=>{
  const bundled=await build({entryPoints:['cloudflare/worker.mjs'],bundle:true,write:false,format:'esm',platform:'browser'});
  const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-28',bindings:{SITE_PASSWORD:'media-test'},d1Databases:['DB'],r2Buckets:['FILES'],cf:false}));
  t.after(()=>mf.dispose());
  const origin='https://example.test';let cookie='';
  const call=(path,method='GET',body,extra={})=>mf.dispatchFetch(origin+'/api'+path,{method,body,headers:{Cookie:cookie,...method==='GET'?{}:{Origin:origin},...extra}});
  const ok=async(response,status=200)=>{const text=await response.text();assert.equal(response.status,status,text);return JSON.parse(text);};
  const login=await call('/session','POST',JSON.stringify({name:'시험',password:'media-test'}),{'Content-Type':'application/json'});
  await ok(login);cookie=login.headers.get('Set-Cookie').split(';')[0];
  const images=[0,1,2].map(n=>Buffer.concat([png,Buffer.from('slide-'+n)])),hashes=images.map(hash);
  for(const [i,b] of images.entries())await ok(await call('/media/'+hashes[i]+'/content','PUT',b,{'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':hashes[i]}),201);
  const place=(name,list)=>call('/media/paths','POST',JSON.stringify({name,items:list.map(sha256=>({sha256}))}),{'Content-Type':'application/json'});
  const root='/Users/Shared/Renewed Vision Media/YebaeOn/';
  const first=(await ok(await place('주일예배말씀 ppt',hashes.slice(0,2)))).paths;
  assert.deepEqual(first.map(p=>p.path),[root+'주일예배말씀 ppt-1.png',root+'주일예배말씀 ppt-2.png']);
  assert.equal(first[0].size,images[0].length);
  assert.deepEqual((await ok(await place('주일예배말씀 ppt',[hashes[1],hashes[0]]))).paths.map(p=>p.path),[root+'주일예배말씀 ppt-2.png',root+'주일예배말씀 ppt-1.png'],'same image keeps its path');
  assert.equal((await ok(await place('주일예배말씀 ppt',[hashes[2]]))).paths[0].path,root+'주일예배말씀 ppt-3.png','next week continues the numbers');
  assert.equal((await ok(await place('다른 문서',[hashes[0]]))).paths[0].path,root+'주일예배말씀 ppt-1.png','an image already on the Mac is not copied again');
  const db=await mf.getD1Database('DB');
  assert.equal((await db.prepare("SELECT count(*) AS n FROM yebaeon_sync_log WHERE kind='media' AND action='created'").first()).n,3,'each new path is logged once for the Mac ledger');
  const extra=Buffer.concat([png,Buffer.from('odd name')]);await ok(await call('/media/'+hash(extra)+'/content','PUT',extra,{'Content-Type':'application/octet-stream','X-Yebaeon-SHA256':hash(extra)}),201);
  assert.equal((await ok(await place('a/b:c\u0001'+'가'.repeat(80),[hash(extra)]))).paths[0].path,root+'a-b-c-'+'가'.repeat(54)+'-1.png','folder and control characters removed, name cut to 60');
  assert.equal((await place('없음',['e'.repeat(64)])).status,409,'paths only for uploaded images');
  assert.equal((await place('잘못',['x'])).status,400);
  // The document points at the real Mac path; the server links it to the image through the path table.
  const url=p=>'file://'+p.split('/').map(encodeURIComponent).join('/');
  const xml=sources=>`<RVPresentationDocument width="1920" height="1080" category="특별순서"><array rvXMLIvarName="groups"><RVSlideGrouping><array rvXMLIvarName="slides">${sources.map((s,i)=>`<RVDisplaySlide label="${i+1}"><array rvXMLIvarName="displayElements"><RVImageElement source="${s}"/></array></RVDisplaySlide>`).join('')}</array></RVSlideGrouping></array></RVPresentationDocument>`;
  const doc=(await ok(await call('/documents?path='+encodeURIComponent('주일예배말씀 ppt.pro6'),'POST',xml(first.map(p=>url(p.path))),{'Content-Type':'application/xml'}),201)).document;
  const refs=(await ok(await call('/media/references?documentId='+doc.id+'&version=1'))).references;
  assert.deepEqual(refs.map(r=>[r.slide,r.sha256]),[[1,hashes[0]],[2,hashes[1]]]);
  const loose=(await ok(await call('/documents?path=mac.pro6','POST',xml([url(root+'모르는 그림.png')]),{'Content-Type':'application/xml'}),201)).document;
  assert.equal((await ok(await call('/media/references?documentId='+loose.id+'&version=1'))).references.length,0,'unknown YebaeOn paths do not block a Mac document');
});
