import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const xml='<RVPlaylistDocument><RVPlaylistNode UUID="ROOT"><array rvXMLIvarName="children"><RVPlaylistNode UUID="A" displayName="연례 행사"><array rvXMLIvarName="children"><RVDocumentCue UUID="cue" displayName="찬양" filePath="~/Documents/ProPresenter6/song.pro6"/></array></RVPlaylistNode><RVPlaylistNode UUID="B" displayName="주일"><array rvXMLIvarName="children"/></RVPlaylistNode></array></RVPlaylistNode></RVPlaylistDocument>';
test('playlist create, archive snapshot, restoration and stale Sync protection', {timeout:90000},async t=>{
 const bundled=await build({entryPoints:['cloudflare/worker.mjs'],bundle:true,write:false,format:'esm',platform:'browser'});
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-28',bindings:{SITE_PASSWORD:'archives-only'},d1Databases:['DB'],r2Buckets:['FILES'],cf:false}));t.after(()=>mf.dispose());
 const origin='https://example.test';let cookie='';
 const call=(path,method='GET',body,extra={})=>mf.dispatchFetch(origin+'/api'+path,{method,body,headers:{Cookie:cookie,...method==='GET'?{}:{Origin:origin},'Content-Type':'application/json',...extra}});
 const ok=async(response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
 assert.equal((await call('/playlists?scope=archived')).status,401);
 const login=await call('/session','POST',JSON.stringify({name:'시험',password:'archives-only'}));await ok(login);cookie=login.headers.get('Set-Cookie').split(';')[0];
 let lib=(await ok(await call('/playlists?path=fixture.pro6pl','POST',xml),201)).library;
 const path='/playlists/'+lib.id,tag=()=>({'If-Match':`"${lib.version}"`});
 const original='<RVPresentationDocument category="가사찬양"><text>original song</text></RVPresentationDocument>';
 let song=(await ok(await call('/documents?path=song.pro6','POST',original),201)).document;
 const id='88888888-8888-4888-a888-888888888888',body=JSON.stringify({id,name:'새 예배 & 기도'});
 assert.equal((await call(path+'/nodes','POST','null',tag())).status,400);
 assert.equal((await call(path+'/nodes','POST',body,{...tag(),Origin:'https://other.test'})).status,403);
 lib=(await ok(await call(path+'/nodes','POST',body,tag()),201)).library;
 assert.equal(lib.playlists.length,3);
 assert.equal((await ok(await call(path+'/nodes','POST',body,{'If-Match':'"1"'}))).unchanged,true);
 assert.equal((await call(path,'PUT',xml,tag())).status,409,'old full uploads cannot drop new nodes');
 const current=await(await call(path+'/content')).text();
 assert.equal((await call(path+'/archive?node=A','POST','{}',{'If-Match':'"1"'})).status,409);
 lib=(await ok(await call(path+'/archive?node=A','POST','{}',tag()))).library;
 assert.deepEqual(lib.playlists.map(p=>p.id),['B',id]);
 assert.equal((await ok(await call('/playlists?scope=archived'))).archives[0].id,'A');
 const frozen=await ok(await call(path+'/archive?node=A'));assert.equal(frozen.documents.length,1);assert.equal(frozen.media,'references-only');assert.equal(frozen.documents[0].objectKey,undefined);
 const download=path+'/archive?node=A&document='+song.id;
 assert.equal(await(await call(download)).text(),original);
 song=(await ok(await call('/documents/'+song.id,'PUT',original.replace('original','changed'),{'If-Match':'"1"'}))).document;
 assert.equal(song.historyEnabled,false);assert.equal(await(await call(download)).text(),original,'archive copy survives disabled song history');
 assert.equal((await call(path,'PUT',current,tag())).status,409,'old full uploads cannot resurrect archived nodes');
 assert.equal((await ok(await call(path+'/archive?node=A','POST','{}',{'If-Match':'"1"'}))).unchanged,true);
 // A missing current original blocks restoration without dropping the archive.
 const db=await mf.getD1Database('DB'),bucket=await mf.getR2Bucket('FILES');
 const v=await db.prepare('SELECT object_key FROM yebaeon_versions WHERE document_id=? AND version=?').bind(song.id,song.version).first();
 const saved=await(await bucket.get(v.object_key)).arrayBuffer();await bucket.delete(v.object_key);
 assert.equal((await call(path+'/restore?node=A','POST','{}',tag())).status,409);
 assert.equal((await ok(await call('/playlists?scope=archived'))).archives.length,1);
 await bucket.put(v.object_key,saved);
 lib=(await ok(await call(path+'/restore?node=A','POST','{}',tag()))).library;
 assert.equal(lib.playlists.length,3);assert.equal((await ok(await call('/playlists?scope=archived'))).archives.length,0);
 assert.equal((await ok(await call(path+'/plan?node=A'))).documents[0].version,2);
 assert.equal((await ok(await call(path+'/restore?node=A','POST','{}',{'If-Match':'"1"'}))).unchanged,true);
 // Two writers sharing a file version cannot both change structure or controls.
 const candidates=['77777777-7777-4777-a777-777777777777','66666666-6666-4666-a666-666666666666'];
 const results=await Promise.all(candidates.map((id,i)=>call(path+'/nodes','POST',JSON.stringify({id,name:'동시 '+i}),tag())));
 assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);
 const controls=(await db.prepare('SELECT node_id FROM yebaeon_playlist_controls WHERE library_id=?').bind(lib.id).all()).results;
 assert.equal(controls.filter(c=>candidates.includes(c.node_id)).length,1);
});
