#import "YBPlaylistSync.h"
#import "YBPlaylistFormat.h"
#import "YBPlaylistIO.h"
static int checks=0;
static void Check(BOOL ok,NSString *message){checks++;fprintf(stderr,"PLAYLIST CHECK %d: %s\n",checks,message.UTF8String);YBRequire(ok,message);}
static void Reject(void (^action)(void),NSString *message){BOOL rejected=NO;@try{action();}@catch(NSException *e){rejected=[e.name isEqual:@"YebaeOn"];}Check(rejected,message);}
static NSData *D(NSString *text){return [text dataUsingEncoding:NSUTF8StringEncoding];}
static NSData *Doc(NSString *text){return D([NSString stringWithFormat:@"<RVPresentationDocument UUID=\"SAME-DOCUMENT-UUID\" versionNumber=\"600\"><text>%@</text></RVPresentationDocument>",text]);}
static void Put(NSString *path,NSData *data){Check([NSFileManager.defaultManager createDirectoryAtPath:path.stringByDeletingLastPathComponent withIntermediateDirectories:YES attributes:nil error:NULL],@"fixture directory");Check([data writeToFile:path atomically:YES],@"fixture file");}
static NSDictionary *Document(NSDictionary *plan,NSString *path){for(NSDictionary *doc in plan[@"documents"])if([doc[@"path"] isEqual:path])return doc;YBRequire(NO,@"missing document");return nil;}
static NSDictionary *Patch(YBServer *server,NSDictionary *plan,NSArray *items){NSData *data=[NSJSONSerialization dataWithJSONObject:@{@"items":items} options:0 error:NULL];return [server request:[NSString stringWithFormat:@"/api/playlists/%@?node=A",plan[@"library"][@"id"]] method:@"PATCH" body:data headers:@{@"Content-Type":@"application/json",@"If-Match":[NSString stringWithFormat:@"\"%@\"",plan[@"library"][@"version"]]}];}
int main(int argc,const char *argv[]){@autoreleasepool{
    NSString *area=[NSTemporaryDirectory() stringByAppendingPathComponent:[@"yebaeon-playlist-tests-" stringByAppendingString:NSUUID.UUID.UUIDString]];
    @try {
        Check(argc==2,@"Worker address");NSString *origin=[NSString stringWithUTF8String:argv[1]];
        YBServer *server=[[YBServer alloc] initWithOrigin:origin allowLocalTestServer:YES],*web=[[YBServer alloc] initWithOrigin:origin allowLocalTestServer:YES];[server login:@"교회 Mac" password:@"native-integration-only"];[web login:@"웹 준비팀" password:@"native-integration-only"];
        NSString *root=[area stringByAppendingPathComponent:@"documents"],*profile=[area stringByAppendingPathComponent:@"profile"],*song=@"찬양/공유 찬양.pro6",*sermon=@"말씀/말씀.pro6";NSData *original=Doc(@"original"),*edited=Doc(@"web lyrics");
        YBLibrary *library=[[YBLibrary alloc] initWithRoot:root profile:profile server:server];library.sync.presenterRunning=^BOOL{return NO;};
        Put([root stringByAppendingPathComponent:song.decomposedStringWithCanonicalMapping],original);Put([root stringByAppendingPathComponent:sermon],original);Put([root stringByAppendingPathComponent:@"untouched.pro6"],Doc(@"not in selected playlist"));
        NSString *raw=[NSString stringWithFormat:@"<?xml version=\"1.0\"?><RVPlaylistDocument><RVPlaylistNode UUID=\"ROOT\"><array rvXMLIvarName=\"children\"><RVPlaylistNode UUID=\"A\" displayName=\"주일 1부\"><array rvXMLIvarName=\"children\"><RVHeaderCue UUID=\"H\" displayName=\"예배 시작\"/><RVDocumentCue UUID=\"S\" displayName=\"공유 찬양\" filePath=\"~/Documents/ProPresenter6/%@\" selectedArrangementID=\"arrangement\"/><RVDocumentCue UUID=\"T\" displayName=\"말씀\" filePath=\"~/Documents/ProPresenter6/%@\"/></array></RVPlaylistNode><!-- <RVPlaylistNode UUID='FAKE'/> --><RVPlaylistNode UUID=\"B\" displayName=\"주일 2부 > 찬양\"><array rvXMLIvarName=\"children\"><RVDocumentCue UUID=\"S2\" displayName=\"공유 찬양\" filePath=\"~/Documents/ProPresenter6/%@\"/></array></RVPlaylistNode></array></RVPlaylistNode><array rvXMLIvarName=\"deleted\"/></RVPlaylistDocument>",song.decomposedStringWithCanonicalMapping,sermon,song];
        NSURL *target=[NSURL fileURLWithPath:[area stringByAppendingPathComponent:@"playlist/library.pro6pl"]];Put(target.path,D(raw));YBPlaylistSync *engine=[[YBPlaylistSync alloc] initWithLibrary:library target:target];
        Check(YBPlaylistNodes(D(raw)).count==2,@"comments and quoted angle bracket do not create fake playlist nodes");NSString *other=YBPlaylistNode(D(raw),@"B")[@"raw"];
        Check([YBPlaylistReference(@"file:///Users/church/Documents/ProPresenter6/%EC%B0%AC%EC%96%91/test.pro6",@"~/Documents/ProPresenter6") isEqual:@"찬양/test.pro6"],@"file URL and user folder map");Check(!YBPlaylistReference(@"~/Documents/ProPresenter6/../evil.pro6",@"~/Documents/ProPresenter6"),@"traversal rejected");
        NSDictionary *automatic=[engine reconcileFileWithLibraries:[engine libraries]];NSString *autoID=automatic[@"libraries"][0][@"id"];
        NSString *stateName=[NSString stringWithFormat:@"playlist-state-%@.json",YBHash(D(target.path.stringByStandardizingPath))];NSDictionary *state=[NSJSONSerialization JSONObjectWithData:YBReadSafeFile(profile,stateName,NULL) options:0 error:NULL];
        Check([state[@"entries"] count]==2 && state[@"entries"][[autoID stringByAppendingString:@"/A"]]!=nil,@"automatic registration records every node baseline");
        NSMutableDictionary *legacyState=[state mutableCopy];legacyState[@"entries"]=@{};YBWriteSafeFile(profile,stateName,[NSJSONSerialization dataWithJSONObject:legacyState options:0 error:NULL],0600,nil);
        [engine reconcileFileWithLibraries:[engine libraries]];state=[NSJSONSerialization JSONObjectWithData:YBReadSafeFile(profile,stateName,NULL) options:0 error:NULL];Check([state[@"entries"] count]==2,@"old exact file registration safely repairs missing node baselines");
        NSDictionary *registration=[engine registerFileWithSourceRoot:@"~/Documents/ProPresenter6" progress:nil];Check([registration[@"count"] isEqual:@2] && [registration[@"issues"] count]==0,@"register library and unique referenced documents, not unrelated local files");NSString *identifier=registration[@"library"][@"id"];
        Check([engine libraries].count==1,@"native server playlist listing");NSDictionary *plan=[engine manifest:identifier node:@"A"];Check([plan[@"ready"] boolValue] && [plan[@"documents"] count]==2 && [plan[@"items"][1][@"sharedWith"] count]==1,@"normalized links and shared song");
        NSDictionary *comparison=[engine compare:identifier node:@"A"];Check([comparison[@"ready"] boolValue] && [comparison[@"rows"] count]==2,@"only selected playlist documents planned");[engine receive:comparison progress:nil];NSData *normalized=YBReadPlaylist(target);
        Check([YBPlaylistNode(normalized,@"B")[@"raw"] isEqual:other],@"other playlist raw bytes remain identical");NSString *node=YBPlaylistNode(normalized,@"A")[@"raw"];Check([node containsString:root] && [node containsString:@"selectedArrangementID=\"arrangement\""],@"chosen Mac folder and arrangement retained");
        NSDictionary *song1=Document(plan,song);NSDictionary *song2=[web upload:edited path:song previous:song1];NSDictionary *latest=[engine manifest:identifier node:@"A"];Check([latest[@"library"][@"version"] isEqual:plan[@"library"][@"version"]] && ![latest[@"fingerprint"] isEqual:plan[@"fingerprint"]],@"song-only edit invalidates playlist plan without changing playlist version");
        comparison=[engine compare:identifier node:@"A"];Check(![comparison[@"orderChanged"] boolValue],@"song-only edit leaves normalized order unchanged");NSString *job=[engine receive:comparison progress:nil];Check([[library.sync readDocument:song] isEqual:edited] && [YBReadPlaylist(target) isEqual:normalized],@"playlist receive finds lyric-only change and applies it");[engine restoreJob:job];Check([[library.sync readDocument:song] isEqual:original] && [YBReadPlaylist(target) isEqual:normalized],@"batch restores document and playlist baseline");[engine receive:[engine compare:identifier node:@"A"] progress:nil];
        NSDictionary *stale=[engine compare:identifier node:@"A"];NSDictionary *song3=[web upload:Doc(@"concurrent web") path:song previous:song2];Reject(^{[engine receive:stale progress:nil];},@"server changed after comparison is blocked before apply");Check([[library.sync readDocument:song] isEqual:edited],@"stale attempt preserved local file");
        Put([root stringByAppendingPathComponent:sermon],Doc(@"local edit"));comparison=[engine compare:identifier node:@"A"];Check(![comparison[@"ready"] boolValue],@"local edits block batch instead of overwriting");Put([root stringByAppendingPathComponent:sermon],original);
        plan=[engine manifest:identifier node:@"A"];Patch(web,plan,@[@{@"id":@"H"},@{@"id":@"T"},@{@"id":@"S"}]);
        for(NSString *stage in @[@"prepared",@"document",@"playlist",@"baselines"]){
            comparison=[engine compare:identifier node:@"A"];engine.checkpoint=^(NSString *at){if([at isEqual:stage])YBRequire(NO,@"injected interruption");};Reject(^{[engine receive:comparison progress:nil];},[@"interruption " stringByAppendingString:stage]);engine.checkpoint=nil;
            Reject(^{[library.sync assertReady];},@"document tab cannot write while playlist batch is pending");
            NSString *pending=[engine jobs][0][@"id"];[library.sync close];library=[[YBLibrary alloc] initWithRoot:root profile:profile server:server];library.sync.presenterRunning=^BOOL{return NO;};engine=[[YBPlaylistSync alloc] initWithLibrary:library target:target];[engine restoreJob:pending];[library.sync assertReady];
            Check([[library.sync readDocument:song] isEqual:edited] && [YBReadPlaylist(target) isEqual:normalized],[@"restart recovers complete batch after " stringByAppendingString:stage]);
        }
        comparison=[engine compare:identifier node:@"A"];library.sync.checkpoint=^(NSString *at){if([at isEqual:@"replaced"])YBRequire(NO,@"file journal interruption");};Reject(^{[engine receive:comparison progress:nil];},@"in-flight per-document journal interruption");library.sync.checkpoint=nil;[engine restoreJob:[engine jobs][0][@"id"]];Check([[library.sync readDocument:song] isEqual:edited] && library.sync.pendingTransactions.count==0,@"recover file journal before playlist batch");
        [engine receive:[engine compare:identifier node:@"A"] progress:nil];Check([[library.sync readDocument:song] isEqual:Doc(@"concurrent web")],@"retry completes latest lyrics");NSArray *cues=YBPlaylistNode(YBReadPlaylist(target),@"A")[@"items"];Check([cues[1][@"attrs"][@"UUID"] isEqual:@"T"] && [cues[2][@"attrs"][@"UUID"] isEqual:@"S"],@"web order applied to Mac");Check([YBPlaylistNode(YBReadPlaylist(target),@"B")[@"raw"] isEqual:other],@"other playlist still untouched after recovery and reorder");
        // A second Mac can receive into an empty test playlist; the new document stays in its own chosen root.
        NSString *secondRoot=[area stringByAppendingPathComponent:@"second/documents"];YBLibrary *second=[[YBLibrary alloc] initWithRoot:secondRoot profile:[area stringByAppendingPathComponent:@"second/profile"] server:server];second.sync.presenterRunning=^BOOL{return NO;};NSURL *empty=[NSURL fileURLWithPath:[area stringByAppendingPathComponent:@"second/test.pro6pl"]];Put(empty.path,D(@"<RVPlaylistDocument><RVPlaylistNode UUID=\"ROOT2\"><array rvXMLIvarName=\"children\"/></RVPlaylistNode></RVPlaylistDocument>"));NSData *emptyBytes=YBReadPlaylist(empty);YBPlaylistSync *otherMac=[[YBPlaylistSync alloc] initWithLibrary:second target:empty];
        comparison=[otherMac compare:identifier node:@"A"];NSString *secondJob=[otherMac receive:comparison progress:nil];Check([[second.sync readDocument:song] isEqual:Doc(@"concurrent web")] && [YBPlaylistNode(YBReadPlaylist(empty),@"A")[@"raw"] containsString:secondRoot],@"new Mac downloads all referenced documents and inserts selected node");[otherMac restoreJob:secondJob];Check([YBReadPlaylist(empty) isEqual:emptyBytes] && ![second.sync readDocument:song],@"new files and inserted node removed by explicit restore");[second.sync close];
        // Removing a cue is distinct from deleting a document. A new cue gets its own UUID.
        plan=[engine manifest:identifier node:@"A"];Patch(web,plan,@[@{@"id":@"H"},@{@"id":@"S"},@{@"documentId":song3[@"id"]}]);[engine receive:[engine compare:identifier node:@"A"] progress:nil];Check([[library.sync readDocument:sermon] isEqual:original],@"removed cue does not delete document");plan=[engine manifest:identifier node:@"A"];Check([plan[@"items"] count]==3 && [plan[@"documents"] count]==1,@"reused song has distinct cues but one transfer");
        // A separate fresh Mac receives both nodes with one file replacement and one shared-document transfer.
        NSString *batchRoot=[area stringByAppendingPathComponent:@"batch-docs"],*batchProfile=[area stringByAppendingPathComponent:@"batch-profile"];YBLibrary *batchLibrary=[[YBLibrary alloc] initWithRoot:batchRoot profile:batchProfile server:server];batchLibrary.sync.presenterRunning=^BOOL{return NO;};NSURL *batchTarget=[NSURL fileURLWithPath:[area stringByAppendingPathComponent:@"batch-playlists/library.pro6pl"]];Put(batchTarget.path,emptyBytes);YBPlaylistSync *batchEngine=[[YBPlaylistSync alloc] initWithLibrary:batchLibrary target:batchTarget];
        NSArray *batchComparisons=@[[batchEngine compare:identifier node:@"A"],[batchEngine compare:identifier node:@"B"]];NSString *batchJob=[batchEngine receiveComparisons:batchComparisons progress:nil];Check(YBPlaylistNodes(YBReadPlaylist(batchTarget)).count==2,@"multi-playlist receive inserts both nodes into one file");Check([[batchLibrary.sync readDocument:song] isEqual:Doc(@"concurrent web")],@"shared document received in multi-playlist batch");Check([batchEngine jobs][0][@"rows"] && [[batchEngine jobs][0][@"rows"] count]==1,@"shared document transferred once");[batchEngine restoreJob:batchJob];Check([YBReadPlaylist(batchTarget) isEqual:emptyBytes] && ![batchLibrary.sync readDocument:song],@"multi-playlist backup restores all node baselines and new documents");[batchLibrary.sync close];
        NSDictionary *sameFile=[engine reconcileFileWithLibraries:[engine libraries]];Check([sameFile[@"status"] containsString:@"변경이 없습니다"],@"startup compares the last applied playlist without uploading normalized paths");
        NSString *localText=[[NSString alloc] initWithData:YBReadPlaylist(target) encoding:NSUTF8StringEncoding];NSString *editedText=[localText stringByReplacingOccurrencesOfString:@"주일 1부" withString:@"주일 오전"];Check(![editedText isEqual:localText],@"local playlist edit fixture");Put(target.path,D(editedText));
        NSNumber *oldVersion=plan[@"library"][@"version"];NSDictionary *sent=[engine reconcileFileWithLibraries:[engine libraries]];Check([sent[@"status"] containsString:@"서버 새 버전"] && [sent[@"libraries"][0][@"version"] integerValue]==oldVersion.integerValue+1,@"Mac-only playlist change uploads as a CAS version");
        plan=[engine manifest:identifier node:@"A"];Patch(web,plan,@[@{@"id":@"S"},@{@"id":@"H"},@{@"id":plan[@"items"][2][@"id"]}]);NSString *macText=[editedText stringByReplacingOccurrencesOfString:@"주일 오전" withString:@"주일 저녁"];Put(target.path,D(macText));
        NSDictionary *conflicted=[engine reconcileFileWithLibraries:[engine libraries]];Check([conflicted[@"status"] containsString:@"모두 바뀌었습니다"] && [YBReadPlaylist(target) isEqual:D(macText)],@"two-sided playlist changes never overwrite either side");

        // Explicit server selection is guarded by the exact reviewed local/server snapshot.
        comparison=[engine compare:identifier node:@"A"];Check(![comparison[@"ready"] boolValue],@"conflicted node requires explicit choice");
        NSString *serverChoiceJob=[engine receiveChoosingServer:comparison progress:nil];Check([[engine compare:identifier node:@"A"][@"ready"] boolValue],@"explicit server choice returns to normal comparison");[engine restoreJob:serverChoiceJob];Check([YBReadPlaylist(target) isEqual:D(macText)],@"explicit server choice has normal whole-batch undo");
        NSDictionary *staleChoice=[engine compare:identifier node:@"A"];Put(target.path,D([macText stringByReplacingOccurrencesOfString:@"주일 저녁" withString:@"after choice"]));Reject(^{[engine receiveChoosingServer:staleChoice progress:nil];},@"explicit server choice cannot overwrite a later local edit");Put(target.path,D(macText));
        // Choosing Mac backs up both sides, preserves other server nodes, and records exact baselines.
        comparison=[engine compare:identifier node:@"A"];NSDictionary *prepared=[engine prepareMacReset:comparison progress:nil];NSString *otherServer=YBPlaylistNode([server downloadPlaylist:prepared[@"library"]],@"B")[@"raw"];
        Put([root stringByAppendingPathComponent:song],Doc(@"edited after preflight"));Reject(^{[engine applyMacReset:prepared progress:nil];},@"reset rejects local changes after backup preview");Put([root stringByAppendingPathComponent:song],Doc(@"concurrent web"));
        prepared=[engine prepareMacReset:[engine compare:identifier node:@"A"] progress:nil];NSDictionary *chosen=[engine applyMacReset:prepared progress:nil];Check([chosen[@"status"] isEqual:@"complete"],@"selected Mac resolution completes");Check([YBPlaylistNode([server downloadPlaylist:chosen[@"savedLibrary"]],@"B")[@"raw"] isEqual:otherServer],@"selected Mac resolution preserves other server playlist bytes");
        comparison=[engine compare:identifier node:@"A"];Check([comparison[@"ready"] boolValue],@"selected Mac resolution establishes usable node and document baselines");
        // Full reset uploads unrelated local documents, keeps server-only documents, and is retryable.
        NSDictionary *serverOnly=[web upload:Doc(@"server only keep") path:@"server-only.pro6" previous:nil];
        NSDictionary *beforeExtra=[engine manifest:identifier node:@"A"][@"library"];NSData *extraXML=YBPlaylistReplacing([server downloadPlaylist:beforeExtra],@"SERVER-ONLY",@"<RVPlaylistNode UUID=\"SERVER-ONLY\" displayName=\"서버에만 보관\"><array rvXMLIvarName=\"children\"/></RVPlaylistNode>");[server request:[@"/api/playlists/" stringByAppendingString:identifier] method:@"PUT" body:extraXML headers:@{@"If-Match":[NSString stringWithFormat:@"\"%@\"",beforeExtra[@"version"]]}];
        prepared=[engine prepareMacReset:nil progress:nil];Check([prepared[@"serverOnlyPlaylists"] count]==1,@"full reset separately lists server-only playlists");Check([prepared[@"rows"] count]==3 && [prepared[@"serverOnly"] count]==1,@"full reset includes all local docs and separately lists server-only docs");
        engine.checkpoint=^(NSString *stage){if([stage isEqual:@"reset-document"])YBRequire(NO,@"injected reset interruption");};Reject(^{[engine applyMacReset:prepared progress:nil];},@"interrupted reset reports incomplete rather than success");engine.checkpoint=nil;
        NSString *resetPath=[NSString stringWithFormat:@"server-resets/%@/job.json",prepared[@"id"]];NSDictionary *interrupted=[NSJSONSerialization JSONObjectWithData:YBReadSafeFile(profile,resetPath,NULL) options:0 error:NULL];Check([interrupted[@"status"] isEqual:@"incomplete"] && [interrupted[@"completed"] count]==1,@"reset persists completed subset and backup location");
        prepared=[engine prepareMacReset:nil progress:nil];NSDictionary *reset=[engine applyMacReset:prepared progress:nil];Check([reset[@"status"] isEqual:@"complete"] && [reset[@"completed"] count]==3,@"fresh preflight resumes by reusing identical uploaded documents");Check([[server head:serverOnly][@"sha256"] isEqual:serverOnly[@"sha256"]],@"full reset never deletes server-only docs");Check(YBPlaylistNode([server downloadPlaylist:reset[@"savedLibrary"]],@"SERVER-ONLY")!=nil,@"full reset preserves server-only playlists pending user archive choice");
        NSString *backupDir=[@"server-resets/" stringByAppendingString:reset[@"id"]];Check(YBReadSafeFile(profile,[backupDir stringByAppendingString:@"/local.pro6pl"],NULL)!=nil && YBReadSafeFile(profile,[backupDir stringByAppendingString:@"/server.pro6pl"],NULL)!=nil && YBReadSafeFile(profile,[backupDir stringByAppendingString:@"/document-baselines.json"],NULL)!=nil,@"reset retains both playlists and old baselines");
        Check([[engine reconcileFileWithLibraries:[engine libraries]][@"status"] containsString:@"변경이 없습니다"],@"reset common file baseline prevents spurious automatic upload");
        prepared=[engine prepareMacReset:nil progress:nil];NSDictionary *oldSong=[server head:Document([engine manifest:identifier node:@"A"],song)];[web upload:Doc(@"web after reset preview") path:song previous:oldSong];Reject(^{[engine applyMacReset:prepared progress:nil];},@"reset CAS rejects a concurrent server document edit");
        // Missing references must never be reported as a completed playlist.
        NSString *bad=@"<RVPlaylistDocument><RVPlaylistNode><RVPlaylistNode UUID=\"M\" displayName=\"missing\"><RVDocumentCue UUID=\"X\" filePath=\"~/Documents/ProPresenter6/missing.pro6\"/></RVPlaylistNode></RVPlaylistNode></RVPlaylistDocument>";NSDictionary *badLibrary=[server request:@"/api/playlists?path=missing.pro6pl" method:@"POST" body:D(bad) headers:nil][@"library"];comparison=[engine compare:badLibrary[@"id"] node:@"M"];Check(![comparison[@"ready"] boolValue],@"missing document blocks completion");Reject(^{[engine receive:comparison progress:nil];},@"missing reference cannot apply");Reject(^{[engine receiveChoosingServer:comparison progress:nil];},@"explicit server choice still rejects missing references");
        library.sync.presenterRunning=^BOOL{return YES;};Reject(^{[engine receive:[engine compare:identifier node:@"A"] progress:nil];},@"PP6 running blocks batch");library.sync.presenterRunning=^BOOL{return NO;};
        [library.sync close];Check([area hasPrefix:[NSTemporaryDirectory() stringByAppendingPathComponent:@"yebaeon-playlist-tests-"]],@"cleanup scope");[NSFileManager.defaultManager removeItemAtPath:area error:NULL];printf("Playlist Worker checks passed: %d\n",checks);return 0;
    }@catch(NSException *e){fprintf(stderr,"PLAYLIST INTEGRATION FAIL after %d: %s\n",checks,e.reason.UTF8String);return 1;}
}}



