#import "YBServerPlaylistsController.h"
#import "YBPlaylistSync.h"
#import "YBPlaylistIO.h"
#import "YBPlaylistFormat.h"
@interface YBServerPlaylistsController () <NSTableViewDataSource,NSTableViewDelegate,NSSearchFieldDelegate>
@property(nonatomic,readwrite) NSView *view;
@property YBWork *work;
@property YBDocumentsController *documents;
@property NSURL *target;
@property NSTextField *rootLabel;
@property NSTextField *fileLabel;
@property NSTextField *status;
@property NSTableView *listTable;
@property NSSearchField *search;
@property NSArray *visibleChoices;
@property NSMutableDictionary *comparisons;
@property NSButton *receiveButton;
@property NSButton *registerButton;
@property NSTextField *summary;
@property NSTextField *versionLabel;
@property NSTableView *recoveryTable;
@property NSArray *recoveryRecords;
@property NSAlert *recoveryAlert;
@property NSTextView *recoveryDetails;
@property NSTableView *table;
@property NSArray *choices;
@property NSDictionary *comparison;
@end
@implementation YBServerPlaylistsController
- (instancetype)initWithWork:(YBWork *)work documents:(YBDocumentsController *)documents {
    if((self=[super init])){_work=work;_documents=documents;_choices=@[];id path=YBPreferences(@"server-playlists.json")[@"target"] ?: YBPreferences(@"playlist-settings.json")[@"localPath"];if([path isKindOfClass:NSString.class] && [path isAbsolutePath])_target=[NSURL fileURLWithPath:path];[self buildView];}return self;
}
- (void)buildView {
    NSView *v=[[NSView alloc] initWithFrame:NSMakeRect(0,0,1060,720)];self.view=v;self.comparisons=[NSMutableDictionary dictionary];self.visibleChoices=@[];
    self.rootLabel=YBLabel(@"",NSZeroRect,12,NO);self.fileLabel=YBLabel(@"",NSZeroRect,12,NO);
    [v addSubview:YBLabel(@"재생목록",NSMakeRect(24,670,280,28),22,YES)];[v addSubview:YBButton(@"다시 비교",NSMakeRect(881,666,155,34),self,@selector(refresh:))];
    self.search=[[NSSearchField alloc] initWithFrame:NSMakeRect(24,623,305,28)];self.search.placeholderString=@"재생목록 검색";self.search.delegate=self;[v addSubview:self.search];
    self.listTable=YBTable(v,NSMakeRect(24,163,305,448),@[@[@"name",@"재생목록",@130],@[@"status",@"상태",@100],@[@"date",@"바뀐 때",@60]],self);self.listTable.allowsMultipleSelection=NO;
    self.versionLabel=YBLabel(@"재생목록을 선택하세요.",NSMakeRect(349,625,687,25),13,YES);[v addSubview:self.versionLabel];
    self.table=YBTable(v,NSMakeRect(349,163,687,448),@[@[@"index",@"#",@38],@[@"name",@"곡 / 말씀",@175],@[@"status",@"받으면",@210],@[@"author",@"서버 저장 · 작업자",@245]],self);
    self.registerButton=YBButton(@"원본 재생목록 등록",NSMakeRect(60,385,238,36),self,@selector(publish:));self.registerButton.hidden=YES;[v addSubview:self.registerButton];
    self.summary=YBLabel(@"수정·새 문서를 먼저 적용한 뒤 선택한 예배의 순서만 교체합니다.",NSMakeRect(24,127,1012,26),12,NO);[v addSubview:self.summary];
    self.status=YBLabel(@"서버 연결 후 자동으로 순서와 연결 문서를 비교합니다.",NSMakeRect(24,94,1012,25),12,NO);[v addSubview:self.status];
    [v addSubview:YBButton(@"복구 기록…",NSMakeRect(24,35,150,36),self,@selector(restore:))];[v addSubview:YBButton(@"Studio 열기",NSMakeRect(187,35,145,36),self,@selector(openStudio:))];
    [v addSubview:YBLabel(@"PP6 종료 후 원본 백업 · Mac도 바뀌면 적용 차단",NSMakeRect(360,41,440,24),12,NO)];
    self.receiveButton=YBButton(@"선택한 예배 받기",NSMakeRect(806,35,230,36),self,@selector(receive:));self.receiveButton.keyEquivalent=@"\r";self.receiveButton.enabled=NO;[v addSubview:self.receiveButton];[self.documents setPlaylistFile:self.target];
}
- (NSString *)targetPath {return self.target.path ?: @"재생목록 파일 선택 필요";}
- (void)rootChanged {self.rootLabel.stringValue=self.documents.documentsRoot;[self.comparisons removeAllObjects];[self selectionChanged:nil];[self.documents setPlaylistFile:self.target];}
- (void)setTargetFile:(NSURL *)url {if(!url)return;@try{YBReadPlaylist(url);self.target=url;self.fileLabel.stringValue=url.path;YBSavePreferences(@"server-playlists.json",@{@"target":url.path});[self.documents setPlaylistFile:url];if(self.targetChanged)self.targetChanged(url.path);[self refresh:nil];}@catch(NSException *e){YBAlert(@"재생목록 파일",e.reason);}}
- (void)chooseFile:(id)sender {if(self.work.busy)return;NSOpenPanel *p=[NSOpenPanel openPanel];p.allowedFileTypes=@[@"pro6pl"];p.canChooseDirectories=NO;p.allowsMultipleSelection=NO;p.message=@"동기화할 PP6 재생목록 파일을 선택하세요.";if([p runModal]==NSModalResponseOK)[self setTargetFile:p.URL];}
- (YBPlaylistSync *)engine {YBRequire(self.target!=nil,@"재생목록 파일을 먼저 선택하세요.");[self.documents ensureSessionLoaded];return [[YBPlaylistSync alloc] initWithLibrary:[self.documents connectedLibrary] target:self.target];}
- (NSString *)choiceKey:(NSDictionary *)choice {return [NSString stringWithFormat:@"%@/%@",choice[@"library"],choice[@"node"]];}
- (NSString *)comparisonStatus:(NSDictionary *)value {if(!value)return @"미확인";if(value[@"error"])return @"확인 필요";if(![value[@"ready"] boolValue]){for(NSDictionary *r in value[@"rows"])if([@[@"upload",@"conflict"] containsObject:r[@"status"]])return @"Mac도 바뀜";return @"확인 필요";}if([value[@"orderChanged"] boolValue])return @"서버가 새로움";for(NSDictionary *r in value[@"rows"])if([r[@"status"] isEqual:@"download"])return @"서버가 새로움";return @"같음";}
- (void)acceptLibraries:(NSArray *)libraries {NSMutableArray *choices=[NSMutableArray array];for(NSDictionary *library in libraries)for(NSDictionary *node in library[@"playlists"])[choices addObject:@{@"library":library[@"id"],@"node":node[@"id"],@"name":node[@"name"],@"path":library[@"path"],@"date":library[@"updatedAt"] ?: @""}];self.choices=choices;self.registerButton.hidden=choices.count>0;[self filterChoices];}
- (void)filterChoices {NSString *query=self.search.stringValue.precomposedStringWithCanonicalMapping;NSMutableArray *visible=[NSMutableArray array];for(NSDictionary *choice in self.choices)if(!query.length || [choice[@"name"] rangeOfString:query options:NSCaseInsensitiveSearch].location!=NSNotFound)[visible addObject:choice];self.visibleChoices=visible;[self.listTable reloadData];if(visible.count)[self.listTable selectRowIndexes:[NSIndexSet indexSetWithIndex:0] byExtendingSelection:NO];else [self selectionChanged:nil];}
- (void)controlTextDidChange:(NSNotification *)note {[self filterChoices];}
- (void)refresh:(id)sender {
    if(self.work.busy)return;self.status.stringValue=@"서버 순서 비교 중…";self.receiveButton.enabled=NO;
    [self.work run:^id{[self.documents ensureSessionLoaded];YBPlaylistSync *engine=[[YBPlaylistSync alloc] initWithLibrary:[self.documents connectedLibrary] target:self.target];NSArray *libraries=[engine libraries];NSMutableDictionary *results=[NSMutableDictionary dictionary],*hashes=[NSMutableDictionary dictionary];NSUInteger total=0,done=0;for(NSDictionary *l in libraries)total+=[l[@"playlists"] count];for(NSDictionary *l in libraries)for(NSDictionary *n in l[@"playlists"]){NSString *key=[NSString stringWithFormat:@"%@/%@",l[@"id"],n[@"id"]];@try{results[key]=self.target ? [engine compare:l[@"id"] node:n[@"id"] hashCache:hashes] : @{@"error":@"Mac 재생목록 파일을 선택하세요."};}@catch(NSException *e){results[key]=@{@"error":e.reason ?: @"비교 실패"};}done++;NSString *message=[NSString stringWithFormat:@"재생목록 %lu/%lu 비교 · %@",(unsigned long)done,(unsigned long)total,n[@"name"]];dispatch_async(dispatch_get_main_queue(),^{self.status.stringValue=message;});}return @{@"libraries":libraries,@"comparisons":results};} completion:^(NSDictionary *result,NSString *error){if(error){self.status.stringValue=[@"비교 실패 · " stringByAppendingString:error];[self.comparisons removeAllObjects];self.comparison=nil;[self.table reloadData];return;}self.comparisons=[result[@"comparisons"] mutableCopy];[self acceptLibraries:result[@"libraries"]];[self.documents setPlaylistFile:self.target];if(!self.choices.count)self.status.stringValue=@"서버에 재생목록이 없습니다. 원본을 등록해 주세요.";}];
}
- (void)tableViewSelectionDidChange:(NSNotification *)note {if(note.object==self.listTable)[self selectionChanged:nil];else if(note.object==self.recoveryTable)[self recoverySelection];}
- (void)selectionChanged:(id)sender {NSInteger index=self.listTable.selectedRow;NSDictionary *choice=index>=0 && (NSUInteger)index<self.visibleChoices.count ? self.visibleChoices[index] : nil;NSDictionary *result=choice ? self.comparisons[[self choiceKey:choice]] : nil;if(result && !result[@"error"])[self acceptComparison:result];else {self.comparison=nil;[self.table reloadData];self.receiveButton.enabled=NO;self.status.stringValue=result[@"error"] ?: @"재생목록을 선택하세요.";self.versionLabel.stringValue=choice[@"name"] ?: @"재생목록";}}
- (void)publish:(id)sender {
    if(self.work.busy)return;if(!self.target){YBAlert(@"파일을 선택해 주세요.",@"Mac의 원본 .pro6pl 파일을 먼저 선택하세요.");return;}
    NSAlert *alert=[NSAlert new];alert.messageText=@"원본 재생목록과 연결 문서를 서버에 등록";alert.informativeText=[NSString stringWithFormat:@"%@\n\n아래는 재생목록이 원래 참조하던 문서 폴더입니다. 실제 업로드할 문서는 화면 위에서 선택한 문서 폴더에서 찾습니다. 서버와 다른 내용은 자동으로 덮어쓰지 않습니다.",self.target.path];NSTextField *root=[[NSTextField alloc] initWithFrame:NSMakeRect(0,0,560,30)];root.stringValue=@"~/Documents/ProPresenter6";alert.accessoryView=root;[alert addButtonWithTitle:@"서버에 등록"];[alert addButtonWithTitle:@"취소"];if([alert runModal]!=NSAlertFirstButtonReturn)return;NSString *source=root.stringValue;
    [self.work run:^id{YBPlaylistSync *engine=[self engine];NSDictionary *result=[engine registerFileWithSourceRoot:source progress:^(NSString *message){dispatch_async(dispatch_get_main_queue(),^{self.status.stringValue=message;});}];return @{@"result":result,@"libraries":[engine libraries]};} completion:^(NSDictionary *value,NSString *error){if(error){YBAlert(@"원본 등록",error);self.status.stringValue=@"등록을 마치지 못했습니다. 원본과 서버 이력은 유지합니다.";return;}[self acceptLibraries:value[@"libraries"]];[self refresh:nil];NSDictionary *result=value[@"result"];self.status.stringValue=[NSString stringWithFormat:@"재생목록 등록 · 문서 %@개 확인 · 누락/충돌 %lu개",result[@"count"],(unsigned long)[result[@"issues"] count]];if([result[@"issues"] count])YBShowText(@"아직 연결되지 않은 문서",[result[@"issues"] componentsJoinedByString:@"\n"]);}];
}
- (void)acceptComparison:(NSDictionary *)result {self.comparison=result;[self.table reloadData];NSUInteger changed=0,added=0;for(NSDictionary *r in result[@"rows"])if([r[@"status"] isEqual:@"download"]){if(r[@"localHash"]==NSNull.null)added++;else changed++;}NSDictionary *manifest=result[@"manifest"],*library=manifest[@"library"];self.versionLabel.stringValue=[NSString stringWithFormat:@"%@ · 파일 v%@ · %@",manifest[@"playlist"][@"name"],library[@"version"] ?: @"—",library[@"updatedBy"] ?: @"—"];self.versionLabel.toolTip=library[@"updatedAt"];
    self.summary.stringValue=[NSString stringWithFormat:@"① 수정 %lu개 받기 → ② 새 문서 %lu개 추가 → ③ 선택한 예배 순서 %@ · 다른 순서는 유지",(unsigned long)changed,(unsigned long)added,[result[@"orderChanged"] boolValue] ? @"교체" : @"유지"];
    self.status.stringValue=[result[@"ready"] boolValue] ? ((changed+added || [result[@"orderChanged"] boolValue]) ? @"공유 문서 변경은 함께 쓰는 다른 예배에도 반영됩니다." : @"서버와 같습니다.") : [result[@"issues"] componentsJoinedByString:@" · "];
    self.receiveButton.title=[NSString stringWithFormat:@"%@ 받기",manifest[@"playlist"][@"name"] ?: @"선택한 예배"];self.receiveButton.toolTip=self.receiveButton.title;self.receiveButton.enabled=[result[@"ready"] boolValue] && (changed+added || [result[@"orderChanged"] boolValue]) && !self.work.busy;
}
- (NSArray *)previewItems {NSMutableArray *items=[NSMutableArray arrayWithArray:self.comparison[@"manifest"][@"items"] ?: @[]];NSMutableSet *ids=[NSMutableSet set];for(NSDictionary *item in items)if(item[@"id"])[ids addObject:item[@"id"]];for(NSDictionary *old in self.comparison[@"localNode"][@"items"]){if(![old[@"tag"] isEqual:@"RVDocumentCue"] || [ids containsObject:old[@"attrs"][@"UUID"]])continue;[items addObject:@{@"name":old[@"attrs"][@"displayName"] ?: @"문서",@"kind":@"removed",@"path":old[@"attrs"][@"filePath"] ?: @""}];}return items;}
- (NSInteger)numberOfRowsInTableView:(NSTableView *)table {if(table==self.listTable)return self.visibleChoices.count;if(table==self.recoveryTable)return self.recoveryRecords.count;return self.previewItems.count;}
- (NSView *)tableView:(NSTableView *)table viewForTableColumn:(NSTableColumn *)column row:(NSInteger)index {
    NSString *text=@"",*tip=@"";NSColor *color=NSColor.labelColor;
    if(table==self.listTable){NSDictionary *choice=self.visibleChoices[index];NSString *state=[self comparisonStatus:self.comparisons[[self choiceKey:choice]]];text=[column.identifier isEqual:@"name"] ? choice[@"name"] : [column.identifier isEqual:@"status"] ? state : choice[@"date"];tip=[NSString stringWithFormat:@"%@ · %@",choice[@"path"],choice[@"date"]];if([column.identifier isEqual:@"date"] && text.length>=10)text=[text substringWithRange:NSMakeRange(5,5)];if([state isEqual:@"서버가 새로움"])color=[NSColor colorWithCalibratedRed:.18 green:.32 blue:.7 alpha:1];else if(![state isEqual:@"같음"])color=[NSColor colorWithCalibratedRed:.65 green:.3 blue:.1 alpha:1];}
    else if(table==self.recoveryTable){NSDictionary *record=self.recoveryRecords[index];text=record[column.identifier] ?: @"";tip=record[@"detail"];if([record[@"state"] isEqual:@"복구 필요"])color=[NSColor colorWithCalibratedRed:.7 green:.16 blue:.12 alpha:1];}
    else {NSDictionary *item=self.previewItems[index],*row=nil;for(NSDictionary *r in self.comparison[@"rows"])if([r[@"path"] isEqual:item[@"path"]])row=r;BOOL removed=[item[@"kind"] isEqual:@"removed"];
        if([column.identifier isEqual:@"index"])text=[NSString stringWithFormat:@"%ld",(long)index+1];else if([column.identifier isEqual:@"name"])text=item[@"name"];else if([column.identifier isEqual:@"status"]){text=removed ? @"순서에서 빠짐 · 파일 유지" : [item[@"kind"] isEqual:@"header"] ? @"구분" : [row[@"status"] isEqual:@"same"] ? @"그대로" : [row[@"status"] isEqual:@"download"] ? (row[@"localHash"]==NSNull.null ? @"새 문서 · 폴더에 추가" : @"내용 수정 · 문서 받기") : @"누락 / Mac 변경 확인";if([item[@"sharedWith"] count] && [row[@"status"] isEqual:@"download"])text=[text stringByAppendingFormat:@" · %lu곳",(unsigned long)[item[@"sharedWith"] count]+1];}else {NSDictionary *doc=row[@"remote"];text=[doc isKindOfClass:NSDictionary.class] ? [NSString stringWithFormat:@"%@ · %@",doc[@"updatedAt"] ?: @"—",doc[@"updatedBy"] ?: @"—"] : @"—";}tip=[item[@"path"] isKindOfClass:NSString.class] ? item[@"path"] : @"";if(removed)color=NSColor.secondaryLabelColor;
    }
    NSTextField *field=YBLabel(text ?: @"",NSMakeRect(0,2,column.width,24),12,NO);field.toolTip=tip.length ? tip : text;field.textColor=color;return field;
}
- (void)receive:(id)sender {
    if(self.work.busy)return;if(!self.receiveButton.enabled || ![self.comparison[@"ready"] boolValue]){YBAlert(@"먼저 순서를 비교해 주세요.",@"문서 누락/충돌을 해결한 뒤 다시 비교하면 받을 수 있습니다.");return;}NSDictionary *comparison=self.comparison;
    if(!YBConfirm(@"이 플레이리스트를 Mac에 적용할까요?",[NSString stringWithFormat:@"%@\n%@\n\n연결 문서를 먼저 백업·적용하고 선택한 순서를 반영합니다. 공유 문서 변경은 다른 예배에도 반영됩니다. PP6를 종료하세요.",comparison[@"manifest"][@"playlist"][@"name"],self.target.path],@"백업 후 동기화"))return;
    [self.work run:^id{return [[self engine] receive:comparison progress:^(NSString *message){dispatch_async(dispatch_get_main_queue(),^{self.status.stringValue=message;});}];} completion:^(NSString *identifier,NSString *error){self.comparison=nil;[self.table reloadData];if(error){self.status.stringValue=@"미완료 · 백업 / 중단 복구를 확인하세요.";YBAlert(@"플레이리스트 동기화 중단",error);}else{self.status.stringValue=@"플레이리스트와 문서 적용 완료 · PP6에서 같은 순서를 확인하세요.";NSString *warning=[self engine].library.sync.backupWarning;if(warning.length)YBAlert(@"동기화 완료 · 백업 정리 안내",warning);[self refresh:nil];}}];
}
- (NSArray *)recoveryRecordsForSync:(YBSync *)sync jobs:(NSArray *)jobs {
    NSArray *transactions=sync.transactions;NSMutableArray *records=[NSMutableArray array];NSMutableSet *owned=[NSMutableSet set];NSISO8601DateFormatter *iso=[NSISO8601DateFormatter new];NSDateFormatter *date=[NSDateFormatter new];date.dateFormat=@"MM-dd HH:mm";
    for(NSDictionary *job in jobs){NSMutableArray *members=[NSMutableArray array];for(NSDictionary *t in transactions)if([t[@"batchID"] isEqual:job[@"batchID"]] || [job[@"transactionIDs"] containsObject:t[@"id"]] || (!job[@"batchID"] && !job[@"transactionIDs"] && job[@"initialTransactions"] && ![job[@"initialTransactions"] containsObject:t[@"id"]])){[members addObject:t];[owned addObject:t[@"id"]];}NSString *state=[job[@"status"] isEqual:@"restored"] ? @"복구 완료" : [job[@"status"] isEqual:@"committed"] ? @"완료" : @"복구 필요";[records addObject:@{@"kind":@"playlist",@"data":job,@"members":members,@"at":job[@"createdAt"],@"time":[date stringFromDate:[NSDate dateWithTimeIntervalSince1970:[job[@"createdAt"] doubleValue]]],@"target":job[@"name"],@"summary":[NSString stringWithFormat:@"문서 %lu개와 순서",(unsigned long)members.count],@"state":state,@"detail":[NSString stringWithFormat:@"%@\n%@",job[@"target"] ?: @"",[[members valueForKey:@"path"] componentsJoinedByString:@"\n"]],@"canRestore":@(![job[@"status"] isEqual:@"restored"])}];}
    for(NSDictionary *batch in sync.backupBatches){if(![batch[@"kind"] isEqual:@"documents"] || [@[@"pruned",@"pruning"] containsObject:batch[@"status"]])continue;NSMutableArray *members=[NSMutableArray array],*names=[NSMutableArray array];NSUInteger active=0;for(NSDictionary *t in transactions)if([t[@"batchID"] isEqual:batch[@"id"]]){[members addObject:t];[names addObject:t[@"path"]];[owned addObject:t[@"id"]];if([@[@"prepared",@"applied",@"committed",@"restoring"] containsObject:t[@"status"]])active++;}NSString *state=!members.count ? @"적용 없음" : !active ? @"복구 완료" : [batch[@"status"] isEqual:@"complete"] ? @"완료" : @"복구 필요";[records addObject:@{@"kind":@"documents",@"data":batch,@"members":members,@"at":batch[@"createdAt"],@"time":[date stringFromDate:[NSDate dateWithTimeIntervalSince1970:[batch[@"createdAt"] doubleValue]]],@"target":@"문서 받기",@"summary":[NSString stringWithFormat:@"%lu개 문서",(unsigned long)members.count],@"state":state,@"detail":[names componentsJoinedByString:@"\n"],@"canRestore":@(active>0)}];}
    for(NSDictionary *t in transactions)if(![owned containsObject:t[@"id"]]){NSDate *created=[iso dateFromString:t[@"createdAt"]] ?: [NSDate dateWithTimeIntervalSince1970:0];BOOL active=[@[@"prepared",@"applied",@"committed",@"restoring"] containsObject:t[@"status"]];[records addObject:@{@"kind":@"legacy",@"data":t,@"members":@[t],@"at":@(created.timeIntervalSince1970),@"time":[date stringFromDate:created],@"target":t[@"path"],@"summary":@"개별 문서 · 구버전 기록",@"state":active ? ([t[@"status"] isEqual:@"committed"] ? @"완료" : @"복구 필요") : @"복구 완료",@"detail":t[@"path"],@"canRestore":@(active)}];}
    return [records sortedArrayUsingDescriptors:@[[NSSortDescriptor sortDescriptorWithKey:@"at" ascending:NO]]];
}
- (NSView *)recoveryView {NSView *view=[[NSView alloc] initWithFrame:NSMakeRect(0,0,840,380)];self.recoveryTable=YBTable(view,NSMakeRect(0,115,840,265),@[@[@"time",@"시각",@110],@[@"target",@"대상",@250],@[@"summary",@"한 일",@300],@[@"state",@"상태",@140]],self);self.recoveryTable.allowsMultipleSelection=NO;NSScrollView *details=[[NSScrollView alloc] initWithFrame:NSMakeRect(0,0,840,104)];details.hasVerticalScroller=YES;details.borderType=NSBezelBorder;self.recoveryDetails=[[NSTextView alloc] initWithFrame:details.bounds];self.recoveryDetails.editable=NO;self.recoveryDetails.font=[NSFont systemFontOfSize:12];self.recoveryDetails.verticallyResizable=YES;self.recoveryDetails.textContainer.widthTracksTextView=YES;self.recoveryDetails.autoresizingMask=NSViewWidthSizable;self.recoveryDetails.string=@"기록을 선택하면 포함 문서와 경로를 볼 수 있습니다.";details.documentView=self.recoveryDetails;[view addSubview:details];[self.recoveryTable reloadData];return view;}
- (void)recoverySelection {NSInteger i=self.recoveryTable.selectedRow;NSDictionary *r=i>=0 && (NSUInteger)i<self.recoveryRecords.count ? self.recoveryRecords[i] : nil;self.recoveryDetails.string=r[@"detail"] ?: @"기록을 선택하세요.";if(self.recoveryAlert.buttons.count)self.recoveryAlert.buttons[0].enabled=[r[@"canRestore"] boolValue];}
- (void)restore:(id)sender {
    if(self.work.busy)return;[self.work run:^id{YBLibrary *library=[self.documents connectedLibrary];YBPlaylistSync *engine=[[YBPlaylistSync alloc] initWithLibrary:library target:self.target];return [self recoveryRecordsForSync:library.sync jobs:engine.jobs];} completion:^(NSArray *records,NSString *error){if(error){YBAlert(@"복구 기록",error);return;}self.recoveryRecords=records;NSAlert *alert=[NSAlert new];self.recoveryAlert=alert;alert.messageText=@"이 Mac의 복구 기록";alert.informativeText=@"완료된 받기 작업 10회를 보관합니다. 중단·구버전 기록은 추가 보존합니다. 작업에서 바뀐 문서와 순서를 함께 되돌리며 새 문서는 제거합니다. 이후 따로 고친 파일은 덮어쓰지 않습니다. 서버 이력은 유지합니다.";alert.accessoryView=[self recoveryView];[alert addButtonWithTitle:@"이 작업 전으로 되돌리기"];[alert addButtonWithTitle:@"백업 폴더 열기"];[alert addButtonWithTitle:@"닫기"];alert.buttons[0].enabled=NO;if(records.count)[self.recoveryTable selectRowIndexes:[NSIndexSet indexSetWithIndex:0] byExtendingSelection:NO];NSModalResponse response=[alert runModal];NSInteger index=self.recoveryTable.selectedRow;self.recoveryAlert=nil;if(response==NSAlertSecondButtonReturn){[NSWorkspace.sharedWorkspace openURL:[NSURL fileURLWithPath:[self.documents connectedLibrary].sync.profile]];return;}if(response!=NSAlertFirstButtonReturn || index<0 || (NSUInteger)index>=records.count)return;NSDictionary *record=records[index];if(![record[@"canRestore"] boolValue])return;
        [self.work run:^id{YBLibrary *library=[self.documents connectedLibrary];NSDictionary *data=record[@"data"];if([record[@"kind"] isEqual:@"playlist"])[[[YBPlaylistSync alloc] initWithLibrary:library target:[NSURL fileURLWithPath:data[@"target"]]] restoreJob:data[@"id"]];else if([record[@"kind"] isEqual:@"documents"])[library.sync restoreBackupBatch:data[@"id"]];else if([data[@"status"] isEqual:@"committed"])[library.sync restore:data[@"id"]];else [library.sync recover:data[@"id"]];return @YES;} completion:^(id value,NSString *failure){self.comparison=nil;[self.comparisons removeAllObjects];[self.table reloadData];self.receiveButton.enabled=NO;self.status.stringValue=failure ? @"복구 미완료 · 현재 파일 유지 여부와 기록을 확인하세요." : @"작업 전으로 복구했습니다. 다시 비교하세요.";if(failure)YBAlert(@"복구 미완료",failure);else [self.documents refresh:nil];}];
    }];
}
- (void)openStudio:(id)sender {[NSWorkspace.sharedWorkspace openURL:[NSURL URLWithString:@"https://yebaeon.grace-jean-p.workers.dev/"]];}
@end

