(function(){'use strict';
 const P=window.PP6,R=window.PP6Render,H=window.YebaeonHistory,S=window.YebaeonSelection,$=id=>document.getElementById(id);
 const empty='<RVPresentationDocument width="1920" height="1080"><array rvXMLIvarName="groups"><RVSlideGrouping name="Blank"><array rvXMLIvarName="slides"><RVDisplaySlide UUID="EMPTY"><array rvXMLIvarName="displayElements"/></RVDisplaySlide></array></RVSlideGrouping></array></RVPresentationDocument>';
 let model=P.parse(empty,'문서를 선택하세요'),key='empty',selected=0,dirty=false,ready=false,serial=0,view='slides',reflowIndex=0;
 const cache=new Map(),library=new Map();
 const slides=()=>P.slides(model),current=()=>slides()[selected],groupOf=slide=>slide.parentNode.parentNode;
 const textOf=el=>P.parseRTF(P.textNode(el)?.textContent||'').text;
 const title=slide=>P.attr(slide,'label')||textOf(P.textElements(slide)[0]||slide).split('\n')[0]||'빈 슬라이드';
 const status=message=>{$('status').textContent=message;};
 const guarded=fn=>(...args)=>{try{const p=fn(...args);if(p?.catch)p.catch(e=>status(e.message));}catch(e){status(e.message);}};
 function changed(){dirty=true;serial++;window.dispatchEvent(new Event('yebaeonchange'));updateControls();}
 const state=()=>({xml:P.serialize(model),selected,dirty,serial,name:model.name});
 function snapshot(){H.push(key,state());changed();}
 function stash(){if(ready)cache.set(key,{...state(),name:model.name});}
 function open(xml,name,force=false,identity=name){
  const incoming=P.parse(xml,name);
  if(!force&&dirty&&!confirm('현재 변경은 브라우저 초안에 남습니다. 다른 문서를 열까요?'))return false;
  window.dispatchEvent(new Event('yebaeonbeforeopen'));stash();
  if(identity!==key)showView('slides');
  key=identity;model=incoming;selected=0;dirty=false;ready=true;serial++;library.clear();
  selection.chosen=new Set(['0']);selection.anchor='0';selection.cursor='0';render();window.dispatchEvent(new Event('yebaeonopen'));return true;
 }
 function unavailable(doc){
  window.dispatchEvent(new Event('yebaeonbeforeopen'));stash();model=P.parse(empty,doc.name);key=doc.id;selected=0;dirty=false;ready=false;serial++;library.clear();view='slides';
  selection.chosen.clear();selection.setKeys([]);$('inspector').hidden=true;$('reflowPane').hidden=true;$('slidePane').hidden=false;clearCanvases($('reflowRows'));$('texts').replaceChildren();
  document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='slides'));render();$('slideCount').textContent=doc.slideCount?doc.slideCount+'장 · 원본 미업로드':'원본 미업로드';$('emptyDocument').textContent='원본 미업로드 · 텍스트 편집과 미리보기를 사용할 수 없습니다. 재생목록 순서에는 넣을 수 있습니다.';
  window.dispatchEvent(new Event('yebaeonopen'));
 }
 function color(slide){const group=groupOf(slide),name=P.attr(group,'name').toLowerCase(),raw=P.attr(group,'color');if(raw)return P.color(raw);return /chorus|후렴/.test(name)?'#bf490b':/bridge|브릿지/.test(name)?'#7735d5':/blank|빈/.test(name)?'#737e93':'#3c57c9';}
 const selection=new S.Selection($('slidePane'),{onSelect:k=>{selected=Number(k);renderInspector();},onPaint:()=>{updateControls();window.dispatchEvent(new Event('yebaeonselection'));}});
 selection.options={...selection.options,kind:'slides',columns:()=>Math.max(1,Math.round($('slides').clientWidth/Math.max(1,$('slides').querySelector('.slide-card')?.clientWidth||240))),open:()=>quick(),remove:()=>remove(),copy:cut=>copy(cut),paste:()=>paste(),rename:()=>rename(),duplicate:()=>duplicate(),undo:redo=>undo(redo),menu:e=>context(e)};
 function updateControls(){const h=view!=='editor'&&S.active()?.options.kind==='order'&&window.YebaeonPlaylists?.historyState?window.YebaeonPlaylists.historyState():H.state(key);$('undo').disabled=!h.undo;$('redo').disabled=!h.redo;$('dirtyState').textContent=dirty?'저장 안 됨':'';$('templateOpen').disabled=!ready;$('add').disabled=!ready;$('resourceOpen').disabled=!ready;$('mediaOpen').disabled=false;$('templateOpen').title=selection.chosen.size?`템플릿 · 고른 ${selection.chosen.size}장에 적용`:'템플릿 · 모든 장에 적용';}
 const canvasData=new WeakMap();
 const canvasObserver=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{for(const entry of entries){const c=entry.target,data=canvasData.get(c);if(!data)continue;data.visible=entry.isIntersecting;if(data.visible&&c.isConnected){const resized=R.fit(c,data.model,data.width);if(!data.drawn||resized){data.drawn=true;data.draw();}}}},{rootMargin:'200px'}):null;
 const resizeObserver=typeof ResizeObserver==='function'?new ResizeObserver(entries=>{for(const {target:c} of entries){const data=canvasData.get(c);if(data?.visible&&c.isConnected&&R.fit(c,data.model,data.width))data.draw();}}):null;
 function clearCanvases(root){root.querySelectorAll('canvas').forEach(c=>{canvasObserver?.unobserve(c);resizeObserver?.unobserve(c);canvasData.delete(c);});root.replaceChildren();}
 function canvasFor(slide,width=400){const c=document.createElement('canvas');c.width=width;c.height=Math.round(width*model.height/model.width);const capturedModel=model,draw=()=>R.draw(c,capturedModel,slide,library).catch(e=>status(e.message));canvasData.set(c,{model:capturedModel,width,draw,visible:!canvasObserver,drawn:false});if(canvasObserver)canvasObserver.observe(c);else draw();resizeObserver?.observe(c);return c;}
 let gridColumns=6;try{gridColumns=Math.max(4,Math.min(8,Number(localStorage.getItem('yebaeon.gridColumns.v2'))||6));}catch(_){}
 function gridSize(value){gridColumns=Math.round(Math.max(4,Math.min(8,value)));$('slides').style.setProperty('--slide-columns',gridColumns);$('slideColumns').value=gridColumns;$('slideColumnsValue').textContent=gridColumns+'개';try{localStorage.setItem('yebaeon.gridColumns.v2',gridColumns);}catch(_){} }
 $('slideColumns').oninput=()=>gridSize(Number($('slideColumns').value));gridSize(gridColumns);
 function cards(){const root=$('slides');clearCanvases(root);if(!ready)return;for(const [i,slide] of slides().entries()){
   const card=document.createElement('div');card.className='slide-card';selection.bind(card,String(i));card.append(canvasFor(slide));const caption=document.createElement('div');caption.className='slide-caption';caption.style.background=color(slide);caption.textContent=`${i+1}. ${P.attr(slide,'label')||P.attr(groupOf(slide),'name','')}`;card.append(caption);card.title=title(slide);
   card.ondblclick=()=>setView('editor');card.oncontextmenu=e=>{if(!selection.chosen.has(String(i)))selection.select(String(i));context(e);};
   root.append(card);
  }selection.setKeys(slides().map((_,i)=>String(i)));selection.paint();}
 const dropMarker=document.createElement('div');dropMarker.className='slide-drop-marker';dropMarker.hidden=true;dropMarker.setAttribute('aria-hidden','true');const dropLabel=document.createElement('span');dropMarker.append(dropLabel);document.body.append(dropMarker);
 const slideDrag=()=>S.drag()?.pane===selection;
 // Insertion point between cards: the row under the pointer, then the gap nearest to it. Below the last row means the end.
 function dropPoint(x,y){const list=[...$('slides').querySelectorAll(':scope > .slide-card')];if(!list.length)return null;const boxes=list.map(c=>c.getBoundingClientRect()),gap=parseFloat(getComputedStyle($('slides')).columnGap)||8,rowGap=parseFloat(getComputedStyle($('slides')).rowGap)||8;
  const single=boxes.length>1&&boxes.every(b=>Math.abs(b.left-boxes[0].left)<2);
  if(single){let index=boxes.findIndex(b=>y<b.top+b.height/2);if(index<0)index=boxes.length;const b=boxes[Math.min(index,boxes.length-1)],top=index<boxes.length?b.top-rowGap/2:b.bottom+rowGap/2;return {index,line:{left:b.left,top:top-2,width:b.width,height:4}};}
  const rows=[];boxes.forEach((b,i)=>{const row=rows.find(r=>Math.abs(r.top-b.top)<2);if(row){row.items.push(i);row.bottom=Math.max(row.bottom,b.bottom);}else rows.push({top:b.top,bottom:b.bottom,items:[i]});});
  let row=rows.find(r=>y<r.bottom+rowGap/2)||rows.at(-1);if(y>rows.at(-1).bottom+rowGap/2)row=rows.at(-1);
  const after=y>rows.at(-1).bottom+rowGap/2;let index=after?boxes.length:row.items.find(i=>x<boxes[i].left+boxes[i].width/2);if(index===undefined)index=row.items.at(-1)+1;
  const anchor=index<boxes.length&&row.items.includes(index)?boxes[index]:boxes[index-1],left=index<boxes.length&&row.items.includes(index)?anchor.left-gap/2:anchor.right+gap/2;
  return {index,line:{left:left-2,top:anchor.top,width:4,height:anchor.height}};}
 function clearDrop(){dropMarker.hidden=true;$('mediaDropAll').hidden=true;$('mediaDropAll').classList.remove('over');$('slides').querySelectorAll('.drop-media,.dragging').forEach(c=>c.classList.remove('drop-media','dragging'));}
 $('slidePane').addEventListener('dragstart',e=>{if(!e.target.closest?.('.slide-card'))return;queueMicrotask(()=>{if(!slideDrag())return;for(const k of selection.chosen)$('slides').querySelector(`[data-key="${k}"]`)?.classList.add('dragging');});});
 $('slidePane').addEventListener('dragover',e=>{if(!ready)return;const media=window.YebaeonResources?.draggedMedia();if(media){const card=e.target.closest('.slide-card'),all=e.target.closest('#mediaDropAll'),zone=$('mediaDropAll');zone.hidden=false;zone.textContent=`여기에 놓으면 모든 장(${slides().length}장)에 배경`;zone.classList.toggle('over',!!all);const keys=new Set(all?slides().map((_,i)=>String(i)):card?backgroundTargets(Number(card.dataset.key)).map(String):[]);$('slides').querySelectorAll('.slide-card').forEach(c=>c.classList.toggle('drop-media',keys.has(c.dataset.key)));if(card||all)e.preventDefault();return;}
  if(!slideDrag())return;const point=dropPoint(e.clientX,e.clientY);if(!point)return;e.preventDefault();e.dataTransfer.dropEffect='move';showDrop(point,S.drag().keys.map(Number));});
 function showDrop(point,moved){if(!point){dropMarker.hidden=true;return;}const left=Math.max(2,Math.min(innerWidth-point.line.width-2,point.line.left));dropMarker.classList.toggle('edge-left',left<40);dropMarker.classList.toggle('edge-right',left>innerWidth-40);Object.assign(dropMarker.style,{left:left+'px',top:point.line.top+'px',width:point.line.width+'px',height:point.line.height+'px'});dropLabel.textContent=(point.index-moved.filter(i=>i<point.index).length+1)+'번으로';dropMarker.hidden=false;}
 const clearMediaDrop=()=>{dropMarker.hidden=true;$('mediaDropAll').hidden=true;$('mediaDropAll').classList.remove('over');$('slides').querySelectorAll('.drop-media').forEach(c=>c.classList.remove('drop-media'));};$('slidePane').addEventListener('dragleave',e=>{if(!$('slidePane').contains(e.relatedTarget))clearMediaDrop();});document.addEventListener('dragend',clearMediaDrop);
 $('slidePane').addEventListener('drop',guarded(e=>{const media=window.YebaeonResources?.draggedMedia(),card=e.target.closest('.slide-card'),drag=S.drag();clearDrop();if(!ready)return;if(media){if(e.target.closest('#mediaDropAll')){e.preventDefault();setBackground(media.source,'all');}else if(card){e.preventDefault();setBackground(media.source,Number(card.dataset.key));}return;}if(drag?.pane!==selection)return;e.preventDefault();const point=dropPoint(e.clientX,e.clientY);if(point)reorder(drag.keys.map(Number),point.index);}));
 document.addEventListener('dragend',clearDrop);
 // Touch: hold a card briefly to pick it up, then drag; a quick swipe still scrolls. Holding without moving opens the slide menu.
 const touchGhost=document.createElement('div');touchGhost.className='slide-touch-ghost';touchGhost.hidden=true;touchGhost.setAttribute('aria-hidden','true');document.body.append(touchGhost);
 let touchDrag=null,touchFrame=0,suppressTouchClick=0;
 function endTouch(){if(!touchDrag)return;clearTimeout(touchDrag.timer);cancelAnimationFrame(touchFrame);touchFrame=0;if(touchDrag.active){suppressTouchClick=Date.now()+450;try{touchDrag.card.releasePointerCapture(touchDrag.id);}catch(_){}}touchDrag=null;touchGhost.hidden=true;clearDrop();document.body.classList.remove('slide-touch-dragging');}
 function touchPaint(){const t=touchDrag;if(!t?.active)return;Object.assign(touchGhost.style,{left:Math.max(56,Math.min(innerWidth-56,t.x))+'px',top:Math.max(48,t.y)+'px'});t.point=t.moved?dropPoint(t.x,t.y):null;showDrop(t.point,t.keys);}
 function touchTick(){touchFrame=0;const t=touchDrag;if(!t?.active)return;const pane=$('slidePane'),box=pane.getBoundingClientRect(),edge=48;let dy=0,dx=0;
  if(t.y<box.top+edge)dy=-Math.ceil((box.top+edge-t.y)/4);else if(t.y>box.bottom-edge)dy=Math.ceil((t.y-box.bottom+edge)/4);
  if(pane.scrollWidth>pane.clientWidth+1){if(t.x<box.left+edge)dx=-Math.ceil((box.left+edge-t.x)/4);else if(t.x>box.right-edge)dx=Math.ceil((t.x-box.right+edge)/4);}
  if(dy)pane.scrollTop+=dy;if(dx)pane.scrollLeft+=dx;if(dx||dy)touchPaint();touchFrame=requestAnimationFrame(touchTick);}
 function beginTouch(){const t=touchDrag;if(!t||!t.card.isConnected){endTouch();return;}const key=t.card.dataset.key;if(!selection.chosen.has(key))selection.select(key);t.keys=selection.values().map(Number);t.active=true;
  try{t.card.setPointerCapture(t.id);}catch(_){}for(const k of t.keys)$('slides').querySelector(`[data-key="${k}"]`)?.classList.add('dragging');
  touchGhost.textContent=t.keys.length>1?t.keys.length+'장 이동':(t.keys[0]+1)+'번 이동';touchGhost.hidden=false;document.body.classList.add('slide-touch-dragging');navigator.vibrate?.(12);touchPaint();touchFrame=requestAnimationFrame(touchTick);}
 $('slidePane').addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||!e.isPrimary||!ready||$('slidePane').hidden)return;const card=e.target.closest('.slide-card');endTouch();if(!card)return;touchDrag={id:e.pointerId,card,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,active:false,moved:false,keys:[],point:null,timer:setTimeout(beginTouch,300)};});
 window.addEventListener('pointermove',e=>{const t=touchDrag;if(!t||e.pointerId!==t.id)return;t.x=e.clientX;t.y=e.clientY;const distance=Math.hypot(t.x-t.startX,t.y-t.startY);if(!t.active){if(distance>8)endTouch();return;}if(distance>10)t.moved=true;touchPaint();},{passive:true});
 $('slidePane').addEventListener('touchmove',e=>{if(touchDrag?.active)e.preventDefault();},{passive:false});
 window.addEventListener('pointerup',guarded(e=>{const t=touchDrag;if(!t||e.pointerId!==t.id)return;const {active,moved,point,keys,x,y}=t;endTouch();if(!active)return;if(!moved){context({preventDefault(){},clientX:x,clientY:y,target:$('slidePane')});return;}if(point)reorder(keys,point.index);}));
 window.addEventListener('pointercancel',e=>{if(touchDrag?.id===e.pointerId)endTouch();});
 window.addEventListener('contextmenu',e=>{if(touchDrag&&e.target.closest?.('#slidePane')){e.preventDefault();e.stopImmediatePropagation();}},true);
 window.addEventListener('dragstart',e=>{if(touchDrag&&e.target.closest?.('#slidePane'))e.preventDefault();},true);
 window.addEventListener('click',e=>{if(Date.now()<suppressTouchClick&&e.target.closest?.('#slidePane')){e.preventDefault();e.stopImmediatePropagation();}},true);
 $('slidePane').addEventListener('click',e=>{if(!ready||e.target.closest('.slide-card')||e.ctrlKey||e.metaKey||e.shiftKey)return;if(selection.chosen.size)selection.clear();});
 function renderInspector(){if(!ready)return;const slide=current();$('label').value=P.attr(slide,'label');$('slidePosition').textContent=`${selected+1}/${slides().length}`;$('texts').replaceChildren();
  P.textElements(slide).forEach((element,i)=>{const field=document.createElement('label');field.textContent=P.attr(element,'displayName')||`텍스트 ${i+1}`;const input=document.createElement('textarea');input.value=textOf(element);let transaction=false;input.onfocus=()=>transaction=false;input.oninput=guarded(()=>{if(!transaction){snapshot();transaction=true;}else changed();P.setText(element,input.value);refreshThumbnails();});field.append(input);$('texts').append(field);});
  $('group').replaceChildren();P.all(model.doc,'RVSlideGrouping').forEach((group,i)=>{const o=new Option(P.attr(group,'name','그룹'),i);o.selected=group===groupOf(slide);$('group').add(o);});
  $('fonts').textContent=PP6Fonts.descriptions(slide).join(' · ');window.dispatchEvent(new Event('yebaeonselection'));
 }
 let redrawTimer;
 const changedThumbnails=new Set();let redrawAll=false;
 function refreshThumbnails(all=false){changedThumbnails.add(selected);redrawAll=redrawAll||all;clearTimeout(redrawTimer);redrawTimer=setTimeout(()=>{if(redrawAll){for(const c of $('slides').querySelectorAll('canvas')){const data=canvasData.get(c);if(data?.visible)data.draw();else if(data)data.drawn=false;}}else{const seq=slides();for(const i of changedThumbnails){const card=$('slides').children[i],canvas=card?.querySelector('canvas');if(canvas&&seq[i]){R.draw(canvas,model,seq[i],library).catch(e=>status(e.message));card.title=title(seq[i]);}}}changedThumbnails.clear();redrawAll=false;if(view==='editor')window.YebaeonLayout?.paint();},100);}
 function render(){selected=Math.max(0,Math.min(selected,slides().length-1));selection.cursor=String(selected);$('docTitle').textContent=model.name.replace(/\.pro6$/i,'');$('slideCount').textContent=ready?slides().length+'장':'';$('emptyDocument').hidden=ready;cards();renderInspector();if(view==='reflow')renderReflow();updateControls();window.dispatchEvent(new Event('yebaeonrender'));}
 function toggleView(value){const overlay=!$('biblePanel').hidden||!$('mediaDrawer').hidden;window.YebaeonResources?.closeBible();$('mediaDrawer').hidden=true;setView(!overlay&&view===value?'slides':value);}
 function showView(value){view=value;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===value));$('reflowPane').hidden=value!=='reflow';$('slidePane').hidden=value==='reflow';$('inspector').hidden=value!=='editor';}
 function setView(value){if(!ready)return;showView(value);render();if(value==='editor')window.YebaeonLayout?.focus();if(value==='reflow')$('reflowRows').querySelector(`[data-index="${selected}"] textarea`)?.focus();}
 function undo(redo=false){if(!ready)return;const previous=H.step(key,state(),redo);if(!previous)return;model=P.parse(previous.xml,model.name);selected=previous.selected;selection.chosen=new Set([String(selected)]);changed();render();status(redo?'다시 실행했습니다.':'실행취소했습니다.');}
 function add(){if(!ready)return;const copy=current().cloneNode(true);if(!P.textElements(copy).length)throw new Error('텍스트 상자가 있는 슬라이드를 선택하세요.');if(slides().length>=1000)throw new Error('문서는 1,000장까지 지원합니다.');snapshot();const slide=P.duplicate(current(),true);selected=slides().indexOf(slide);selection.chosen=new Set([String(selected)]);render();quick();}
 function duplicate(){if(!ready)return;const indices=selection.chosen.size?selection.values().map(Number):[selected];if(slides().length+indices.length>1000)throw new Error('문서는 1,000장까지 지원합니다.');snapshot();const seq=slides();let after=seq[indices.at(-1)];const copies=indices.map(i=>{const copy=seq[i].cloneNode(true);P.refreshIDs(copy);P.ivar(copy,'array','cues')?.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])copy.setAttribute(k,'');after.parentNode.insertBefore(copy,after.nextSibling);after=copy;return copy;});selection.chosen=new Set(copies.map(c=>String(slides().indexOf(c))));selected=slides().indexOf(copies[0]);render();status(copies.length>1?`슬라이드 ${copies.length}장을 복제했습니다.`:'슬라이드를 복제했습니다.');}
 function remove(){const indices=selection.values().map(Number);if(!indices.length)return;if(indices.length>=slides().length)throw new Error('문서에 한 장은 남겨 주세요.');snapshot();const seq=slides();indices.forEach(i=>seq[i].remove());selected=Math.min(selected,slides().length-1);selection.chosen=new Set([String(selected)]);render();}
 function copy(cut=false){const indices=selection.values().map(Number);if(!indices.length)return;S.copy({kind:'slides',width:model.width,height:model.height,xml:indices.map(i=>new XMLSerializer().serializeToString(slides()[i])),cut,key,indices,serial});if(cut){if(indices.length>=slides().length)throw new Error('문서에 한 장은 남겨 주세요.');const clip=S.clipboard();remove();S.copy({...clip,cut:false});status('슬라이드를 잘라냈습니다. 붙여넣거나 실행취소할 수 있습니다.');}else status('슬라이드를 복사했습니다.');}
 function paste(){const clip=S.clipboard();if(clip?.kind!=='slides')return;if(clip.width!==model.width||clip.height!==model.height)throw new Error('크기가 같은 문서에 붙여 넣어 주세요.');if(clip.cut&&clip.key!==key)throw new Error('문서 간 잘라내기는 지원하지 않습니다. 복사해서 붙여 넣어 주세요.');if(clip.cut&&clip.serial!==serial)throw new Error('잘라낸 뒤 문서가 바뀌었습니다. 다시 선택하세요.');if(clip.cut){reorder(clip.indices,selected+1);S.copy({...clip,cut:false});return;}if(slides().length+clip.xml.length>1000)throw new Error('문서는 1,000장까지 지원합니다.');const copies=clip.xml.map(xml=>{const doc=new DOMParser().parseFromString(xml,'application/xml');const slide=model.doc.importNode(doc.documentElement,true);P.refreshIDs(slide);const cues=P.ivar(slide,'array','cues');if(cues)cues.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])slide.setAttribute(k,'');return slide;});snapshot();let after=current();for(const slide of copies){after.parentNode.insertBefore(slide,after.nextSibling);after=slide;}selection.chosen=new Set(copies.map(s=>String(slides().indexOf(s))));selected=slides().indexOf(copies[0]);render();}
 function reorder(indices,targetIndex){const seq=slides(),members=indices.map(i=>seq[i]);if(!members.length)return;const kept=seq.filter(s=>!members.includes(s)),before=seq.slice(0,targetIndex).filter(s=>!members.includes(s)).length,next=[...kept.slice(0,before),...members,...kept.slice(before)];if(next.every((s,i)=>s===seq[i]))return;const target=kept[before],parent=target?.parentNode||seq.at(-1).parentNode;snapshot();members.forEach(s=>parent.insertBefore(s,target||null));selection.chosen=new Set(members.map(s=>String(slides().indexOf(s))));selected=slides().indexOf(members[0]);render();}
 function rename(){if(!ready)return;const name=prompt('슬라이드 이름',P.attr(current(),'label'));if(name===null||name===P.attr(current(),'label'))return;snapshot();current().setAttribute('label',name);render();}
 function split(index,offset){const slide=slides()[index],box=P.textElements(slide)[0];if(!box)throw new Error('첫 번째 글상자가 없습니다.');const text=textOf(box);if(offset<=0||offset>=text.length)throw new Error('나눌 글 사이에 커서를 놓으세요.');if(slides().length>=1000)throw new Error('문서는 1,000장까지 지원합니다.');snapshot();const copy=P.duplicate(slide);const parsed=P.parseRTF(P.textNode(box).textContent);P.setRuns(box,P.sliceRuns(parsed.runs,0,offset),parsed.emptyStyle);P.setRuns(P.textElements(copy)[0],P.sliceRuns(parsed.runs,offset,text.length),parsed.emptyStyle);selected=slides().indexOf(copy);selection.chosen=new Set([String(selected)]);render();if(view==='reflow'){const input=$('reflowRows').querySelector(`[data-index="${selected}"] textarea`);input?.focus();input?.setSelectionRange(0,0);}}
 function merge(index){if(index<=0)return;const seq=slides(),a=P.textElements(seq[index-1])[0],b=P.textElements(seq[index])[0];if(!a||!b)throw new Error('두 장 모두 첫 번째 글상자가 필요합니다.');snapshot();const pa=P.parseRTF(P.textNode(a).textContent),pb=P.parseRTF(P.textNode(b).textContent);P.setRuns(a,[...pa.runs,{text:'\n',style:pa.runs.at(-1)?.style||pa.emptyStyle},...pb.runs],pa.emptyStyle);seq[index].remove();selected=index-1;selection.chosen=new Set([String(selected)]);render();}
 function renderReflow(){const root=$('reflowRows');clearCanvases(root);slides().forEach((slide,index)=>{const row=document.createElement('div');row.className='reflow-row';row.dataset.index=index;row.style.borderLeftColor=color(slide);const body=document.createElement('div'),head=document.createElement('div');head.className='reflow-heading';head.textContent=`${index+1}. ${P.attr(groupOf(slide),'name')}`;const groups=document.createElement('select');groups.setAttribute('aria-label',`${index+1}번 그룹`);P.all(model.doc,'RVSlideGrouping').forEach((g,i)=>{const o=new Option(P.attr(g,'name'),i);o.selected=g===groupOf(slide);groups.add(o);});groups.onchange=()=>moveGroup([index],Number(groups.value));head.append(groups);const input=document.createElement('textarea');const box=P.textElements(slide)[0];input.value=box?textOf(box):'';input.disabled=!box;input.setAttribute('aria-label',`${index+1}번 본문`);let transaction=false;input.onfocus=()=>{reflowIndex=index;selected=index;transaction=false;root.querySelectorAll('.active').forEach(e=>e.classList.remove('active'));row.classList.add('active');};input.oninput=guarded(()=>{if(!transaction){snapshot();transaction=true;}else changed();P.setText(box,input.value);const canvas=row.querySelector('canvas');R.draw(canvas,model,slide,library);});input.onkeydown=guarded(e=>{if(e.isComposing)return;if(e.code==='Enter'&&window.YebaeonKeys?.leftAlt()){e.preventDefault();split(index,input.selectionStart);}else if(e.code==='Backspace'&&input.selectionStart===0&&input.selectionEnd===0&&index>0){e.preventDefault();merge(index);}});body.append(head,input);row.append(body,canvasFor(slide,300));root.append(row);});}
 function moveGroup(indices,groupIndex){const group=P.all(model.doc,'RVSlideGrouping')[groupIndex];if(!group)return;const members=indices.map(i=>slides()[i]);snapshot();let container=P.ivar(group,'array','slides');if(!container){container=model.doc.createElement('array');container.setAttribute('rvXMLIvarName','slides');group.append(container);}members.forEach(s=>container.append(s));selected=slides().indexOf(members[0]);selection.chosen=new Set(members.map(s=>String(slides().indexOf(s))));render();}
 async function quick(){if(!ready)return;if(!$('quickDialog').open){if(window.YebaeonResponsive?.compact())$('quickDialog').show();else $('quickDialog').showModal();}await renderQuick();}
 let quickGeneration=0;
 async function renderQuick(){const token=++quickGeneration,slide=current();$('quickTitle').textContent=`빠른 편집 · ${selected+1}. ${title(slide)}`;$('quickPrevious').disabled=selected===0;$('quickNext').disabled=selected===slides().length-1;const canvas=$('quickCanvas');R.fit(canvas,model,640);const warnings=await R.draw(canvas,model,slide,library);if(token!==quickGeneration||!$('quickDialog').open)return;$('quickWarnings').textContent=warnings.join(' · ');$('quickInputs').replaceChildren();
  P.textElements(slide).forEach((box,i)=>{const parsed=P.parseRTF(P.textNode(box)?.textContent||''),field=document.createElement('label');field.textContent=P.attr(box,'displayName')||`텍스트 ${i+1}`;const input=document.createElement('textarea');input.value=parsed.text;input.setAttribute('aria-label',`텍스트 ${i+1}`);let transaction=false,timer;input.onfocus=()=>transaction=false;input.oninput=guarded(()=>{if(!transaction){snapshot();transaction=true;}else changed();P.setText(box,input.value);refreshThumbnails();clearTimeout(timer);timer=setTimeout(async()=>{if(token!==quickGeneration||!$('quickDialog').open)return;R.fit(canvas,model,640);const messages=await R.draw(canvas,model,slide,library);if(token===quickGeneration)$('quickWarnings').textContent=messages.join(' · ');},80);});field.append(input);$('quickInputs').append(field);});$('quickInputs').querySelector('textarea')?.focus();}
 function templateSlide(template){if(template.width!==model.width||template.height!==model.height)throw new Error(`템플릿은 ${template.width}×${template.height}입니다. 같은 크기의 문서를 선택하세요.`);const doc=new DOMParser().parseFromString(template.xml,'application/xml');if(doc.querySelector('parsererror')||doc.documentElement.tagName!=='RVDisplaySlide')throw new Error('템플릿 형식 오류');const slide=model.doc.importNode(doc.documentElement,true);P.refreshIDs(slide);P.ivar(slide,'array','cues')?.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])slide.setAttribute(k,'');return slide;}
 function applyTemplate(template){const indices=selection.chosen.size?selection.values().map(Number):slides().map((_,i)=>i);const prepared=indices.map(i=>{const old=slides()[i],copy=templateSlide(template),values=P.textElements(old).map(textOf),boxes=P.textElements(copy);if(boxes.length<values.length)throw new Error('기존 글상자보다 적은 템플릿입니다. 글을 먼저 정리해 주세요.');boxes.forEach((b,n)=>P.setText(b,values[n]||''));copy.setAttribute('label',P.attr(old,'label'));return {old,copy};});snapshot();prepared.forEach(({old,copy})=>old.replaceWith(copy));render();status(`${prepared.length}장에 템플릿을 적용했습니다.`);}
 function bibleSlide(value,template){if(!template)throw new Error('말씀 템플릿을 선택하세요.');const slide=templateSlide(template);P.refreshIDs(slide);P.ivar(slide,'array','cues')?.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])slide.setAttribute(k,'');const boxes=P.textElements(slide);if(boxes.length<2)throw new Error('본문과 장절 글상자가 있는 템플릿을 선택하세요.');boxes.forEach((box,i)=>P.setText(box,i===0?value.text:i===1?value.reference:''));slide.setAttribute('label',value.reference+' (NKRV)');return slide;}
 function addBible(values,template){if(!values.length||slides().length+values.length>1000)throw new Error('전체 1,000장 이내에서 추가하세요.');const copies=values.map(v=>bibleSlide(v,template));snapshot();let after=current();copies.forEach(s=>{after.parentNode.insertBefore(s,after.nextSibling);after=s;});selected=slides().indexOf(copies[0]);selection.chosen=new Set(copies.map(s=>String(slides().indexOf(s))));render();status(`말씀 ${copies.length}장을 추가했습니다.`);}
 // 배경 그림 요소는 PP6가 저장하는 모양 그대로(PP6.imageElementXML). 위치 {0 0 0 0 0}은 화면 전체를 뜻한다.
 const backgroundName=source=>{let path=String(source);try{if(path.startsWith('file:'))path=decodeURIComponent(new URL(path).pathname);}catch{}return path.split('/').pop().replace(/\.[^.]+$/,'').normalize('NFC');};
 function backgroundElement(){const x=new DOMParser().parseFromString(P.imageElementXML({source:'',scale:'1',background:true}),'application/xml').documentElement;return model.doc.importNode(x,true);}
 // 배경 그림을 씌운다. target은 장 번호 하나, 번호 배열, 'all'(모든 장). 없으면 고른 장(없으면 지금 장). 실행취소 한 번에 모두 되돌린다.
 function backgroundTargets(target){if(target==='all')return slides().map((_,i)=>i);if(Array.isArray(target))return target;if(Number.isInteger(target)){const chosen=selection.values().map(Number);return chosen.length>1&&chosen.includes(target)?chosen:[target];}const chosen=selection.values().map(Number);return chosen.length?chosen:[selected];}
 function setBackground(source,target){const indices=backgroundTargets(target).filter(i=>slides()[i]);if(!indices.length)return;snapshot();for(const index of indices){const slide=slides()[index];const name=backgroundName(source);let cue=P.ivar(slide,'RVMediaCue','backgroundMediaCue');if(!cue){cue=model.doc.createElement('RVMediaCue');for(const [k,v] of Object.entries({UUID:P.uuid(),actionType:'0',alignment:'4',behavior:'2',dateAdded:'',delayTime:'0.000000',displayName:name,enabled:'false',nextCueUUID:'',rvXMLIvarName:'backgroundMediaCue',tags:'',timeStamp:'0.000000'}))cue.setAttribute(k,v);slide.insertBefore(cue,P.ivar(slide,'array','displayElements'));}let media=P.mediaElements(cue)[0];if(!media||media.tagName!=='RVImageElement'){cue.replaceChildren(backgroundElement());media=P.mediaElements(cue)[0];}cue.setAttribute('displayName',name);media.setAttribute('format',/\.jpe?g$/i.test(source)?'JPEG 이미지':'PNG 이미지');media.setAttribute('source',source);}render();status(indices.length>1?`배경을 ${indices.length}장에 적용했습니다.`:'배경을 적용했습니다.');}
 // 배경 그림(backgroundMediaCue의 그림)과 맞춤. PP6 scaleBehavior: 0=맞추기, 1=채우기, 3=늘이기(10-05 교회 PP6에서 확인). 2는 뜻을 모른다.
 const SCALE={fit:'0',fill:'1',stretch:'3'};
 function backgroundImage(slide){const cue=P.ivar(slide,'RVMediaCue','backgroundMediaCue');return cue?P.mediaElements(cue).find(m=>m.tagName==='RVImageElement')||null:null;}
 function backgroundScale(mode,target){const indices=backgroundTargets(target).filter(i=>slides()[i]&&backgroundImage(slides()[i]));if(!indices.length)return;snapshot();for(const i of indices)backgroundImage(slides()[i]).setAttribute('scaleBehavior',SCALE[mode]);render();status(`배경 ${({fit:'맞추기',fill:'채우기',stretch:'늘이기'})[mode]} · ${indices.length}장`);}
 function removeBackground(target){const indices=backgroundTargets(target).filter(i=>slides()[i]&&P.ivar(slides()[i],'RVMediaCue','backgroundMediaCue'));if(!indices.length)return;snapshot();for(const i of indices)P.ivar(slides()[i],'RVMediaCue','backgroundMediaCue').remove();render();status(`배경을 뺐습니다 · ${indices.length}장`);}
 function backgroundMenu(){const chosen=backgroundTargets(),images=chosen.map(i=>slides()[i]&&backgroundImage(slides()[i])).filter(Boolean),none=!images.length,mode=images.length&&images.every(m=>P.attr(m,'scaleBehavior')===images[0].getAttribute('scaleBehavior'))?Object.keys(SCALE).find(k=>SCALE[k]===P.attr(images[0],'scaleBehavior'))||'fill':'';const mark=k=>mode===k?' ✓':'';
  return [{heading:'배경'},{label:'채우기 (가장자리 잘림)'+mark('fill'),disabled:none,action:()=>backgroundScale('fill')},{label:'맞추기 (그림 전체, 빈 곳 생김)'+mark('fit'),disabled:none,action:()=>backgroundScale('fit')},{label:'늘이기 (비율 무시)'+mark('stretch'),disabled:none,action:()=>backgroundScale('stretch')},{label:'배경 자르기…',disabled:none,action:()=>window.YebaeonMediaLibrary.crop(P.attr(images[0],'source'),chosen)},{label:'배경 빼기',disabled:!chosen.some(i=>slides()[i]&&P.ivar(slides()[i],'RVMediaCue','backgroundMediaCue')),action:()=>removeBackground()}];}
 function context(e){S.menu(e,[{label:'빠른 편집 Enter',action:quick},{label:'편집기 Alt+E',action:()=>setView('editor')},{label:'리플로우에서 나누기 Alt+R',action:()=>setView('reflow')},{label:'앞 장에 합치기',disabled:selected===0,action:()=>merge(selected)},...P.all(model.doc,'RVSlideGrouping').map((g,i)=>({label:'그룹 · '+P.attr(g,'name'),action:()=>moveGroup(selection.values().map(Number),i)})),{label:'이름 바꾸기 F2',action:rename},{label:'복제 Ctrl+D',action:duplicate},{label:'복사 Ctrl+C',action:()=>copy()},{label:'붙여넣기 Ctrl+V',action:paste},{label:'삭제 Delete',action:remove},...backgroundMenu()]);}
 $('undo').onclick=guarded(()=>S.active()?.options.kind==='order'&&view!=='editor'?S.active().options.undo(false):undo());$('redo').onclick=guarded(()=>S.active()?.options.kind==='order'&&view!=='editor'?S.active().options.undo(true):undo(true));$('add').onclick=guarded(add);$('label').onchange=guarded(()=>{snapshot();current().setAttribute('label',$('label').value);cards();});$('group').onchange=guarded(()=>moveGroup([selected],Number($('group').value)));
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>toggleView(b.dataset.view));$('reflowClose').onclick=()=>setView('slides');$('reflowSplit').onclick=guarded(()=>{const input=$('reflowRows').querySelector(`[data-index="${reflowIndex}"] textarea`);split(reflowIndex,input.selectionStart);});$('reflowMerge').onclick=guarded(()=>merge(reflowIndex));$('quickClose').onclick=()=>$('quickDialog').close();$('quickPrevious').onclick=()=>{selected--;renderQuick();};$('quickNext').onclick=()=>{selected++;renderQuick();};$('quickDialog').addEventListener('close',()=>render());window.addEventListener('yebaeonfocus',updateControls);window.addEventListener('yebaeonorderhistory',updateControls);window.addEventListener('pp6fontschange',()=>{if(ready)refreshThumbnails(true);});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 window.YebaeonEditor={backgroundScale,removeBackground,open,unavailable,duplicate,applyTemplate,addBible,bibleSlide,setBackground,setView,toggleView,quick,undo,split,merge,redraw:render,status,ready:()=>ready,selection,model:()=>model,current:()=>current(),selected:()=>selected,view:()=>view,isDirty:id=>id===key?dirty:!!cache.get(id)?.dirty,cache:id=>id===key?state():cache.get(id),state:()=>({name:model.name,serial,dirty,key}),document:()=>({...state(),name:model.name,serial}),markDirty:changed,discardChanges(){dirty=false;cache.clear();},beginEdit:snapshot,refreshInspector:renderInspector,refreshPreview:refreshThumbnails,forget(id){if(id!==key)cache.delete(id);},stage(id,value){if(id===key)return false;cache.set(id,{xml:value.xml,selected:0,dirty:true,serial:1,name:value.name});return true;},markCachedSaved(id,xml){const c=cache.get(id);if(c&&c.xml===xml)c.dirty=false;},markSaved(value){if(serial===value){dirty=false;updateControls();}},hasPackageMedia:()=>P.all(model.doc,'[source]').some(e=>P.attr(e,'source').startsWith('file:///PP6-Package/'))};
 render();
})();



