(function(){'use strict';
 const P=window.PP6,R=window.PP6Render,H=window.YebaeonHistory,S=window.YebaeonSelection,$=id=>document.getElementById(id);
 const empty='<RVPresentationDocument width="1920" height="1080"><array rvXMLIvarName="groups"><RVSlideGrouping name="Blank"><array rvXMLIvarName="slides"><RVDisplaySlide UUID="EMPTY"><array rvXMLIvarName="displayElements"/></RVDisplaySlide></array></RVSlideGrouping></array></RVPresentationDocument>';
 let model=P.parse(empty,'문서를 선택하세요'),key='empty',selected=0,dirty=false,ready=false,serial=0,view='slides',reflowIndex=0;
 const cache=new Map(),library=new Map();
 const slides=()=>P.slides(model),current=()=>slides()[selected],groupOf=slide=>slide.parentNode.parentNode;
 const textOf=el=>P.parseRTF(P.textNode(el)?.textContent||'').text;
 const title=slide=>P.attr(slide,'label')||textOf(P.textElements(slide)[0]||slide).split('\n')[0]||'빈 슬라이드';
 const status=message=>{$('status').textContent=message;};
 const guarded=fn=>(...args)=>{try{const p=fn(...args);if(p?.catch)p.catch(e=>status(e.message));}catch(e){status(e.message);}};
 function changed(){dirty=true;serial++;window.dispatchEvent(new Event('yebaeonchange'));updateControls();}
 const state=()=>({xml:P.serialize(model),selected,dirty,serial,name:model.name});
 function snapshot(){H.push(key,state());changed();}
 function stash(){if(ready)cache.set(key,{...state(),name:model.name});}
 function open(xml,name,force=false,identity=name){
  const incoming=P.parse(xml,name);
  if(!force&&dirty&&!confirm('현재 변경은 브라우저 초안에 남습니다. 다른 문서를 열까요?'))return false;
  window.dispatchEvent(new Event('yebaeonbeforeopen'));stash();
  key=identity;model=incoming;selected=0;dirty=false;ready=true;serial++;library.clear();
  selection.chosen=new Set(['0']);selection.anchor='0';selection.cursor='0';render();window.dispatchEvent(new Event('yebaeonopen'));return true;
 }
 function unavailable(doc){
  window.dispatchEvent(new Event('yebaeonbeforeopen'));stash();model=P.parse(empty,doc.name);key=doc.id;selected=0;dirty=false;ready=false;serial++;library.clear();view='slides';
  selection.chosen.clear();selection.setKeys([]);$('inspector').hidden=true;$('reflowPane').hidden=true;$('slidePane').hidden=false;clearCanvases($('reflowRows'));$('texts').replaceChildren();
  document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='slides'));render();$('slideCount').textContent=doc.slideCount?doc.slideCount+'장 · 원본 미업로드':'원본 미업로드';$('templateSelect').options[0].textContent='원본 미업로드';$('templateSelect').value='';$('emptyDocument').textContent='원본 미업로드 · 텍스트 편집과 미리보기를 사용할 수 없습니다. 재생목록 순서에는 넣을 수 있습니다.';
  window.dispatchEvent(new Event('yebaeonopen'));
 }
 function color(slide){const group=groupOf(slide),name=P.attr(group,'name').toLowerCase(),raw=P.attr(group,'color');if(raw)return P.color(raw);return /chorus|후렴/.test(name)?'#bf490b':/bridge|브릿지/.test(name)?'#7735d5':/blank|빈/.test(name)?'#737e93':'#3c57c9';}
 const selection=new S.Selection($('slidePane'),{onSelect:k=>{selected=Number(k);renderInspector();},onPaint:()=>{updateControls();window.dispatchEvent(new Event('yebaeonselection'));}});
 selection.options={...selection.options,kind:'slides',columns:()=>Math.max(1,Math.round($('slides').clientWidth/Math.max(1,$('slides').querySelector('.slide-card')?.clientWidth||240))),open:()=>quick(),remove:()=>remove(),copy:cut=>copy(cut),paste:()=>paste(),rename:()=>rename(),undo:redo=>undo(redo),menu:e=>context(e)};
 function updateControls(){const h=view!=='editor'&&S.active()?.options.kind==='order'&&window.YebaeonPlaylists?.historyState?window.YebaeonPlaylists.historyState():H.state(key);$('undo').disabled=!h.undo;$('redo').disabled=!h.redo;$('dirtyState').textContent=dirty?'저장 안 됨':'';$('templateSelect').disabled=!ready;$('add').disabled=!ready;$('resourceOpen').disabled=!ready;$('mediaOpen').disabled=!ready;$('templateScope').textContent=selection.chosen.size?`고른 ${selection.chosen.size}장에 적용`:'문서 전체에 적용';}
 const canvasData=new WeakMap();
 const canvasObserver=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{for(const entry of entries){const c=entry.target,data=canvasData.get(c);if(!data)continue;data.visible=entry.isIntersecting;if(data.visible&&c.isConnected){const resized=R.fit(c,data.model,data.width);if(!data.drawn||resized){data.drawn=true;data.draw();}}}},{rootMargin:'200px'}):null;
 const resizeObserver=typeof ResizeObserver==='function'?new ResizeObserver(entries=>{for(const {target:c} of entries){const data=canvasData.get(c);if(data?.visible&&c.isConnected&&R.fit(c,data.model,data.width))data.draw();}}):null;
 function clearCanvases(root){root.querySelectorAll('canvas').forEach(c=>{canvasObserver?.unobserve(c);resizeObserver?.unobserve(c);canvasData.delete(c);});root.replaceChildren();}
 function canvasFor(slide,width=400){const c=document.createElement('canvas');c.width=width;c.height=Math.round(width*model.height/model.width);const capturedModel=model,draw=()=>R.draw(c,capturedModel,slide,library).catch(e=>status(e.message));canvasData.set(c,{model:capturedModel,width,draw,visible:!canvasObserver,drawn:false});if(canvasObserver)canvasObserver.observe(c);else draw();resizeObserver?.observe(c);return c;}
 let gridColumns=6;try{gridColumns=Math.max(4,Math.min(8,Number(localStorage.getItem('yebaeon.gridColumns.v2'))||6));}catch(_){}
 function gridSize(value){gridColumns=Math.round(Math.max(4,Math.min(8,value)));$('slides').style.setProperty('--slide-columns',gridColumns);$('slideColumns').value=gridColumns;$('slideColumnsValue').textContent=gridColumns+'개';try{localStorage.setItem('yebaeon.gridColumns.v2',gridColumns);}catch(_){} }
 $('slideColumns').oninput=()=>gridSize(Number($('slideColumns').value));gridSize(gridColumns);
 function cards(){const root=$('slides');clearCanvases(root);if(!ready)return;for(const [i,slide] of slides().entries()){
   const card=document.createElement('div');card.className='slide-card';selection.bind(card,String(i));card.append(canvasFor(slide));const caption=document.createElement('div');caption.className='slide-caption';caption.style.background=color(slide);caption.textContent=`${i+1}. ${P.attr(slide,'label')||P.attr(groupOf(slide),'name','')}`;card.append(caption);card.title=title(slide);
   card.ondblclick=()=>setView('editor');card.oncontextmenu=e=>{if(!selection.chosen.has(String(i)))selection.select(String(i));context(e);};
   card.ondragover=e=>{if(S.drag()?.pane===selection||window.YebaeonResources?.draggedMedia()){e.preventDefault();card.classList.add('drop-before');}};card.ondragleave=()=>card.classList.remove('drop-before');
   card.ondrop=guarded(e=>{e.preventDefault();card.classList.remove('drop-before');const media=window.YebaeonResources?.draggedMedia();if(media){setBackground(media.source,i);return;}if(S.drag()?.pane===selection)reorder(S.drag().keys.map(Number),i);});root.append(card);
  }selection.setKeys(slides().map((_,i)=>String(i)));selection.paint();}
 function renderInspector(){if(!ready)return;const slide=current();$('label').value=P.attr(slide,'label');$('slidePosition').textContent=`${selected+1}/${slides().length}`;$('texts').replaceChildren();
  P.textElements(slide).forEach((element,i)=>{const field=document.createElement('label');field.textContent=P.attr(element,'displayName')||`텍스트 ${i+1}`;const input=document.createElement('textarea');input.value=textOf(element);let transaction=false;input.onfocus=()=>transaction=false;input.oninput=guarded(()=>{if(!transaction){snapshot();transaction=true;}else changed();P.setText(element,input.value);refreshThumbnails();});field.append(input);$('texts').append(field);});
  $('group').replaceChildren();P.all(model.doc,'RVSlideGrouping').forEach((group,i)=>{const o=new Option(P.attr(group,'name','그룹'),i);o.selected=group===groupOf(slide);$('group').add(o);});
  $('fonts').textContent=PP6Fonts.descriptions(slide).join(' · ');window.dispatchEvent(new Event('yebaeonselection'));
 }
 let redrawTimer;
 const changedThumbnails=new Set();let redrawAll=false;
 function refreshThumbnails(all=false){changedThumbnails.add(selected);redrawAll=redrawAll||all;clearTimeout(redrawTimer);redrawTimer=setTimeout(()=>{if(redrawAll){for(const c of $('slides').querySelectorAll('canvas')){const data=canvasData.get(c);if(data?.visible)data.draw();else if(data)data.drawn=false;}}else{const seq=slides();for(const i of changedThumbnails){const card=$('slides').children[i],canvas=card?.querySelector('canvas');if(canvas&&seq[i]){R.draw(canvas,model,seq[i],library).catch(e=>status(e.message));card.title=title(seq[i]);}}}changedThumbnails.clear();redrawAll=false;if(view==='editor')window.YebaeonLayout?.paint();},100);}
 function render(){selected=Math.max(0,Math.min(selected,slides().length-1));selection.cursor=String(selected);$('docTitle').textContent=model.name.replace(/\.pro6$/i,'');$('slideCount').textContent=ready?slides().length+'장':'';$('emptyDocument').hidden=ready;cards();renderInspector();if(view==='reflow')renderReflow();updateControls();window.dispatchEvent(new Event('yebaeonrender'));}
 function toggleView(value){const overlay=!$('biblePanel').hidden||!$('mediaDrawer').hidden;window.YebaeonResources?.closeBible();$('mediaDrawer').hidden=true;setView(!overlay&&view===value?'slides':value);}
 function setView(value){if(!ready)return;view=value;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===value));$('reflowPane').hidden=value!=='reflow';$('slidePane').hidden=value==='reflow';$('inspector').hidden=value!=='editor';render();if(value==='editor')window.YebaeonLayout?.focus();if(value==='reflow')$('reflowRows').querySelector(`[data-index="${selected}"] textarea`)?.focus();}
 function undo(redo=false){if(!ready)return;const previous=H.step(key,state(),redo);if(!previous)return;model=P.parse(previous.xml,model.name);selected=previous.selected;selection.chosen=new Set([String(selected)]);changed();render();status(redo?'다시 실행했습니다.':'실행취소했습니다.');}
 function add(){if(!ready)return;const copy=current().cloneNode(true);if(!P.textElements(copy).length)throw new Error('텍스트 상자가 있는 슬라이드를 선택하세요.');if(slides().length>=1000)throw new Error('문서는 1,000장까지 지원합니다.');snapshot();const slide=P.duplicate(current(),true);selected=slides().indexOf(slide);selection.chosen=new Set([String(selected)]);render();quick();}
 function remove(){const indices=selection.values().map(Number);if(!indices.length)return;if(indices.length>=slides().length)throw new Error('문서에 한 장은 남겨 주세요.');snapshot();const seq=slides();indices.forEach(i=>seq[i].remove());selected=Math.min(selected,slides().length-1);selection.chosen=new Set([String(selected)]);render();}
 function copy(cut=false){const indices=selection.values().map(Number);if(!indices.length)return;S.copy({kind:'slides',width:model.width,height:model.height,xml:indices.map(i=>new XMLSerializer().serializeToString(slides()[i])),cut,key,indices,serial});if(cut){if(indices.length>=slides().length)throw new Error('문서에 한 장은 남겨 주세요.');const clip=S.clipboard();remove();S.copy({...clip,cut:false});status('슬라이드를 잘라냈습니다. 붙여넣거나 실행취소할 수 있습니다.');}else status('슬라이드를 복사했습니다.');}
 function paste(){const clip=S.clipboard();if(clip?.kind!=='slides')return;if(clip.width!==model.width||clip.height!==model.height)throw new Error('크기가 같은 문서에 붙여 넣어 주세요.');if(clip.cut&&clip.key!==key)throw new Error('문서 간 잘라내기는 지원하지 않습니다. 복사해서 붙여 넣어 주세요.');if(clip.cut&&clip.serial!==serial)throw new Error('잘라낸 뒤 문서가 바뀌었습니다. 다시 선택하세요.');if(clip.cut){reorder(clip.indices,selected+1);S.copy({...clip,cut:false});return;}if(slides().length+clip.xml.length>1000)throw new Error('문서는 1,000장까지 지원합니다.');const copies=clip.xml.map(xml=>{const doc=new DOMParser().parseFromString(xml,'application/xml');const slide=model.doc.importNode(doc.documentElement,true);P.refreshIDs(slide);const cues=P.ivar(slide,'array','cues');if(cues)cues.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])slide.setAttribute(k,'');return slide;});snapshot();let after=current();for(const slide of copies){after.parentNode.insertBefore(slide,after.nextSibling);after=slide;}selection.chosen=new Set(copies.map(s=>String(slides().indexOf(s))));selected=slides().indexOf(copies[0]);render();}
 function reorder(indices,targetIndex){const seq=slides(),members=indices.map(i=>seq[i]);if(!members.length||indices.includes(targetIndex))return;const target=seq[targetIndex],parent=target?.parentNode||seq.at(-1).parentNode;snapshot();members.forEach(s=>parent.insertBefore(s,target||null));selection.chosen=new Set(members.map(s=>String(slides().indexOf(s))));selected=slides().indexOf(members[0]);render();}
 function rename(){if(!ready)return;const name=prompt('슬라이드 이름',P.attr(current(),'label'));if(name===null||name===P.attr(current(),'label'))return;snapshot();current().setAttribute('label',name);render();}
 function split(index,offset){const slide=slides()[index],box=P.textElements(slide)[0];if(!box)throw new Error('첫 번째 글상자가 없습니다.');const text=textOf(box);if(offset<=0||offset>=text.length)throw new Error('나눌 글 사이에 커서를 놓으세요.');if(slides().length>=1000)throw new Error('문서는 1,000장까지 지원합니다.');snapshot();const copy=P.duplicate(slide);const parsed=P.parseRTF(P.textNode(box).textContent);P.setRuns(box,P.sliceRuns(parsed.runs,0,offset),parsed.emptyStyle);P.setRuns(P.textElements(copy)[0],P.sliceRuns(parsed.runs,offset,text.length),parsed.emptyStyle);selected=slides().indexOf(copy);selection.chosen=new Set([String(selected)]);render();if(view==='reflow'){const input=$('reflowRows').querySelector(`[data-index="${selected}"] textarea`);input?.focus();input?.setSelectionRange(0,0);}}
 function merge(index){if(index<=0)return;const seq=slides(),a=P.textElements(seq[index-1])[0],b=P.textElements(seq[index])[0];if(!a||!b)throw new Error('두 장 모두 첫 번째 글상자가 필요합니다.');snapshot();const pa=P.parseRTF(P.textNode(a).textContent),pb=P.parseRTF(P.textNode(b).textContent);P.setRuns(a,[...pa.runs,{text:'\n',style:pa.runs.at(-1)?.style||pa.emptyStyle},...pb.runs],pa.emptyStyle);seq[index].remove();selected=index-1;selection.chosen=new Set([String(selected)]);render();}
 function renderReflow(){const root=$('reflowRows');clearCanvases(root);slides().forEach((slide,index)=>{const row=document.createElement('div');row.className='reflow-row';row.dataset.index=index;row.style.borderLeftColor=color(slide);const body=document.createElement('div'),head=document.createElement('div');head.className='reflow-heading';head.textContent=`${index+1}. ${P.attr(groupOf(slide),'name')}`;const groups=document.createElement('select');groups.setAttribute('aria-label',`${index+1}번 그룹`);P.all(model.doc,'RVSlideGrouping').forEach((g,i)=>{const o=new Option(P.attr(g,'name'),i);o.selected=g===groupOf(slide);groups.add(o);});groups.onchange=()=>moveGroup([index],Number(groups.value));head.append(groups);const input=document.createElement('textarea');const box=P.textElements(slide)[0];input.value=box?textOf(box):'';input.disabled=!box;input.setAttribute('aria-label',`${index+1}번 본문`);let transaction=false;input.onfocus=()=>{reflowIndex=index;selected=index;transaction=false;root.querySelectorAll('.active').forEach(e=>e.classList.remove('active'));row.classList.add('active');};input.oninput=guarded(()=>{if(!transaction){snapshot();transaction=true;}else changed();P.setText(box,input.value);const canvas=row.querySelector('canvas');R.draw(canvas,model,slide,library);});input.onkeydown=guarded(e=>{if(e.isComposing)return;if(e.code==='Enter'&&window.YebaeonKeys?.leftAlt()){e.preventDefault();split(index,input.selectionStart);}else if(e.code==='Backspace'&&input.selectionStart===0&&input.selectionEnd===0&&index>0){e.preventDefault();merge(index);}});body.append(head,input);row.append(body,canvasFor(slide,300));root.append(row);});}
 function moveGroup(indices,groupIndex){const group=P.all(model.doc,'RVSlideGrouping')[groupIndex];if(!group)return;const members=indices.map(i=>slides()[i]);snapshot();let container=P.ivar(group,'array','slides');if(!container){container=model.doc.createElement('array');container.setAttribute('rvXMLIvarName','slides');group.append(container);}members.forEach(s=>container.append(s));selected=slides().indexOf(members[0]);selection.chosen=new Set(members.map(s=>String(slides().indexOf(s))));render();}
 async function quick(){if(!ready)return;if(!$('quickDialog').open)$('quickDialog').showModal();await renderQuick();}
 let quickGeneration=0;
 async function renderQuick(){const token=++quickGeneration,slide=current();$('quickTitle').textContent=`빠른 편집 · ${selected+1}. ${title(slide)}`;$('quickPrevious').disabled=selected===0;$('quickNext').disabled=selected===slides().length-1;const canvas=$('quickCanvas');R.fit(canvas,model,640);const warnings=await R.draw(canvas,model,slide,library);if(token!==quickGeneration||!$('quickDialog').open)return;$('quickWarnings').textContent=warnings.join(' · ');$('quickInputs').replaceChildren();
  P.textElements(slide).forEach((box,i)=>{const parsed=P.parseRTF(P.textNode(box)?.textContent||''),field=document.createElement('label');field.textContent=P.attr(box,'displayName')||`텍스트 ${i+1}`;const input=document.createElement('textarea');input.value=parsed.text;input.setAttribute('aria-label',`텍스트 ${i+1}`);let transaction=false,timer;input.onfocus=()=>transaction=false;input.oninput=guarded(()=>{if(!transaction){snapshot();transaction=true;}else changed();P.setText(box,input.value);refreshThumbnails();clearTimeout(timer);timer=setTimeout(async()=>{if(token!==quickGeneration||!$('quickDialog').open)return;R.fit(canvas,model,640);const messages=await R.draw(canvas,model,slide,library);if(token===quickGeneration)$('quickWarnings').textContent=messages.join(' · ');},80);});field.append(input);$('quickInputs').append(field);});$('quickInputs').querySelector('textarea')?.focus();}
 function templateSlide(template){if(template.width!==model.width||template.height!==model.height)throw new Error(`템플릿은 ${template.width}×${template.height}입니다. 같은 크기의 문서를 선택하세요.`);const doc=new DOMParser().parseFromString(template.xml,'application/xml');if(doc.querySelector('parsererror')||doc.documentElement.tagName!=='RVDisplaySlide')throw new Error('템플릿 형식 오류');const slide=model.doc.importNode(doc.documentElement,true);P.refreshIDs(slide);P.ivar(slide,'array','cues')?.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])slide.setAttribute(k,'');return slide;}
 function applyTemplate(template){const indices=selection.chosen.size?selection.values().map(Number):slides().map((_,i)=>i);const prepared=indices.map(i=>{const old=slides()[i],copy=templateSlide(template),values=P.textElements(old).map(textOf),boxes=P.textElements(copy);if(boxes.length<values.length)throw new Error('기존 글상자보다 적은 템플릿입니다. 글을 먼저 정리해 주세요.');boxes.forEach((b,n)=>P.setText(b,values[n]||''));copy.setAttribute('label',P.attr(old,'label'));return {old,copy};});snapshot();prepared.forEach(({old,copy})=>old.replaceWith(copy));render();status(`${prepared.length}장에 템플릿을 적용했습니다.`);}
 function bibleSlide(value,template){if(!template)throw new Error('말씀 템플릿을 선택하세요.');const slide=templateSlide(template);P.refreshIDs(slide);P.ivar(slide,'array','cues')?.replaceChildren();for(const k of ['hotKey','notes','chordChartPath'])slide.setAttribute(k,'');const boxes=P.textElements(slide);if(boxes.length<2)throw new Error('본문과 장절 글상자가 있는 템플릿을 선택하세요.');boxes.forEach((box,i)=>P.setText(box,i===0?value.text:i===1?value.reference:''));slide.setAttribute('label',value.reference+' (NKRV)');return slide;}
 function addBible(values,template){if(!values.length||slides().length+values.length>1000)throw new Error('전체 1,000장 이내에서 추가하세요.');const copies=values.map(v=>bibleSlide(v,template));snapshot();let after=current();copies.forEach(s=>{after.parentNode.insertBefore(s,after.nextSibling);after=s;});selected=slides().indexOf(copies[0]);selection.chosen=new Set(copies.map(s=>String(slides().indexOf(s))));render();status(`말씀 ${copies.length}장을 추가했습니다.`);}
 function setBackground(source,index=selected){const slide=slides()[index];snapshot();let cue=P.ivar(slide,'RVMediaCue','backgroundMediaCue');if(!cue){cue=model.doc.createElement('RVMediaCue');for(const [k,v] of Object.entries({UUID:P.uuid(),rvXMLIvarName:'backgroundMediaCue',actionType:'0',alignment:'4',behavior:'1',enabled:'false'}))cue.setAttribute(k,v);slide.insertBefore(cue,P.ivar(slide,'array','displayElements'));}let media=P.mediaElements(cue)[0];if(!media||media.tagName!=='RVImageElement'){cue.replaceChildren();media=model.doc.createElement('RVImageElement');for(const [k,v]of Object.entries({UUID:P.uuid(),rvXMLIvarName:'element',scaleBehavior:'1',opacity:'1',rotation:'0',format:'PNG'}))media.setAttribute(k,v);cue.append(media);}media.setAttribute('source',source);render();status('교회 자료를 배경으로 적용했습니다. 원래 Mac 경로를 유지합니다.');}
 function context(e){S.menu(e,[{label:'빠른 편집 Enter',action:quick},{label:'편집기 Alt+E',action:()=>setView('editor')},{label:'리플로우에서 나누기 Alt+R',action:()=>setView('reflow')},{label:'앞 장에 합치기',disabled:selected===0,action:()=>merge(selected)},...P.all(model.doc,'RVSlideGrouping').map((g,i)=>({label:'그룹 · '+P.attr(g,'name'),action:()=>moveGroup(selection.values().map(Number),i)})),{label:'이름 바꾸기 F2',action:rename},{label:'복사 Ctrl+C',action:()=>copy()},{label:'붙여넣기 Ctrl+V',action:paste},{label:'삭제 Delete',action:remove}]);}
 $('undo').onclick=guarded(()=>S.active()?.options.kind==='order'&&view!=='editor'?S.active().options.undo(false):undo());$('redo').onclick=guarded(()=>S.active()?.options.kind==='order'&&view!=='editor'?S.active().options.undo(true):undo(true));$('add').onclick=guarded(add);$('label').onchange=guarded(()=>{snapshot();current().setAttribute('label',$('label').value);cards();});$('group').onchange=guarded(()=>moveGroup([selected],Number($('group').value)));
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>toggleView(b.dataset.view));$('reflowClose').onclick=()=>setView('slides');$('reflowSplit').onclick=guarded(()=>{const input=$('reflowRows').querySelector(`[data-index="${reflowIndex}"] textarea`);split(reflowIndex,input.selectionStart);});$('reflowMerge').onclick=guarded(()=>merge(reflowIndex));$('quickClose').onclick=()=>$('quickDialog').close();$('quickPrevious').onclick=()=>{selected--;renderQuick();};$('quickNext').onclick=()=>{selected++;renderQuick();};$('quickDialog').addEventListener('close',()=>render());window.addEventListener('yebaeonfocus',updateControls);window.addEventListener('yebaeonorderhistory',updateControls);window.addEventListener('pp6fontschange',()=>{if(ready)refreshThumbnails(true);});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 window.YebaeonEditor={open,unavailable,applyTemplate,addBible,bibleSlide,setBackground,setView,toggleView,quick,undo,split,merge,redraw:render,status,ready:()=>ready,selection,model:()=>model,current:()=>current(),selected:()=>selected,view:()=>view,isDirty:id=>id===key?dirty:!!cache.get(id)?.dirty,cache:id=>id===key?state():cache.get(id),state:()=>({name:model.name,serial,dirty,key}),document:()=>({...state(),name:model.name,serial}),markDirty:changed,beginEdit:snapshot,refreshInspector:renderInspector,refreshPreview:refreshThumbnails,markCachedSaved(id,xml){const c=cache.get(id);if(c&&c.xml===xml)c.dirty=false;},markSaved(value){if(serial===value){dirty=false;updateControls();}},hasPackageMedia:()=>P.all(model.doc,'[source]').some(e=>P.attr(e,'source').startsWith('file:///PP6-Package/'))};
 render();
})();



