(function(root){'use strict';
 const abbreviations='창 출 레 민 신 수 삿 룻 삼상 삼하 왕상 왕하 대상 대하 스 느 에 욥 시 잠 전 아 사 렘 애 겔 단 호 욜 암 옵 욘 미 나 합 습 학 슥 말 마 막 눅 요 행 롬 고전 고후 갈 엡 빌 골 살전 살후 딤전 딤후 딛 몬 히 약 벧전 벧후 요일 요이 요삼 유 계'.split(' ');
 function parse(query,bible){const match=query.trim().normalize('NFC').match(/^([^\d]+?)\s*(\d[\s\S]*)$/);if(!match)throw new Error('책 이름과 장·절을 입력하세요. 예: 요 3 16 4 2');const name=match[1].trim(),books=bible.books;let index=abbreviations.indexOf(name);if(index<0)index=books.findIndex(b=>b.name===name);if(index<0)index=books.findIndex(b=>b.name.startsWith(name));if(index<0)index=abbreviations.findIndex(a=>a.startsWith(name));if(index<0||!books[index])throw new Error('성경 이름을 찾지 못했습니다.');if(/[^\d\s:~\-장절]/.test(match[2]))throw new Error('장·절 구분을 확인하세요.');const numbers=match[2].match(/\d+/g).map(Number);if(numbers.length<1||numbers.length>4||numbers.some(n=>n<1||!Number.isSafeInteger(n)))throw new Error('장과 절은 양의 정수로 입력하세요.');const book=books[index],chapter=n=>book.chapters.find(c=>c.number===n);const startC=numbers[0],endC=numbers.length===4?numbers[2]:startC;if(!chapter(startC)||!chapter(endC))throw new Error('없는 장입니다.');const startV=numbers.length===1?chapter(startC).verses[0].number:numbers[1],endV=numbers.length===1?chapter(startC).verses.at(-1).number:numbers.length===2?startV:numbers.at(-1);if(!chapter(startC).verses.some(v=>v.number===startV)||!chapter(endC).verses.some(v=>v.number===endV))throw new Error('없는 절입니다.');if(endC<startC||(endC===startC&&endV<startV))throw new Error('끝 장절이 시작 장절보다 앞입니다.');const verses=[];for(const c of book.chapters)for(const v of c.verses)if(c.number>=startC&&c.number<=endC&&(c.number!==startC||v.number>=startV)&&(c.number!==endC||v.number<=endV))verses.push({book:book.name,start:{chapter:c.number,verse:v.number},end:{chapter:c.number,verse:v.number},text:String(v.text).replace(/\r\n?/g,'\n').replace(/[ \t\n]+$/,'')});return {book:book.name,verses,reference:reference({book:book.name,start:{chapter:startC,verse:startV},end:{chapter:endC,verse:endV}})};}
 function reference(v){const a=v.start,b=v.end;return `${v.book} ${a.chapter}:${a.verse}`+(a.chapter!==b.chapter?`-${b.chapter}:${b.verse}`:a.verse!==b.verse?`-${b.verse}`:'');}
 function wrap(text,width,measure,words=true){if(!(width>0))throw new Error('본문 글상자 폭이 없습니다.');const lines=[];for(const paragraph of text.split('\n')){let line='';const tokens=words?paragraph.match(/\S+\s*|\s+/g)||['']:Array.from(paragraph);for(const token of tokens){if(measure(line+token.trimEnd())<=width){line+=token;continue;}if(line.trim()){lines.push(line.trimEnd());line='';}const value=token.trimStart();if(measure(value.trimEnd())<=width){line=value;continue;}for(const char of Array.from(value)){if(line&&measure(line+char)>width){lines.push(line.trimEnd());line='';}line+=char;}}lines.push(line.trimEnd());}return lines;}
 function balanced(lines,capacity){capacity=Math.max(1,Math.floor(capacity));const count=Math.ceil(lines.length/capacity),base=Math.floor(lines.length/count),remainder=lines.length%count,result=[];let offset=0;for(let i=0;i<count;i++){const length=base+(i<remainder?1:0);result.push(lines.slice(offset,offset+length).join('\n'));offset+=length;}return result;}
 root.YebaeonBible={parse,reference,wrap,balanced};
})(typeof window==='undefined'?globalThis:window);

