(function(){'use strict';
 const $=id=>document.getElementById(id),C=YebaeonCloud,L=YebaeonPlaylists,P=PP6,D=YebaeonBulletinDocuments;
 const dialog=document.createElement('dialog');dialog.id='bulletinDialog';dialog.className='bulletin-dialog';
 dialog.innerHTML=`<header><strong>주보·교회 자료</strong><button id="bulletinTab">주보로 준비</button><button id="dropboxTab">교회 자료</button><button id="bulletinClose" aria-label="닫기">×</button></header>
 <section id="bulletinSection"><div class="bulletin-toolbar"><label>주보 <input id="bulletinFile" type="file" accept=".hwp"></label><label>날짜 <input id="bulletinDate" type="date"></label><select id="bulletinService" aria-label="주보 예배"><option value="0">1부</option><option value="1">2부</option><option value="2">3부</option></select><select id="bulletinTarget" aria-label="적용할 재생목록"></select></div>
 <p id="bulletinMessage" class="bulletin-message" role="status">HWP 주보를 선택하세요. 1·2·3부를 나누어 읽고, 검수한 예배만 적용합니다.</p><div class="bulletin-toolbar"><button id="bulletinFind">찬양 후보 찾기</button><span class="bulletin-count" id="bulletinCount"></span></div><div id="bulletinRows" class="bulletin-list"></div><div id="bulletinPreview" class="bulletin-preview"></div>
 <div class="bulletin-actions"><button id="bulletinApply" class="primary">검수 완료 · 순서 초안에 적용</button><small>현재 순서를 교체합니다. 기도·설교·말씀은 새 문서로 등록하며, 순서는 적용 후 ‘변경사항 저장’으로 확정합니다.</small></div></section>
 <section id="dropboxSection" hidden><div class="bulletin-toolbar"><button id="dropboxUp">↑ 상위</button><strong id="dropboxPath">교회 자료</strong><button id="dropboxRefresh">새로고침</button></div><p id="dropboxMessage" class="bulletin-message" role="status"></p><div id="dropboxFiles" class="bulletin-list"></div><button id="dropboxMore" hidden>더 보기</button></section>`;
 document.body.append(dialog);const button=document.createElement('button');button.id='bulletinOpen';button.textContent='주보·자료';$('serverStatus').before(button);
 let bulletin=null,busy=false,active=0,generation=0,dropPath='',dropNext=null,dropGeneration=0;
 const recoveryKey='yebaeon.bulletin.recovery';
 const resultCache=new Map(),sourceCache=new Map();let aliases={};try{aliases=JSON.parse(localStorage.getItem('yebaeon.bulletin.aliases')||'{}');}catch{}
 const aliasKey=item=>item.kind==='song'?'song:'+D.key(item.value):'role:'+active+':'+item.kind+':'+item.label.replace(/\([^)]*\)/g,'');
 const message=s=>$('bulletinMessage').textContent=s;
 const rows=()=>bulletin?.services[active].items||[];
 const dynamic=r=>['prayer','sermon','preacher','scripture'].includes(r.kind);
 function targets(){const old=$('bulletinTarget').value;$('bulletinTarget').replaceChildren(new Option('선택한 순서를 교체할 예배…',''));for(const library of L.libraries())for(const p of library.playlists)$('bulletinTarget').add(new Option(p.name,library.id+'/'+p.id));if([...$('bulletinTarget').options].some(o=>o.value===old))$('bulletinTarget').value=old;}
 function suggestTarget(){targets();const matches=[...$('bulletinTarget').options].filter(o=>o.text.replace(/\s/g,'')===(active+1)+'부예배'||o.text===(active+1)+'부');$('bulletinTarget').value=matches.length===1?matches[0].value:'';}
 function count(){const pending=rows().filter(r=>!r.skip&&!dynamic(r)&&!r.document).length;$('bulletinCount').textContent=`${rows().filter(r=>!r.skip).length}개 항목 · 연결 필요 ${pending}개`;$('bulletinApply').disabled=!bulletin||busy||pending>0;}
 function invalidate(r){if(r.prepared?.path)r.id=crypto.randomUUID();delete r.prepared;delete r.created;$('bulletinPreview').replaceChildren();}
 function lock(value){busy=value;for(const e of dialog.querySelectorAll('button,input,select,textarea'))e.disabled=value;count();}
 async function run(fn){if(busy)return;lock(true);try{await fn();}catch(e){if(!$('dropboxSection').hidden)$('dropboxMessage').textContent=e.message;else message(e.message);}finally{lock(false);}}
 function remember(r){if(r.document){aliases[aliasKey(r)]={id:r.document.id,name:r.document.name,boxIndex:r.boxIndex};try{localStorage.setItem('yebaeon.bulletin.aliases',JSON.stringify(aliases));}catch{message('이 브라우저에서 연결 기억을 저장하지 못했습니다. 현재 선택은 유지됩니다.');}}}
 async function source(id){if(!sourceCache.has(id))sourceCache.set(id,C.documentCopySource(id).catch(e=>{sourceCache.delete(id);throw e;}));return sourceCache.get(id);}
 async function search(r,q){q=q.trim();if(!q)throw Error('검색어를 입력하세요.');if(q.length>120)throw Error('검색어는 120자 이내로 입력하세요.');if(!resultCache.has(q))resultCache.set(q,C.api('/documents?'+new URLSearchParams({q,sort:'used'})).then(r=>r.json()).catch(e=>{resultCache.delete(q);throw e;}));const data=await resultCache.get(q);r.candidates=data.documents.filter(d=>d.available!==false);r.more=!!data.next;return r.candidates;}
 async function selectDoc(r,id){invalidate(r);r.document=r.candidates?.find(d=>d.id===id)||null;r.sourceXML=null;r.boxIndex=null;if(r.document&&dynamic(r)&&r.kind!=='scripture'){const s=await source(id);r.sourceXML=s.xml;r.boxes=D.textBoxes(P.parse(s.xml,r.document.name)).map(x=>x.text);const saved=aliases[aliasKey(r)];if(saved?.id===id&&Number.isInteger(saved.boxIndex)&&r.boxes[saved.boxIndex]!==undefined)r.boxIndex=saved.boxIndex;else if(r.boxes.length===1)r.boxIndex=0;}render();}
 function field(r,root){const controls=document.createElement('div');controls.className='bulletin-controls';
  if(r.kind==='scripture'){controls.textContent='개역개정 · 말씀 템플릿으로 새 문서';}
  else {const input=document.createElement('input');input.setAttribute('aria-label',r.label+' 문서 검색');input.value=r.query||(!dynamic(r)?D.query(r.value):r.label);input.oninput=()=>r.query=input.value;const find=document.createElement('button');find.textContent=dynamic(r)?'서식 찾기':'찾기';find.onclick=()=>run(async()=>{await search(r,input.value);render();});const sel=document.createElement('select');sel.setAttribute('aria-label',r.value+' 연결 문서');sel.add(new Option(dynamic(r)?'기본 서식으로 새 문서':'문서를 선택하세요',''));for(const d of r.candidates||[])sel.add(new Option(d.path||d.name,d.id));sel.value=r.document?.id||'';sel.onchange=()=>run(()=>selectDoc(r,sel.value));controls.append(input,find,sel);
   if(r.sourceXML){const boxes=document.createElement('select');boxes.setAttribute('aria-label','교체할 글상자');boxes.add(new Option('교체할 글상자를 선택하세요',''));r.boxes.forEach((s,i)=>boxes.add(new Option(`${i+1}. ${s.slice(0,100)||'(빈 글상자)'}`,String(i))));boxes.value=r.boxIndex===null?'':String(r.boxIndex);boxes.onchange=()=>{r.boxIndex=boxes.value===''?null:Number(boxes.value);invalidate(r);};controls.append(boxes);}
   if(r.more){const hint=document.createElement('small');hint.textContent='후보 100개 초과 · 검색어를 구체적으로 입력하세요.';controls.append(hint);}
  }
  if(dynamic(r)){const preview=document.createElement('button');preview.textContent='생성 미리보기';preview.onclick=()=>run(async()=>{const xml=await prepare(r);const m=P.parse(xml,r.label),target=$('bulletinPreview');target.replaceChildren();await PP6Fonts.ensure(m.doc);for(const slide of P.slides(m)){const c=document.createElement('canvas');PP6Render.fit(c,m,480);target.append(c);await PP6Render.draw(c,m,slide,new Map());}message('미리보기의 줄바꿈·넘침을 확인하세요. 원본 문서는 바뀌지 않습니다.');});controls.append(preview);}
  root.append(controls);
 }
 function render(){const target=$('bulletinRows');target.replaceChildren();for(const [i,r]of rows().entries()){const row=document.createElement('div');row.className='bulletin-row';const label=document.createElement('label');const include=document.createElement('input');include.type='checkbox';include.checked=!r.skip;include.setAttribute('aria-label',r.label+' 포함');include.onchange=()=>{r.skip=!include.checked;count();};label.append(include,document.createTextNode(`${i+1}. ${r.label}`));const value=document.createElement('textarea');value.value=r.value;value.setAttribute('aria-label',r.label+' 주보 내용');value.onchange=()=>{r.value=value.value.trim();invalidate(r);if(!dynamic(r)){r.document=null;r.candidates=[];}count();};row.append(label,value);field(r,row);target.append(row);}count();}
 async function loadFile(file){if(!/\.hwp$/i.test(file.name))throw Error('HWP 5 파일을 선택하세요.');if(file.size>16*1024*1024)throw Error('16MB 이내 주보를 선택하세요.');const parsed=YebaeonBulletinParser.parse(await file.arrayBuffer());bulletin=parsed;generation++;for(const service of parsed.services)for(const r of service.items){r.id=crypto.randomUUID();r.skip=r.kind==='preacher';}active=0;$('bulletinService').value='0';$('bulletinDate').value=parsed.date;sourceCache.clear();resultCache.clear();$('bulletinPreview').replaceChildren();suggestTarget();render();message(file.name+' · '+(parsed.warnings.join(' · ')||'표 구조를 읽었습니다. 각 예배의 찬양과 기도자를 확인하세요.'));tab(false);}
 async function prepare(r){if(r.prepared)return r.prepared.xml;if(!r.value.trim())throw Error(r.label+' 내용이 비었습니다.');if(r.sourceXML&&r.boxIndex===null)throw Error(r.label+'의 교체할 글상자를 선택하세요.');const xml=await D.make(r);r.prepared={xml};return xml;}
 async function findAll(){if(!bulletin)throw Error('먼저 주보를 선택하세요.');for(const r of rows()){if(r.skip||r.kind==='scripture')continue;const saved=aliases[aliasKey(r)];if(saved){try{const data=await(await C.api('/documents/'+saved.id)).json();r.candidates=[data.document];if(dynamic(r))await selectDoc(r,data.document.id);else r.document=data.document;continue;}catch{delete aliases[aliasKey(r)];}}
   if(dynamic(r))continue;let candidates=await search(r,D.query(r.value));if(!candidates.length&&/^찬송가\s*\d+/.test(r.value))candidates=await search(r,r.value.match(/\d+/)[0]);const exact=candidates.filter(d=>D.key(d.name)===D.key(D.query(r.value)));if(exact.length===1&&!r.more)r.document=exact[0];}render();message('정확히 일치하는 제목과 기억한 연결만 선택했습니다. 나머지는 후보를 고르거나 제외하세요.');}
 function recovery(){try{sessionStorage.setItem(recoveryKey,JSON.stringify({author:C.worker(),bulletin,active,date:$('bulletinDate').value,target:$('bulletinTarget').value}));}catch{throw Error('주보 작업을 브라우저에 보존하지 못했습니다. 저장 공간을 확인하세요.');}}
 async function apply(){if(!bulletin)throw Error('주보를 먼저 선택하세요.');const selected=$('bulletinTarget').value;if(!selected)throw Error('적용할 예배를 선택하세요.');if(!/^\d{4}-\d{2}-\d{2}$/.test($('bulletinDate').value))throw Error('주보 날짜를 확인하세요.');if(L.state().dirty||C.pendingDocuments(L.saveScope()?.ids||[]).length)throw Error('현재 예배의 문서·순서 변경사항을 먼저 저장하세요.');
  const included=rows().filter(r=>!r.skip);if(!included.length)throw Error('한 항목 이상 포함하세요.');for(const r of included){if(!dynamic(r)&&!r.document)throw Error(r.value+'의 연결 문서를 선택하세요.');if(dynamic(r))await prepare(r);}
  const [library,node]=selected.split('/');const plan=(await(await C.api(`/playlists/${library}/plan?`+new URLSearchParams({node,includeIndexed:'1'}))).json());if(!plan.playlist.editable)throw Error('이 순서는 편집할 수 없습니다.');if(C.pendingDocuments(plan.items.map(x=>x.document?.id||x.documentId).filter(Boolean)).length)throw Error('대상 예배 문서의 미저장 변경사항을 먼저 저장하세요.');
  if(!confirm(`${$('bulletinDate').value} ${bulletin.services[active].name} → ${plan.playlist.name}\n기존 ${plan.items.length}개 순서를 검수한 ${included.length}개로 교체합니다.\n기도·설교·말씀은 원본을 보존한 새 문서로 등록합니다. 계속할까요?`))return;
  // Persist this operation's prepared XML before POST: retry reuses path and bytes.
  let done=0;const documents=[];for(const r of included){if(dynamic(r)){if(!r.prepared.path)r.prepared.path=`주보준비/${$('bulletinDate').value}/${bulletin.services[active].name}-${r.label}-${r.id}.pro6`;recovery();if(!r.created){r.created=(await(await C.api('/documents?'+new URLSearchParams({path:r.prepared.path}),{method:'POST',headers:{'Content-Type':'application/xml'},body:r.prepared.xml})).json()).document;}documents.push(r.created);}else documents.push(r.document);remember(r);recovery();done++;message(`${done}/${included.length} 준비됨 · 중단되면 같은 화면에서 다시 적용할 수 있습니다.`);}
  const record={kind:'playlist',id:crypto.randomUUID(),basePlan:plan,items:documents.map(doc=>({kind:'document',name:doc.name.replace(/\.pro6$/i,''),document:doc,documentId:doc.id,path:doc.path,sharedWith:[]})),serial:1};if(!await L.restoreDraft(record))throw Error('초안을 적용하지 못했습니다. 로그인 상태를 확인하세요.');await L.checkpoint();dialog.close();YebaeonEditor.status(`${plan.playlist.name} 주보 초안 적용됨 · 슬라이드를 검수하고 변경사항 저장을 누르세요.`);
 }
 function tab(drop){$('bulletinSection').hidden=drop;$('dropboxSection').hidden=!drop;}
 async function listDropbox(path='',more=false){const g=++dropGeneration;$('dropboxMessage').textContent='불러오는 중…';const data=await(await C.api('/dropbox/list?'+new URLSearchParams({path,...more&&dropNext?{cursor:dropNext}:{}}))).json();if(g!==dropGeneration||!C.authenticated())return;dropPath=path;dropNext=data.next;$('dropboxPath').textContent=path||'교회 자료';if(!more)$('dropboxFiles').replaceChildren();for(const item of data.entries){const row=document.createElement('div');row.className='dropbox-row';const name=document.createElement('span');name.textContent=item.name;row.append(name);if(item.kind==='folder'){const open=document.createElement('button');open.textContent='열기';open.onclick=()=>run(()=>listDropbox(item.path));row.append(open);}else{if(/\.hwp$/i.test(item.name)&&item.size<=16*1024*1024){const use=document.createElement('button');use.textContent='주보로 준비';use.onclick=()=>run(async()=>{const r=await C.api('/dropbox/file?'+new URLSearchParams({path:item.path}));await loadFile(new File([await r.blob()],item.name));});row.append(use);}const a=document.createElement('a');a.textContent='다운로드';a.href='/api/dropbox/file?'+new URLSearchParams({path:item.path});a.download=item.name;row.append(a);}$('dropboxFiles').append(row);}$('dropboxMore').hidden=!dropNext;$('dropboxMessage').textContent='보기·다운로드 전용 · 폴더 원본은 수정하지 않습니다.';}
 button.onclick=()=>{if(!C.needUser())return;targets();if(!bulletin){try{const saved=JSON.parse(sessionStorage.getItem(recoveryKey)||'null');if(saved?.author===C.worker()&&saved.bulletin&&confirm('이 탭의 주보 준비 작업을 복구할까요?')){bulletin=saved.bulletin;active=saved.active;$('bulletinService').value=String(active);$('bulletinDate').value=saved.date;$('bulletinTarget').value=saved.target;render();message('주보 준비 복구됨 · 이미 등록된 문서는 재사용합니다.');}}catch{message('보존한 주보 작업을 읽지 못했습니다. 주보를 다시 선택하세요.');}}dialog.showModal();};$('bulletinClose').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('bulletinTab').onclick=()=>tab(false);
 $('dropboxTab').onclick=()=>run(async()=>{tab(true);try{const c=await(await C.api('/dropbox/config')).json();if(!c.ready){$('dropboxMessage').textContent='관리자가 드롭박스를 최초 연결하면 사용할 수 있습니다. 그동안 주보로 준비에서 HWP를 직접 선택하세요.';return;}await listDropbox(dropPath);}catch(e){$('dropboxMessage').textContent=e.message;}});
 $('dropboxUp').onclick=()=>run(()=>listDropbox(dropPath.split('/').slice(0,-1).join('/')));$('dropboxRefresh').onclick=()=>run(()=>listDropbox(dropPath));$('dropboxMore').onclick=()=>run(()=>listDropbox(dropPath,true));
 $('bulletinFile').onchange=()=>{const f=$('bulletinFile').files[0];if(f)run(()=>loadFile(f));};$('bulletinService').onchange=()=>{active=Number($('bulletinService').value);$('bulletinPreview').replaceChildren();suggestTarget();render();message((active+1)+'부 내용을 검수하고 적용할 재생목록을 선택하세요.');};$('bulletinDate').onchange=()=>{for(const service of bulletin?.services||[])for(const r of service.items)invalidate(r);};$('bulletinFind').onclick=()=>run(findAll);$('bulletinApply').onclick=()=>run(apply);
 dialog.addEventListener('change',()=>{if(bulletin&&!busy)try{recovery();}catch(e){message(e.message);}});
 window.addEventListener('yebaeonsession',e=>{if(!e.detail.authenticated){generation++;dropGeneration++;bulletin=null;resultCache.clear();sourceCache.clear();$('bulletinRows').replaceChildren();$('bulletinPreview').replaceChildren();$('dropboxFiles').replaceChildren();dialog.close();}});
 window.YebaeonBulletin={loadFile,findAll,apply,state:()=>bulletin};count();
})();
