/* Stage manipulation changes the original PP6 XML; view-only locks never enter it. */
(function(){'use strict';
 const E=YebaeonEditor,P=PP6,$=id=>document.getElementById(id),locks=new WeakSet();
 let active=null,slide=null,key='',range=[0,0],textInput=null,gesture=null,drawID=0;
 const elements=()=>Array.from(P.ivar(E.current(),'array','displayElements')?.children||[]);
 const editable=e=>!!P.ivar(e,'RVRect3D','position');
 const isText=e=>e?.tagName==='RVTextElement';
 $('layerProperties').before($('texts'));
 function safe(fn){return (...args)=>{try{fn(...args);}catch(e){E.status(e.message);}};}
 function commit(fn,rebuild=true){if(!active||locks.has(active))return;E.beginEdit();fn();E.refreshPreview();if(rebuild)E.refreshInspector();else paint();}
 function name(e,i){return P.attr(e,'displayName')||(isText(e)?'글상자 '+(i+1):e.tagName==='RVImageElement'?'이미지':'영상');}
 function select(e){active=e;range=[0,0];render();}
 function field(label,type,value,change,options){const row=document.createElement('label');row.textContent=label;const input=document.createElement(options?'select':'input');if(options){for(const [text,val] of options)input.add(new Option(text,val));}else input.type=type;input.value=value;input.disabled=locks.has(active);if(type==='number'){input.step='any';}input.onchange=safe(()=>change(input.value));row.append(input);$('layerProperties').append(row);return input;}
 function stylePatch(patch,paragraph=false){if(!isText(active))return;const parsed=P.parseRTF(P.textNode(active).textContent);let [a,b]=range;if(paragraph&&b>a){a=parsed.text.lastIndexOf('\n',a-1)+1;const end=parsed.text.indexOf('\n',b);b=end<0?parsed.text.length:end;}commit(()=>P.formatRange(active,a,b,patch),false);properties();}
 function properties(){const root=$('layerProperties');root.replaceChildren();if(!active)return;const box=P.rect(active);for(const [label,k] of [['X','x'],['Y','y'],['너비','w'],['높이','h']]){const input=field(label,'number',Math.round(box[k]*100)/100,v=>{const n=Number(v);if(!Number.isFinite(n)||(k==='w'||k==='h')&&n<=0)throw Error('올바른 위치·크기를 입력하세요.');commit(()=>P.setRect(active,{...P.rect(active),[k]:n}));});if(k==='w'||k==='h')input.min='1';}
 const rotation=field('회전','number',P.attr(active,'rotation','0'),v=>{if(!Number.isFinite(Number(v)))return;commit(()=>active.setAttribute('rotation',v));});rotation.min='-360';rotation.max='360';
 field('불투명도','number',P.attr(active,'opacity','1'),v=>commit(()=>active.setAttribute('opacity',String(Math.max(0,Math.min(1,Number(v)||0)))))).max='1';
 if(!isText(active))return;
 const parsed=P.parseRTF(P.textNode(active).textContent),selected=range[1]>range[0]?P.sliceRuns(parsed.runs,...range):parsed.runs,s=selected[0]?.style||parsed.emptyStyle;
 const caption=document.createElement('p');caption.className='help';caption.textContent=range[1]>range[0]?'선택한 글자에 적용':'글상자 전체에 적용';if(new Set(selected.map(r=>JSON.stringify(r.style))).size>1)caption.textContent+=' · 여러 서식';root.append(caption);
 const fontNames=[...new Set([s.font,...PP6Fonts.choices().map(f=>f.name)])];field('폰트 · 굵기 변종','',s.font,v=>stylePatch({font:v,bold:false}),fontNames.map(n=>[n,n]));
 const size=field('글자 크기','number',s.size,v=>{const n=Number(v);if(n>=1&&n<=1000)stylePatch({size:n});});size.min='1';size.max='1000';
 const hex=value=>{if(value.startsWith('#'))return value;return '#'+(value.match(/\d+/g)||[255,255,255]).slice(0,3).map(n=>Number(n).toString(16).padStart(2,'0')).join('');};
 field('글자 색','color',hex(s.color),v=>stylePatch({color:v}));
 for(const [label,k] of [['굵게','bold'],['기울임','italic'],['밑줄','underline']])field(label,'',String(!!s[k]),v=>stylePatch({[k]:v==='true'}),[['해제','false'],['적용','true']]);
 field('문단 정렬','',s.align,v=>stylePatch({align:v},true),[['왼쪽','left'],['가운데','center'],['오른쪽','right']]);
 field('추가 줄 간격','number',s.leading||0,v=>{const n=Number(v);if(Number.isFinite(n)&&n>=-1000&&n<=1000)stylePatch({leading:n},true);});
 field('자간','number',s.tracking||0,v=>{const n=Number(v);if(Number.isFinite(n)&&Math.abs(n)<=1000)stylePatch({tracking:n});});
 field('아웃라인 두께 (%)','number',Math.abs(s.strokeWidth||0),v=>{const n=Number(v);if(Number.isFinite(n)&&n>=0&&n<=100)stylePatch({strokeWidth:-n});});
 field('아웃라인 색','color',hex(s.strokeColor||'#000000'),v=>stylePatch({strokeColor:v}));
 field('세로 정렬','',P.attr(active,'verticalAlignment','0'),v=>commit(()=>active.setAttribute('verticalAlignment',v)),[['위','1'],['가운데','0'],['아래','2']]);
 }
 async function paint(){if(!E.ready()||E.view()!=='editor')return;const token=++drawID,model=E.model(),canvas=$('layoutCanvas');PP6Render.fit(canvas,model,1280);const warnings=await PP6Render.draw(canvas,model,E.current(),new Map());if(token===drawID){$('layoutMessage').textContent=warnings.join(' · ');overlay();}}
 function overlay(){const root=$('layoutOverlay');root.replaceChildren();const model=E.model();for(const e of elements().slice().reverse()){if(!editable(e))continue;const box=P.rect(e),item=document.createElement('div');item.className='layer-box'+(e===active?' active':'')+(locks.has(e)?' locked':'');item.tabIndex=-1;item.setAttribute('aria-label',name(e,elements().indexOf(e)));Object.assign(item.style,{left:box.x/model.width*100+'%',top:box.y/model.height*100+'%',width:box.w/model.width*100+'%',height:box.h/model.height*100+'%',transform:`rotate(${Number(P.attr(e,'rotation','0'))}deg)`});item.onpointerdown=event=>beginGesture(event,e,'move');item.ondblclick=()=>{select(e);if(isText(e))textInput?.focus();};if(e===active&&!locks.has(e)){const handle=document.createElement('button');handle.className='layer-resize';handle.title='크기 조절';handle.setAttribute('aria-label','글상자 크기 조절');handle.onpointerdown=event=>beginGesture(event,e,'resize');item.append(handle);}root.append(item);}}
 function beginGesture(event,e,kind){if(event.button!==0)return;event.preventDefault();event.stopPropagation();active=e;range=[0,0];render();if(locks.has(e))return;if(kind==='resize'&&Number(P.attr(e,'rotation','0'))!==0){E.status('회전된 글상자는 너비·높이 입력으로 조절하세요.');return;}const bounds=$('layoutStage').getBoundingClientRect();gesture={element:e,kind,startX:event.clientX,startY:event.clientY,box:P.rect(e),sx:E.model().width/bounds.width,sy:E.model().height/bounds.height,started:false};$('layoutStage').focus();}
 window.addEventListener('pointermove',safe(event=>{if(!gesture)return;const g=gesture,dx=(event.clientX-g.startX)*g.sx,dy=(event.clientY-g.startY)*g.sy;if(!g.started&&Math.abs(dx)+Math.abs(dy)<2)return;if(!g.started){E.beginEdit();g.started=true;}const box=g.kind==='move'?{...g.box,x:g.box.x+dx,y:g.box.y+dy}:{...g.box,w:Math.max(1,g.box.w+dx),h:Math.max(1,g.box.h+dy)};P.setRect(g.element,box);overlay();paint();}));
 const endGesture=()=>{if(gesture?.started){E.refreshPreview();properties();}gesture=null;};window.addEventListener('pointerup',endGesture);window.addEventListener('pointercancel',endGesture);
 function order(delta){const list=elements(),i=list.indexOf(active),j=i+delta;if(j<0||j>=list.length)return;commit(()=>{if(delta<0)active.parentNode.insertBefore(active,list[j]);else active.parentNode.insertBefore(active,list[j].nextSibling);});}
 function action(label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=safe(fn);$('layerList').append(b);}
 function render(){const shown=E.ready()&&E.view()==='editor';$('layoutStagePane').hidden=!shown;$('editorBody').classList.toggle('layout-mode',shown);if(!shown){gesture=null;return;}if(slide!==E.current()||key!==E.state().key){slide=E.current();key=E.state().key;active=null;range=[0,0];gesture=null;}const list=elements();if(!list.includes(active))active=list.find(isText)||list[0]||null;
 const root=$('layerList');root.replaceChildren();const heading=document.createElement('h3');heading.textContent='레이어 · 위쪽이 맨 앞';root.append(heading);list.forEach((e,i)=>{const row=document.createElement('div');row.className='layer-row';const b=document.createElement('button');b.textContent=name(e,i);b.classList.toggle('active',e===active);b.onclick=()=>select(e);const lock=document.createElement('button');lock.textContent=locks.has(e)?'잠금 해제':'잠금';lock.title='웹 편집 중 이동·수정 잠금';lock.onclick=()=>{if(locks.has(e))locks.delete(e);else locks.add(e);render();};row.append(b,lock);root.append(row);});
 action('앞으로',()=>order(-1),!active||locks.has(active));action('뒤로',()=>order(1),!active||locks.has(active));action('복제',()=>commit(()=>{const copy=active.cloneNode(true);P.refreshIDs(copy);const box=P.rect(copy);P.setRect(copy,{...box,x:box.x+20,y:box.y+20});active.parentNode.insertBefore(copy,active);active=copy;}),!active||locks.has(active)||!editable(active));action('삭제',()=>commit(()=>{active.remove();active=null;}),!active||locks.has(active));
 action('가로 가운데',()=>commit(()=>P.setRect(active,{...P.rect(active),x:(E.model().width-P.rect(active).w)/2})),!editable(active||slide)||locks.has(active));
 textInput=null;$('texts').querySelectorAll('label').forEach((field,i)=>{const e=P.textElements(E.current())[i];field.hidden=e!==active;const input=field.querySelector('textarea');input.disabled=locks.has(e);if(e===active){textInput=input;const remember=()=>{if(document.activeElement!==input)return;range=[input.selectionStart,input.selectionEnd];properties();};input.onselect=remember;input.onkeyup=remember;input.onpointerup=remember;input.oninputLayout=()=>{range=[input.selectionStart,input.selectionEnd];paint();};if(!input.dataset.layoutBound){input.dataset.layoutBound='1';input.addEventListener('input',()=>input.oninputLayout?.());}}});
 properties();paint();
 }
 $('layerAdd').onclick=safe(()=>{if(!E.ready())return;const source=P.textElements(E.current())[0]||P.slides(E.model()).flatMap(P.textElements)[0];if(!source)throw Error('글상자가 있는 템플릿을 먼저 적용하세요.');E.beginEdit();const copy=source.cloneNode(true);P.refreshIDs(copy);copy.setAttribute('displayName','새 글상자');copy.setAttribute('rotation','0');P.setRect(copy,{x:E.model().width*.1,y:E.model().height*.1,w:E.model().width*.8,h:E.model().height*.25});P.setText(copy,'새 텍스트');P.ivar(E.current(),'array','displayElements').prepend(copy);active=copy;E.redraw();});
 $('layoutStage').onkeydown=safe(event=>{if(event.isComposing||!active||locks.has(active))return;const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[event.key];if(delta){event.preventDefault();event.stopPropagation();const step=event.shiftKey?10:1;commit(()=>{const r=P.rect(active);P.setRect(active,{...r,x:r.x+delta[0]*step,y:r.y+delta[1]*step});});}else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();event.stopPropagation();commit(()=>{active.remove();active=null;});}});
 for(const event of ['yebaeonrender','yebaeonselection'])window.addEventListener(event,render);window.addEventListener('pp6fontschange',paint);
 const stageResize=typeof ResizeObserver==='function'?new ResizeObserver(()=>{if(E.view()==='editor')paint();}):null;stageResize?.observe($('layoutStage'));
 window.YebaeonLayout={paint,focus:()=>{$('layoutStage').focus();},render,select,active:()=>active};
})();

