(function(){'use strict';
 const $=id=>document.getElementById(id),P=PP6,C=YebaeonCloud,E=YebaeonEditor,L=YebaeonPlaylists;
 const dialog=document.createElement('dialog');dialog.id='lyricsDialog';dialog.className='studio-import-dialog lyrics-dialog';dialog.setAttribute('aria-labelledby','lyricsTitle');
 dialog.innerHTML='<header><strong id="lyricsTitle">가사찬양 추가</strong><button type="button" id="lyricsClose" class="import-close" aria-label="닫기">×</button></header><div class="lyrics-body"><div class="lyrics-fields"><label class="field">찬양 제목<input id="lyricsName" maxlength="145" placeholder="찬양 제목"></label><label class="field">카테고리<select id="lyricsCategory"></select></label><label class="field lyrics-template">템플릿<select id="lyricsTemplate" aria-label="가사 템플릿"></select></label></div><label class="field">가사<textarea id="lyricsText" rows="9" placeholder="가사를 붙여넣으세요" spellcheck="false"></textarea></label><div class="lyrics-preview-heading"><strong>슬라이드 미리보기</strong><span id="lyricsCount"></span></div><div id="lyricsPreview" class="lyrics-preview" tabindex="0" aria-label="가사 슬라이드 미리보기 · 가로 스크롤"></div><p id="lyricsMessage" class="dialog-message" role="status"></p></div><footer class="import-actions"><label class="lyrics-append"><input type="checkbox" id="lyricsAppend"> 현재 예배 순서에도 추가</label><button type="button" id="lyricsCreate" class="primary">문서 추가</button></footer>';
 document.body.append(dialog);
 const button=document.createElement('button');button.id='lyricsOpen';button.type='button';button.className='studio-tool';button.title='가사찬양 추가';button.setAttribute('aria-label','가사찬양 추가');button.innerHTML='<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M9 18V5l11-2v13M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/></svg><span>가사찬양 추가</span>';$('studioGlobalTools').append(button);
 let busy=false,previewToken=0,prepared=null,history=[],index=0,lastInput=null,initialized=false;
 const value=()=>({name:$('lyricsName').value,text:$('lyricsText').value,template:$('lyricsTemplate').value,category:$('lyricsCategory').value,append:$('lyricsAppend').checked});
 function remember(e){if(e?.isComposing){preview();return;}const next=value();if(JSON.stringify(next)===JSON.stringify(history[index]))return;const merge=e?.inputType==='insertText'&&lastInput?.target===e.target&&Date.now()-lastInput.time<700&&index===history.length-1&&index>0;history=history.slice(0,index+1);if(merge)history[index]=next;else{history.push(next);if(history.length>100)history.shift();index=history.length-1;}lastInput=e?.inputType==='insertText'?{target:e.target,time:Date.now()}:null;prepared=null;preview();}
 function undo(redo=false){if(busy)return;const n=index+(redo?1:-1);if(n<0||n>=history.length)return;index=n;const v=history[index];$('lyricsName').value=v.name;$('lyricsText').value=v.text;$('lyricsTemplate').value=v.template;$('lyricsCategory').value=v.category;$('lyricsAppend').checked=v.append;lastInput=null;prepared=null;preview();}
 function split(text){const out=[];let lines=[];const flush=()=>{if(lines.length){out.push(lines.join('\n'));lines=[];}};for(const line of text.replace(/\r\n?/g,'\n').split('\n')){if(!line.trim()){flush();continue;}lines.push(line.trim());if(lines.length===2)flush();}flush();return out;}
 function documentXML(text,template,category='가사찬양'){const chunks=split(text);if(!chunks.length)throw Error('가사를 입력해 주세요.');if(chunks.length>1000)throw Error('가사는 1,000장 이내로 나누어 주세요.');const parsed=new DOMParser().parseFromString(template.xml,'application/xml'),sample=parsed.documentElement;if(parsed.querySelector('parsererror')||sample.tagName!=='RVDisplaySlide')throw Error('템플릿 형식을 확인해 주세요.');if(!P.textElements(sample).length)throw Error('글상자가 있는 템플릿을 선택하세요.');
  const slides=chunks.map((text,i)=>{const slide=sample.cloneNode(true);P.refreshIDs(slide);P.ivar(slide,'array','cues')?.replaceChildren();P.ivar(slide,'RVMediaCue','backgroundMediaCue')?.remove();for(const node of P.mediaElements(slide))node.remove();slide.setAttribute('drawingBackgroundColor','false');slide.setAttribute('enabled','true');for(const key of ['hotKey','notes','chordChartPath'])slide.setAttribute(key,'');slide.setAttribute('label',String(i+1));P.textElements(slide).forEach((box,n)=>P.setText(box,n===0?text:''));return new XMLSerializer().serializeToString(slide);}).join('');return P.documentXML({width:template.width,height:template.height,category,groups:[{name:'가사',slides}]});}
 async function preview(){const token=++previewToken,chunks=split($('lyricsText').value);$('lyricsCount').textContent=chunks.length+'장';const root=$('lyricsPreview');root.replaceChildren();for(const [i,text] of chunks.slice(0,1000).entries()){const card=document.createElement('article'),body=document.createElement('div'),num=document.createElement('small');card.className='lyrics-preview-card';body.textContent=text;num.textContent=String(i+1);card.append(body,num);root.append(card);}$('lyricsCreate').disabled=busy||!chunks.length||chunks.length>1000||!$('lyricsTemplate').value||!$('lyricsCategory').value;if(!chunks.length){root.textContent='가사를 입력하면 두 줄씩 미리보기가 나타납니다.';return;}
  try{const t=await YebaeonResources.lyricTemplate($('lyricsTemplate').value);if(token!==previewToken)return;documentXML(chunks[0],t);for(const card of root.querySelectorAll('.lyrics-preview-card>div'))card.style.aspectRatio=t.width+'/'+t.height;$('lyricsMessage').textContent='';}catch(e){if(token===previewToken){$('lyricsMessage').textContent=e.message;$('lyricsCreate').disabled=true;}}}
 function lock(on){busy=on;for(const el of dialog.querySelectorAll('input,textarea,select,button'))el.disabled=on;$('lyricsAppend').disabled=on||!L.selectedPlaylist()?.editable;if(!on)$('lyricsCreate').disabled=!split($('lyricsText').value).length||split($('lyricsText').value).length>1000||!$('lyricsTemplate').value||!$('lyricsCategory').value;}
 function categories(){if($('lyricsCategory').options.length)return Promise.resolve();return (async()=>{let names=['가사찬양','악보찬양','예배순서','특별순서','옛날자료'];try{const result=await(await C.api('/categories')).json();if(result.categories?.length)names=result.categories.map(c=>c.name);}catch{}if(!names.includes('가사찬양'))names.unshift('가사찬양');for(const name of names)$('lyricsCategory').add(new Option(name,name));$('lyricsCategory').value='가사찬양';})();}
 button.onclick=async()=>{if(!C.needUser()||busy)return;dialog.showModal();$('lyricsMessage').textContent='템플릿을 불러오는 중…';$('lyricsCreate').disabled=true;try{const [list]=await Promise.all([YebaeonResources.lyricTemplates(),categories()]);if(!$('lyricsTemplate').options.length){for(const t of list){const label=t.id==='64'?'찬양 · 기본텍스트/110':`${t.name} · ${t.label}`;$('lyricsTemplate').add(new Option(label,t.id));}$('lyricsTemplate').value=list.some(t=>t.id==='64')?'64':'';}
   $('lyricsAppend').disabled=!L.selectedPlaylist()?.editable;if($('lyricsAppend').disabled)$('lyricsAppend').checked=false;if(!initialized){$('lyricsAppend').checked=!!L.selectedPlaylist()?.editable;history=[value()];index=0;initialized=true;}await preview();$('lyricsText').focus({preventScroll:true});}catch(e){$('lyricsMessage').textContent=e.message;}};
 $('lyricsClose').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 for(const id of ['lyricsText','lyricsName']){ $(id).addEventListener('input',remember);$(id).addEventListener('compositionend',remember);}for(const id of ['lyricsTemplate','lyricsCategory','lyricsAppend'])$(id).addEventListener('change',remember);
 dialog.addEventListener('keydown',e=>{if(e.isComposing||e.keyCode===229)return;if((e.ctrlKey||e.metaKey)&&!e.altKey&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();e.stopPropagation();undo(e.key.toLowerCase()==='y'||e.shiftKey);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopPropagation();}});
 $('lyricsCreate').onclick=async()=>{if(busy)return;const v=value(),name=v.name.trim().normalize('NFC').replace(/\.pro6$/i,'');if(!name||/[\\/\x00-\x1f\x7f]/.test(name)||name.length>145){$('lyricsMessage').textContent='찬양 제목을 확인해 주세요. 폴더 구분 문자는 사용할 수 없습니다.';$('lyricsName').focus();return;}if(!v.category){$('lyricsMessage').textContent='카테고리를 선택하세요.';return;}const target=v.append?L.selectedPlaylist():null;if(v.append&&!target?.editable){$('lyricsMessage').textContent='문서를 추가할 예배 순서를 먼저 선택하세요.';return;}
  lock(true);$('lyricsMessage').textContent='찬양 문서를 만드는 중…';try{const key=JSON.stringify(v);if(prepared?.key!==key){const template=await YebaeonResources.lyricTemplate(v.template);prepared={key,xml:documentXML(v.text,template,v.category)};}const made=await C.createDocument(name+'.pro6',prepared.xml);let note='';if(target){note=L.selectedPlaylist()?.key===target.key&&L.appendDocuments([made])?' 순서에도 추가했습니다. 서버 저장으로 순서를 확정하세요.':' 순서에 넣지 못했습니다. 검색에서 추가하세요.';}dialog.close();E.setView('slides');window.YebaeonResponsive?.navigate('edit');E.status('가사찬양 문서를 서버에 저장했습니다.'+note);$('lyricsText').value='';$('lyricsName').value='';prepared=null;history=[value()];index=0;lastInput=null;}catch(e){$('lyricsMessage').textContent=e.message;}finally{lock(false);}};
 window.YebaeonLyrics={split,documentXML,undo};
})();
