(function(){'use strict';
 const $=id=>document.getElementById(id),C=YebaeonCloud,P=PP6,E=YebaeonEditor,L=YebaeonPlaylists;
 const dialog=document.createElement('dialog');dialog.id='pptDialog';dialog.className='ppt-dialog';dialog.setAttribute('aria-labelledby','pptHeading');
 dialog.innerHTML=`<header><strong id="pptHeading">PPT 추가</strong><button id="pptClose" aria-label="PPT 추가 닫기">닫기 ×</button></header>
 <div class="ppt-body"><div id="pptDrop" class="ppt-drop"><label for="pptFile"><strong>PPT 파일을 여기에 놓으세요</strong><span>또는 파일 선택 · .ppt / .pptx · 최대 40MB, 120장</span></label><input id="pptFile" type="file" accept=".ppt,.pptx"></div>
 <p class="ppt-help">파일은 이 브라우저에서 변환합니다. 검수 후 추가하면 이미지와 새 문서를 서버에 저장합니다.</p>
 <div id="pptRecovery" hidden><strong>완료하지 못한 가져오기가 있습니다.</strong><button id="pptResume">저장 다시 시도</button><button id="pptDiscard">준비본 버리기</button><div id="pptRename" hidden><p>같은 이름의 기존 문서는 유지합니다. 변환한 이미지를 그대로 새 문서에 저장할 수 있어요.</p><label>새 문서 이름 <input id="pptRecoveryName" maxlength="145"></label><button id="pptRenameSave">이 이름으로 저장</button></div></div>
 <fieldset id="pptOptions"><legend>가져오기 방식</legend><div class="ppt-controls"><label><input type="radio" name="pptMode" value="full" checked> 설교·행사 · 슬라이드 전체 이미지</label><label><input type="radio" name="pptMode" value="score"> 악보 · 배경 분리</label></div>
 <div id="pptScoreOptions" class="ppt-controls" hidden><label>2장부터 제목 부분 자르기 <input id="pptCrop" type="number" min="0" max="40" step="0.1" value="16.7"> %</label><span>첫 번째로 가져오는 장은 제목을 유지합니다. 하단 이동 버튼·텍스트 도형은 제외합니다.</span></div>
 <div id="pptBackgroundControls" class="ppt-controls" hidden><label>배경 <select id="pptBackground"><option value="original">원본 배경</option><option value="color">단색</option><option value="image">새 이미지</option></select></label><input id="pptColor" aria-label="배경색" type="color" value="#ffffff"><input id="pptBackgroundFile" aria-label="새 배경 이미지" type="file" accept="image/png,image/jpeg,image/webp"></div>
 <div class="ppt-controls"><label>문서 이름 <input id="pptName" maxlength="145" placeholder="파일을 선택하세요"></label><button id="pptPreview" disabled>변환 미리보기</button></div></fieldset>
 <p id="pptMessage" class="ppt-message" role="status">일반 슬라이드도 이미지로 변환하기 전에는 원본 폰트가 필요합니다. 글꼴·특수 효과가 다르면 PowerPoint에서 PNG로 내보내 원본과 대조해 주세요.</p>
 <div id="pptSlides" class="ppt-slides"></div><div id="pptLarge" class="ppt-large" hidden><button id="pptLargeClose">확대 닫기</button><div id="pptLargeImage"></div></div>
 <details id="pptBackgroundEdit"><summary>현재 열려 있는 악보 문서의 배경 바꾸기</summary><p>악보를 유지하며 모든 슬라이드의 배경을 바꿉니다. 적용 후 ‘변경사항 저장’을 눌러 주세요.</p><label>배경색 <input id="pptEditColor" type="color" value="#ffffff"></label><input id="pptEditFile" type="file" accept="image/png,image/jpeg,image/webp" aria-label="현재 문서 새 배경 이미지"><button id="pptEditApply">전체 배경 적용</button></details></div>
 <footer><label><input id="pptAppend" type="checkbox"> 선택한 재생목록 맨 아래에도 추가</label><label><input id="pptReviewed" type="checkbox" disabled> 모든 장의 변환 결과를 확인했어요</label><button id="pptSave" class="primary" disabled>검수 완료 · 문서 추가</button></footer>`;
 document.body.append(dialog);const open=document.createElement('button');open.id='pptOpen';open.textContent='PPT 추가';$('bulletinOpen').before(open);
 let deck=null,outputs=[],prepared=null,busy=false,uploading=false,enginePromise=null,bgURL=null,urls=[],renderEpoch=0;
 const message=t=>$('pptMessage').textContent=t,mode=()=>dialog.querySelector('input[name=pptMode]:checked').value;
 const escape=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
 const hash=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await b.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');
 async function engine(){if(window.YebaeonPPTEngine)return window.YebaeonPPTEngine;return enginePromise??=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/ppt-engine.js';s.onload=()=>resolve(YebaeonPPTEngine);s.onerror=()=>{s.remove();enginePromise=null;reject(Error('변환기를 불러오지 못했습니다. 다시 시도해 주세요.'));};document.head.append(s);});}
 function lock(value){busy=value;$('pptOptions').disabled=value||!!prepared;$('pptFile').disabled=value||!!prepared;$('pptEditApply').disabled=value;$('pptResume').disabled=value;$('pptDiscard').disabled=value;$('pptRenameSave').disabled=value;$('pptRecoveryName').disabled=value;$('pptSave').disabled=value||!outputs.length||!$('pptReviewed').checked;$('pptPreview').disabled=value||!deck;$('pptReviewed').disabled=value||!outputs.length;for(const el of $('pptSlides').querySelectorAll('input,select'))el.disabled=value;}
 function invalidate(){outputs=[];prepared=null;for(const u of urls)URL.revokeObjectURL(u);urls=[];$('pptReviewed').checked=false;$('pptReviewed').disabled=true;$('pptSave').disabled=true;$('pptLarge').hidden=true;}
 const requestResult=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
 async function recovery(action,value){const request=indexedDB.open('yebaeon-ppt-import',1);request.onupgradeneeded=()=>request.result.createObjectStore('jobs');const db=await requestResult(request);try{return await new Promise((resolve,reject)=>{const tx=db.transaction('jobs',action==='get'?'readonly':'readwrite'),store=tx.objectStore('jobs'),key=C.worker(),r=action==='put'?store.put(value,key):action==='delete'?store.delete(key):store.get(key);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('준비본 보존 실패'));});}finally{db.close();}}
 function showRecovery(){ $('pptRecovery').hidden=!prepared;$('pptRename').hidden=!prepared?.pathConflict;if(prepared?.pathConflict)$('pptRecoveryName').value=prepared.path.replace(/\.pro6$/i,'').slice(0,139)+' (PPT)';}
 async function openDialog(){if(!C.needUser()||busy)return;dialog.showModal();const selected=L.selectedPlaylist();$('pptAppend').disabled=!selected?.editable;$('pptAppend').checked=!!selected?.editable;try{prepared=await recovery('get')||prepared;showRecovery();lock(false);}catch(e){message('중단 복구 저장소를 열지 못했습니다: '+e.message);}}
 open.onclick=openDialog;$('pptClose').onclick=()=>{if(!uploading){renderEpoch++;dialog.close();}};dialog.addEventListener('cancel',e=>{if(uploading)e.preventDefault();else renderEpoch++;});
 async function read(file){if(busy||!file)return;if(prepared){message('먼저 이전 저장을 다시 시도하거나 준비본을 버려 주세요.');return;}if(!/\.pptx?$/i.test(file.name)){message('PPT 또는 PPTX 파일을 선택해 주세요.');return;}if(file.size>40*1024*1024){message('40MB 이하 파일을 선택해 주세요.');return;}lock(true);invalidate();deck?.dispose();deck=null;const epoch=++renderEpoch;
  try{message('파일 구조와 이미지를 읽고 있습니다…');const lib=await engine(),next=await lib.parse(await file.arrayBuffer());if(epoch!==renderEpoch){next.dispose();return;}deck=next;$('pptName').value=file.name.normalize('NFC').replace(/\.pptx?$/i,'').slice(0,145);deck.slides.forEach(s=>s.selected=!s.hidden);cards();message(`${deck.slides.length}장 읽음. 방식을 선택한 뒤 ‘변환 미리보기’를 누르세요.\n${deck.warnings.join('\n')}`);}catch(e){message('파일 읽기 실패: '+e.message);}finally{lock(false);}
 }
 $('pptFile').onchange=()=>read($('pptFile').files[0]);const drop=$('pptDrop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover');};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');if(e.dataTransfer.files.length!==1){message('한 번에 PPT 파일 하나를 넣어 주세요.');return;}read(e.dataTransfer.files[0]);};
 function cards(){const root=$('pptSlides');root.replaceChildren();if(!deck)return;deck.slides.forEach((s,i)=>{const card=document.createElement('article');card.className='ppt-card';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=s.selected;check.setAttribute('aria-label',`${i+1}장 포함`);check.onchange=()=>{s.selected=check.checked;invalidate();};label.append(check,document.createTextNode(`${i+1}장${s.hidden?' · 숨김':''}`));card.append(label);
  if(mode()==='score'){const select=document.createElement('select');select.setAttribute('aria-label',`${i+1}장 악보 이미지`);if(!s.images.length)select.add(new Option('분리 가능한 이미지 없음','-1'));s.images.forEach((p,j)=>select.add(new Option(`${p.name}${p.transparent?' · 투명':''}`,String(j))));select.value=String(s.scoreIndex);select.onchange=()=>{s.scoreIndex=Number(select.value);invalidate();};card.append(select);}
  const preview=document.createElement('button');preview.className='ppt-thumb';preview.type='button';preview.setAttribute('aria-label',`${i+1}장 확대`);preview.textContent='미리보기 전';preview.onclick=()=>{const o=outputs.find(x=>x.index===i);if(!o)return;const holder=$('pptLargeImage');holder.replaceChildren(composite(o));$('pptLarge').hidden=false;$('pptLarge').scrollIntoView({block:'nearest'});};card.append(preview);card.dataset.index=i;root.append(card);
 });}
 function composite(o){const box=document.createElement('div');box.className='ppt-composite';box.style.aspectRatio=deck?`${deck.width}/${deck.height}`:'16/9';for(const src of [o.bgURL,o.fgURL].filter(Boolean)){const img=document.createElement('img');img.src=src;img.alt='변환 슬라이드';box.append(img);}return box;}
 $('pptLargeClose').onclick=()=>$('pptLarge').hidden=true;
 function optionsChanged(){invalidate();$('pptScoreOptions').hidden=mode()!=='score';$('pptBackgroundControls').hidden=mode()!=='score';cards();}
 for(const r of dialog.querySelectorAll('[name=pptMode]'))r.onchange=optionsChanged;
 for(const id of ['pptCrop','pptBackground','pptColor','pptName'])$(id).oninput=invalidate;
 $('pptBackgroundFile').onchange=()=>{if(bgURL)URL.revokeObjectURL(bgURL);bgURL=$('pptBackgroundFile').files[0]?URL.createObjectURL($('pptBackgroundFile').files[0]):null;$('pptBackground').value='image';invalidate();};
 async function preview(){if(busy||!deck)return;invalidate();lock(true);const epoch=++renderEpoch,lib=await engine(),selected=deck.slides.map((s,i)=>s.selected?i:-1).filter(i=>i>=0),made=[];
  try{if(!selected.length)throw Error('가져올 장을 선택해 주세요.');const crop=Number($('pptCrop').value)/100;if(!Number.isFinite(crop)||crop<0||crop>.4)throw Error('자르기는 0~40%로 입력해 주세요.');if(mode()==='score'&&$('pptBackground').value==='image'&&!bgURL)throw Error('새 배경 이미지를 선택해 주세요.');let total=0;
   for(const [n,i] of selected.entries()){message(`${n+1}/${selected.length}장 변환 중…`);const result=await lib.render(deck,i,{mode:mode(),crop,keepTitle:n===0,background:$('pptBackground').value,backgroundColor:$('pptColor').value,backgroundImage:bgURL});if(epoch!==renderEpoch)return;total+=result.foreground.size+(result.background?.size||0);if(total>180*1024*1024)throw Error('변환 이미지가 180MB를 넘습니다. 장을 나누어 가져와 주세요.');const o={...result,index:i,fgURL:URL.createObjectURL(result.foreground),bgURL:result.background?URL.createObjectURL(result.background):null};urls.push(o.fgURL,...o.bgURL?[o.bgURL]:[]);made.push(o);const card=$('pptSlides').querySelector(`[data-index="${i}"] .ppt-thumb`);card.replaceChildren(composite(o));await new Promise(r=>setTimeout(r,0));}
   outputs=made;message(`${made.length}장 준비됨 · 썸네일을 누르면 크게 볼 수 있어요.\n${[...new Set([...deck.warnings,...made.flatMap(o=>o.warnings)])].join('\n')}`);
  }catch(e){invalidate();message('변환 실패: '+e.message);}finally{lock(false);}
 }
 $('pptPreview').onclick=preview;$('pptReviewed').onchange=()=>lock(busy);
 function imageElement(source,w,h){return `<RVImageElement UUID="${P.uuid()}" source="${source}" scaleBehavior="0" opacity="1" rotation="0" drawingShadow="false" format="PNG"><RVRect3D rvXMLIvarName="position">{0 0 0 ${w} ${h}}</RVRect3D></RVImageElement>`;}
 function documentName(value){const name=value.trim().normalize('NFC').replace(/\.pro6$/i,'');if(!name||/[\\/\x00-\x1f\x7f]/.test(name)||name.length>145)throw Error('문서 이름을 확인해 주세요. 폴더 구분 문자는 사용할 수 없습니다.');return name;}
 async function prepare(){const name=documentName($('pptName').value);const assets=new Map(),w=1920,h=Math.round(w*deck.height/deck.width);let slides='';
  async function source(b){const sha256=await hash(b);assets.set(sha256,{sha256,blob:b});return 'file:///YebaeOn-Media/'+sha256+'.png';}
  for(const o of outputs){const fg=await source(o.foreground),bg=o.background?await source(o.background):null;slides+=`<RVDisplaySlide UUID="${P.uuid()}" label="${o.index+1}" enabled="true" drawingBackgroundColor="true" backgroundColor="1 1 1 1">${bg?`<RVMediaCue UUID="${P.uuid()}" rvXMLIvarName="backgroundMediaCue" actionType="0" alignment="4" behavior="1" enabled="true">${imageElement(bg,w,h).replace('<RVImageElement ','<RVImageElement rvXMLIvarName="element" ')}</RVMediaCue>`:''}<array rvXMLIvarName="displayElements">${imageElement(fg,w,h)}</array><array rvXMLIvarName="cues"/></RVDisplaySlide>`;}
  const xml=`<RVPresentationDocument UUID="${P.uuid()}" versionNumber="600" width="${w}" height="${h}" category="${mode()==='score'?'악보찬양':'특별순서'}" lastDateUsed="" usedCount="0" yebaeonImport="${mode()}"><array rvXMLIvarName="groups"><RVSlideGrouping UUID="${P.uuid()}" name="기본"><array rvXMLIvarName="slides">${slides}</array></RVSlideGrouping></array></RVPresentationDocument>`;
  return {path:name+'.pro6',xml,assets:[...assets.values()],owner:C.worker(),appendTarget:$('pptAppend').checked?L.selectedPlaylist()?.key:null};
 }
 async function save(resume=false){if(busy||!C.needUser()||window.YebaeonSave?.busy())return;if(!resume&&(!$('pptReviewed').checked||!outputs.length))return;uploading=true;lock(true);
  try{if(!prepared){const next=await prepare();await recovery('put',next);prepared=next;}if(prepared.owner!==C.worker())throw Error('준비한 작업자 이름으로 입장해 주세요.');
   const known=new Set();for(let i=0;i<prepared.assets.length;i+=80){const query=new URLSearchParams();for(const a of prepared.assets.slice(i,i+80))query.append('hash',a.sha256);const found=await(await C.api('/media?'+query)).json();for(const a of found.assets)known.add(a.sha256);}
   for(let i=0;i<prepared.assets.length;i++){const a=prepared.assets[i];if(known.has(a.sha256))continue;message(`이미지 저장 ${i+1}/${prepared.assets.length}…`);await C.api('/media/'+a.sha256+'/content',{method:'PUT',headers:{'Content-Type':'image/png','X-Yebaeon-SHA256':a.sha256},body:a.blob});}
   message('문서를 등록하고 이미지 연결을 확인하고 있습니다…');const result=await(await C.api('/documents?'+new URLSearchParams({path:prepared.path}),{method:'POST',headers:{'Content-Type':'application/xml'},body:prepared.xml})).json();prepared.document=result.document;await recovery('put',prepared);
   let added=false;if(prepared.appendTarget&&prepared.appendTarget===L.selectedPlaylist()?.key&&!L.memberIDs().includes(result.document.id)){added=L.appendDocuments([result.document]);if(added)await L.checkpoint();}
   await C.openDocument(result.document.id);await recovery('delete');prepared=null;$('pptRecovery').hidden=true;dialog.close();E.status(added?'PPT 문서를 추가했습니다. 순서는 변경사항 저장으로 확정해 주세요.':'PPT 문서를 추가했습니다. 이름으로 검색해 순서에 넣을 수 있습니다.');invalidate();
  }catch(e){if(e.code==='path_exists'&&prepared){prepared.pathConflict=true;try{await recovery('put',prepared);}catch{ /* Existing stable recovery still permits retry. */ }}message('저장 중단: '+e.message+(e.code==='path_exists'?'\n위의 새 문서 이름을 확인하고 ‘이 이름으로 저장’을 누르세요. 다시 변환할 필요가 없습니다.':prepared?'\n준비본을 보존했습니다. ‘저장 다시 시도’를 누르면 같은 문서로 이어갑니다.':'\n복구 준비본을 저장하지 못해 서버 업로드를 시작하지 않았습니다. 이 창을 유지하고 입력값과 브라우저 저장 공간을 확인해 주세요.')); showRecovery();}finally{uploading=false;lock(false);}
 }
 $('pptRenameSave').onclick=async()=>{if(busy||!prepared?.pathConflict||!C.needUser())return;lock(true);let renamed=false;try{const path=documentName($('pptRecoveryName').value)+'.pro6';if(path===prepared.path)throw Error('기존 이름과 다른 새 이름을 입력해 주세요.');const next={...prepared,path,pathConflict:false};delete next.document;await recovery('put',next);prepared=next;showRecovery();renamed=true;}catch(e){message('이름 변경 중단: '+e.message);}finally{lock(false);}if(renamed)await save(true);};
 $('pptSave').onclick=()=>save();$('pptResume').onclick=()=>save(true);$('pptDiscard').onclick=async()=>{if(busy||!confirm('이 브라우저의 PPT 준비본을 버릴까요? 이미 서버에 저장된 이미지나 문서는 삭제하지 않습니다.'))return;try{await recovery('delete');prepared=null;invalidate();$('pptRecovery').hidden=true;message('준비본을 버렸습니다. 새 파일을 선택할 수 있습니다.');}catch(e){message(e.message);}};
 $('pptEditApply').onclick=async()=>{if(busy||!C.needUser())return;if(!E.ready()||E.model().doc.documentElement.getAttribute('yebaeonImport')!=='score'){message('배경을 분리해 가져온 악보 문서를 먼저 열어 주세요.');return;}lock(true);uploading=true;
  try{const lib=await engine(),model=E.model(),key=E.state().key,c=lib.makeCanvas(1920,Math.round(1920*model.height/model.width)),ctx=c.getContext('2d');ctx.fillStyle=$('pptEditColor').value;ctx.fillRect(0,0,c.width,c.height);const file=$('pptEditFile').files[0];if(file){if(file.size>20*1024*1024)throw Error('배경은 20MB 이하로 선택해 주세요.');const bitmap=await createImageBitmap(file);const scale=Math.max(c.width/bitmap.width,c.height/bitmap.height);ctx.drawImage(bitmap,(c.width-bitmap.width*scale)/2,(c.height-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();}const b=await lib.blob(c),digest=await hash(b);await C.api('/media/'+digest+'/content',{method:'PUT',headers:{'Content-Type':'image/png','X-Yebaeon-SHA256':digest},body:b});if(E.state().key!==key)throw Error('열린 문서가 바뀌었습니다. 다시 적용해 주세요.');E.beginEdit();for(const s of P.slides(model)){const el=P.ivar(s,'RVMediaCue','backgroundMediaCue');if(el)for(const m of P.mediaElements(el))m.setAttribute('source','file:///YebaeOn-Media/'+digest+'.png');}E.redraw();dialog.close();E.status('전체 악보 배경을 바꿨습니다. 변경사항 저장으로 확정해 주세요.');}catch(e){message(e.message);}finally{uploading=false;lock(false);}
 };
 window.addEventListener('yebaeonsession',e=>{if(!e.detail.authenticated&&!busy){dialog.close();deck?.dispose();deck=null;invalidate();prepared=null;cards();}});
 window.YebaeonPPTImport={read,preview,save,open:openDialog,state:()=>({deck,outputs,prepared,busy}),imageElement};
})();
