(function(){'use strict';
 const $=id=>document.getElementById(id),E=YebaeonEditor,P=PP6,B=YebaeonBible;
 let catalog=null,templates=[],bible=null,loading=null,draft=[],filter='all',editing=-1,buildSequence=0,mediaDrag=null,target=null;
 const mediaFiles=new Map();const normalize=value=>{if(value.startsWith('file:')){try{const url=new URL(value);if(url.host||url.search||url.hash)return value.normalize('NFC');return decodeURIComponent(url.pathname).normalize('NFC');}catch{}}return value.normalize('NFC');};
 async function resource(name){const r=await fetch('/resources/'+name,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'입장한 뒤 자료를 사용할 수 있습니다.':'교회 자료를 읽지 못했습니다.');return r;}
 async function boot(){if(catalog)return catalog;if(loading)return loading;loading=(async()=>{const value=await(await resource('catalog.json')).json();PP6Fonts.registerCatalog(value.fonts);templates=await(await resource('templates.json')).json();catalog=value;for(const id of ['templateSelect','bibleTemplate']){const s=$(id);s.replaceChildren(new Option(id==='templateSelect'?'현재 서식':'현재 슬라이드',''));for(const t of templates)s.add(new Option(`${t.name} · ${t.label}`,t.id));}E.redraw();return value;})();try{return await loading;}finally{loading=null;}}
 async function media(source){if(!catalog)return null;const match=catalog.media.find(x=>normalize(x.source)===normalize(source));if(!match)return null;if(!mediaFiles.has(match.file))mediaFiles.set(match.file,resource(match.file).then(r=>r.blob()).then(b=>new File([b],match.name,{type:'image/png'})).catch(()=>{mediaFiles.delete(match.file);return null;}));return mediaFiles.get(match.file);}
 const template=()=>templates.find(x=>x.id===$('bibleTemplate').value);
 function boxInfo(){const sample=E.bibleSlide({text:'',reference:'장절'},template()),box=P.textElements(sample)[0],style=P.parseRTF(P.textNode(box).textContent).emptyStyle,rect=P.rect(box);return {sample,box,style,rect};}
 async function metrics(){const info=boxInfo();const warnings=await PP6Fonts.ensure(info.sample);if(warnings.length)$('resourceMessage').textContent=warnings.join(' · ');const ctx=document.createElement('canvas').getContext('2d');ctx.font=PP6Fonts.css(info.style);return {...info,measure:text=>ctx.measureText(text).width,capacity:Math.max(1,Math.floor((info.rect.h+(info.style.leading||0))/(info.style.size*1.2+(info.style.leading||0))))};}
 function targetLabel(){$('bibleTarget').textContent=`넣을 곳: ${E.state().name.replace(/\.pro6$/i,'')} · ${E.selected()+1}장 뒤`;}
 async function show(){if(!E.ready()||!YebaeonCloud.needUser())return;try{await boot();if(!bible)bible=await(await resource('bible.json')).json();target={key:E.state().key,index:E.selected()};targetLabel();$('biblePanel').hidden=false;$('bibleQuery').focus();if($('bibleQuery').value){if(draft.length)await render();else await build();}}catch(error){E.status(error.message);}}
 async function build(){const token=++buildSequence;editing=-1;$('bibleAdd').disabled=true;try{await boot();if(!bible)bible=await(await resource('bible.json')).json();const parsed=B.parse($('bibleQuery').value,bible);const m=await metrics();if(token!==buildSequence)return;draft=[];for(const verse of parsed.verses){const lines=B.wrap(verse.text,m.rect.w,m.measure,$('bibleWrap').checked);const chunks=B.balanced(lines,m.capacity);for(const text of chunks)draft.push({...verse,text,changed:chunks.length>1,manual:false});}$('bibleParsed').textContent=`${parsed.reference} · ${parsed.verses.length}절 · NKRV`;$('resourceMessage').textContent=PP6Fonts.state().some(x=>x.status!=='loaded')?'대체 글꼴로 계산한 결과입니다. PP6에서 최종 확인하세요.':'';await render();}catch(error){if(token!==buildSequence)return;draft=[];$('bibleGrid').replaceChildren();$('bibleParsed').textContent='';$('resourceMessage').textContent=error.message;}}
 async function render(){const token=++buildSequence,root=$('bibleGrid');root.replaceChildren();if(!draft.length)return;const m=await metrics();if(token!==buildSequence)return;let long=0,changed=0;draft.forEach((value,index)=>{const lines=B.wrap(value.text,m.rect.w,m.measure,$('bibleWrap').checked),overflow=lines.length>m.capacity;value.lineCount=lines.length;value.overflow=overflow;if(lines.length>=6)long++;if(value.changed)changed++;if(filter==='long'&&lines.length<6||filter==='changed'&&!value.changed)return;const card=document.createElement('div');card.className='bible-card'+(lines.length>=6?' long':'')+(value.changed?' changed':'')+(editing===index?' editing':'');card.tabIndex=0;const reference=B.reference(value);if(editing===index){const input=document.createElement('textarea');input.value=value.text;input.setAttribute('aria-label',reference+' 본문');input.oninput=()=>{value.text=input.value;value.manual=true;value.changed=true;const measured=B.wrap(value.text,m.rect.w,m.measure,$('bibleWrap').checked);caption.lastChild.textContent=measured.length+'줄'+(measured.length>m.capacity?' · 넘침':'');};input.onkeydown=e=>{if(e.isComposing)return;if(e.code==='Enter'&&YebaeonKeys.leftAlt()){e.preventDefault();split(index,input.selectionStart);}else if(e.code==='Backspace'&&!input.selectionStart&&!input.selectionEnd&&index>0){e.preventDefault();merge(index);}else if(e.code==='Escape'){e.preventDefault();e.stopPropagation();editing=-1;render();}};card.append(input);setTimeout(()=>input.focus(),0);}else{const canvas=document.createElement('canvas');canvas.width=400;canvas.height=400*E.model().height/E.model().width;const slide=E.bibleSlide({text:lines.join('\n'),reference},template());PP6Render.draw(canvas,E.model(),slide,new Map());card.append(canvas);card.ondblclick=()=>{editing=index;render();};}
 const caption=document.createElement('div');caption.className='bible-caption';const label=document.createElement('strong');label.textContent=reference;const count=document.createElement('span');count.textContent=lines.length+'줄'+(overflow?' · 넘침':'');caption.append(label,count);card.append(caption);const actions=document.createElement('div');actions.className='bible-actions';for(const [name,action,disabled] of [['앞 장에 합치기',()=>merge(index),index===0],['나누기',()=>split(index),false]]){const button=document.createElement('button');button.textContent=name;button.disabled=disabled;button.onclick=action;actions.append(button);}card.append(actions);root.append(card);});$('bibleCount').textContent=draft.length;$('bibleLong').textContent=long;$('bibleChanged').textContent=changed;$('bibleAdd').textContent=`말씀 ${draft.length}장 추가`;$('bibleAdd').disabled=draft.length===0;}
 function split(index,offset){const item=draft[index];if(offset===undefined){const lines=item.text.split('\n');if(lines.length>1)offset=lines.slice(0,Math.ceil(lines.length/2)).join('\n').length;else{const middle=Math.floor(item.text.length/2);offset=item.text.indexOf(' ',middle);if(offset<0)offset=middle;}}if(offset<=0||offset>=item.text.length){$('resourceMessage').textContent='나눌 글 사이에 커서를 놓으세요.';return;}draft.splice(index,1,{...item,text:item.text.slice(0,offset).trimEnd(),changed:true,manual:true},{...item,text:item.text.slice(offset).trimStart(),changed:true,manual:true});editing=-1;render();}
 function merge(index){if(index<=0)return;const a=draft[index-1],b=draft[index];draft.splice(index-1,2,{...a,text:a.text+'\n'+b.text,end:b.end,changed:true,manual:true});editing=-1;render();}
 function close(){clearTimeout(queryTimer);buildSequence++;$('biblePanel').hidden=true;}
 function requestBuild(){clearTimeout(queryTimer);if(draft.some(x=>x.manual)&&!confirm('직접 고친 말씀 미리보기를 다시 만들까요?'))return;build();}
 $('resourceOpen').onclick=show;$('resourceClose').onclick=close;$('bibleCancel').onclick=close;$('bibleTargetChange').onclick=()=>{close();E.status('넣을 문서와 슬라이드를 선택한 뒤 말씀을 다시 여세요.');};$('bibleQuery').onchange=requestBuild;let queryTimer;$('bibleQuery').oninput=()=>{clearTimeout(queryTimer);if(!draft.some(x=>x.manual))queryTimer=setTimeout(build,350);};$('bibleTemplate').onchange=requestBuild;$('bibleWrap').onchange=requestBuild;
 document.querySelectorAll('[data-bible-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.bibleFilter;document.querySelectorAll('[data-bible-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});
 $('bibleAdd').onclick=async()=>{try{if(target.key!==E.state().key||target.index!==E.selected())throw new Error('넣을 문서나 슬라이드가 바뀌었습니다. 넣을 곳을 다시 선택하세요.');const m=await metrics();const values=draft.map(v=>({text:B.wrap(v.text,m.rect.w,m.measure,$('bibleWrap').checked).join('\n'),reference:B.reference(v)}));E.addBible(values,template());close();}catch(error){$('resourceMessage').textContent=error.message;}};
 $('templateSelect').onchange=()=>{try{const value=templates.find(x=>x.id===$('templateSelect').value);if(value)E.applyTemplate(value);}catch(error){E.status(error.message);}finally{$('templateSelect').value='';}};
 async function showMedia(){if(!E.ready()||!YebaeonCloud.needUser())return;try{await boot();$('mediaDrawer').hidden=false;fillMedia();$('mediaQuery').focus();}catch(error){E.status(error.message);}}
 function fillMedia(){const query=$('mediaQuery').value.normalize('NFC').toLowerCase(),root=$('mediaGrid');root.replaceChildren();for(const item of catalog.media.filter(x=>x.name.normalize('NFC').toLowerCase().includes(query))){const button=document.createElement('button');button.draggable=true;button.title=item.source;const img=document.createElement('img');img.src='/resources/'+item.file;img.alt='';img.loading='lazy';const label=document.createElement('span');label.textContent=item.name;button.append(img,label);button.ondragstart=e=>{mediaDrag=item;e.dataTransfer.setData('text/plain',item.source);e.dataTransfer.effectAllowed='copy';};button.ondragend=()=>mediaDrag=null;button.onclick=()=>E.setBackground(item.source);root.append(button);}}
 $('mediaOpen').onclick=showMedia;$('mediaClose').onclick=()=>$('mediaDrawer').hidden=true;$('mediaQuery').oninput=fillMedia;$('serverStatus').onclick=()=>window.open('/status','_blank','noopener');
 window.addEventListener('yebaeonsession',event=>{if(event.detail.authenticated)boot().catch(e=>E.status(e.message));else{catalog=null;mediaFiles.clear();}});
 window.YebaeonResources={boot,media,showBible:show,showMedia,draggedMedia:()=>mediaDrag,closeBible:close};
})();
