(function(){'use strict';
 const $=id=>document.getElementById(id),E=YebaeonEditor,P=PP6,B=YebaeonBible;
 let catalog=null,templates=[],bible=null,loading=null,draft=[],filter='all',editing=-1,buildSequence=0,templateApplySequence=0,mediaDrag=null,target=null,bibleView='slides';
 const templateLoads=new Map();
 const footer=document.querySelector('.editor-footer');
 const footerSpace=()=>document.documentElement.style.setProperty('--studio-footer-space',`${Math.max(0,innerHeight-footer.getBoundingClientRect().top)}px`);
 new ResizeObserver(footerSpace).observe(document.querySelector('.editing-column'));new ResizeObserver(footerSpace).observe(footer);window.addEventListener('resize',footerSpace);footerSpace();
 const knownFormats=new Map();let labelSequence=0;
 const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),n=>n.toString(16).padStart(2,'0')).join('');
 // Stable catalog ID of the supplied Arita-buri 90pt sermon body (right-hand reference).
 const DEFAULT_BIBLE_TEMPLATE_ID='104';
 const templateName=t=>`${t.name} · ${t.label} · #${t.id}`;
 const optionName=t=>`${templateName(t)} · ${t.width}×${t.height}`;
 let resetBibleTemplate=true;
 async function formatName(slide){const format=P.templateFormat(slide);if(knownFormats.has(format))return knownFormats.get(format);const hash=await digest(format),matches=templates.filter(t=>t.format===hash&&t.width===E.model().width&&t.height===E.model().height);const names=[...new Set(matches.map(templateName))];return names.length===1?names[0]:names.length>1?'여러 템플릿과 같은 서식':'이름 정보 없는 서식';}
 async function updateTemplateLabels(){const token=++labelSequence;if(!catalog||!E.ready())return;const current=await formatName(E.current()),slides=P.slides(E.model()),indices=E.selection.values().map(Number);const names=await Promise.all((indices.length?indices:slides.map((_,i)=>i)).map(i=>formatName(slides[i])));if(token!==labelSequence)return;const mixed=new Set((indices.length?indices:slides.map((_,i)=>i)).map(i=>P.templateFormat(slides[i]))).size>1;const label=mixed?'여러 서식 선택됨':names[0]||current;$('templateSelect').options[0].textContent=label;$('templateSelect').title=label;}
 async function ensureTemplate(value){if(!value||typeof value.xml==='string')return value;if(!value.file||!/^template-[a-f0-9]{24}\.json$/.test(value.file))throw new Error('템플릿 파일을 확인해 주세요.');if(!templateLoads.has(value.file))templateLoads.set(value.file,resource(value.file).then(r=>r.json()).then(data=>{if(typeof data.xml!=='string')throw new Error('템플릿 원본이 없습니다.');return data.xml;}).catch(error=>{templateLoads.delete(value.file);throw error;}));value.xml=await templateLoads.get(value.file);return value;}
 const mediaFiles=new Map();const normalize=value=>{if(value.startsWith('file:')){try{const url=new URL(value);if(url.host||url.search||url.hash)return value.normalize('NFC');return decodeURIComponent(url.pathname).normalize('NFC');}catch{}}return value.normalize('NFC');};
 async function resource(name){const r=await fetch('/resources/'+name,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'입장한 뒤 자료를 사용할 수 있습니다.':'교회 자료를 읽지 못했습니다.');return r;}
 async function boot(){if(catalog)return catalog;if(loading)return loading;loading=(async()=>{const [value,list]=await Promise.all([resource('catalog.json').then(r=>r.json()),resource('templates.json').then(r=>r.json())]);PP6Fonts.registerCatalog(value.fonts);templates=list;catalog=value;for(const id of ['templateSelect','bibleTemplate']){const s=$(id);s.replaceChildren(new Option(id==='bibleTemplate'?'말씀 템플릿을 선택하세요':'슬라이드를 선택하세요',''));for(const t of templates)s.add(new Option(optionName(t),t.id));}window.dispatchEvent(new Event('yebaeonresourcesready'));E.redraw();return value;})();try{return await loading;}finally{loading=null;}}
 async function media(source){if(!catalog)return null;const match=catalog.media.find(x=>normalize(x.source)===normalize(source));if(!match)return null;if(!mediaFiles.has(match.file))mediaFiles.set(match.file,resource(match.file).then(r=>r.blob()).then(b=>new File([b],match.name,{type:'image/png'})).catch(()=>{mediaFiles.delete(match.file);return null;}));return mediaFiles.get(match.file);}
 const template=()=>templates.find(x=>x.id===$('bibleTemplate').value);
 function chooseDefaultBible(){const chosen=templates.find(t=>t.id===DEFAULT_BIBLE_TEMPLATE_ID);$('bibleTemplate').value=chosen?.id||'';if(!chosen)$('resourceMessage').textContent='기본 말씀 템플릿이 없습니다. 사용할 템플릿을 선택하세요.';}
 function boxInfo(){const sample=E.bibleSlide({text:'',reference:'장절'},template()),box=P.textElements(sample)[0],style=P.parseRTF(P.textNode(box).textContent).emptyStyle,rect=P.rect(box);return {sample,box,style,rect};}
 async function metrics(){const chosen=template();await ensureTemplate(chosen);if(chosen!==template())return metrics();const info=boxInfo();const warnings=await PP6Fonts.ensure(info.sample);if(warnings.length)$('resourceMessage').textContent=warnings.join(' · ');const ctx=document.createElement('canvas').getContext('2d');ctx.font=PP6Fonts.css(info.style);const layout=PP6Render.layout(ctx,{runs:[{text:'한',style:info.style}],emptyStyle:info.style},info.rect);return {...info,ctx,measure:text=>ctx.measureText(text).width,capacity:Math.max(1,Math.floor((info.rect.h+layout.lines[0].leading)/layout.lines[0].height))};}
 function targetLabel(){$('bibleTarget').textContent=`넣을 곳: ${E.state().name.replace(/\.pro6$/i,'')} · ${E.selected()+1}장 뒤`;}
 async function show(){if(!E.ready()||!YebaeonCloud.needUser())return;try{await boot();if(!bible)bible=await(await resource('bible.json')).json();if(resetBibleTemplate||target?.key!==E.state().key){chooseDefaultBible();resetBibleTemplate=false;}target={key:E.state().key,index:E.selected()};targetLabel();$('biblePanel').hidden=false;$('bibleQuery').focus();if($('bibleQuery').value){if(draft.length)await render();else await build();}}catch(error){E.status(error.message);}}
 async function build(){const token=++buildSequence;editing=-1;$('bibleAdd').disabled=true;try{await boot();if(!bible)bible=await(await resource('bible.json')).json();const parsed=B.parse($('bibleQuery').value,bible);const m=await metrics();if(token!==buildSequence)return;draft=[];for(const verse of parsed.verses){const lines=B.wrap(verse.text,m.rect.w,m.measure,$('bibleWrap').checked);const chunks=B.balanced(lines,m.capacity);for(const text of chunks)draft.push({...verse,text,changed:chunks.length>1,manual:false});}$('bibleParsed').textContent=`${parsed.reference} · ${parsed.verses.length}절 · NKRV`;$('resourceMessage').textContent=PP6Fonts.state().some(x=>x.status!=='loaded')?'대체 글꼴로 계산한 결과입니다. PP6에서 최종 확인하세요.':'';await render();}catch(error){if(token!==buildSequence)return;draft=[];$('bibleGrid').replaceChildren();$('bibleParsed').textContent='';$('resourceMessage').textContent=error.message;}}
 async function render(){const token=++buildSequence,root=$('bibleGrid');root.replaceChildren();root.classList.toggle('reflow',bibleView==='reflow');if(!draft.length)return;const m=await metrics();if(token!==buildSequence)return;let long=0,changed=0;
 draft.forEach((value,index)=>{const info=layoutValue(value,m);if(info.lines>=6)long++;if(value.changed)changed++;if(filter==='long'&&info.lines<6||filter==='changed'&&!value.changed)return;
 const card=document.createElement('div');card.className='bible-card'+(info.lines>=6?' long':'')+(value.changed?' changed':'')+(editing===index||bibleView==='reflow'?' editing':'')+(info.overflow?' overflow':'');card.tabIndex=0;
 const reference=B.reference(value),canvas=document.createElement('canvas');canvas.width=640;canvas.height=Math.round(640*E.model().height/E.model().width);
 const caption=document.createElement('div');caption.className='bible-caption';const label=document.createElement('strong');label.textContent=reference;const count=document.createElement('span');caption.append(label,count);
 const redraw=()=>{const data=layoutValue(value,m);value.lineCount=data.lines;value.overflow=data.overflow;count.textContent=data.lines+'줄'+(data.overflow?' · 글상자 넘침':'');card.classList.toggle('overflow',data.overflow);card.classList.toggle('long',data.lines>=6);PP6Render.fit(canvas,E.model(),640);PP6Render.draw(canvas,E.model(),E.bibleSlide({text:data.text,reference:B.reference(value)},template()),new Map());};
 if(editing===index||bibleView==='reflow'){const input=document.createElement('textarea');input.value=value.text;input.setAttribute('aria-label',reference+' 본문');input.oninput=()=>{value.text=input.value;value.manual=true;value.changed=true;card.classList.add('changed');redraw();$('bibleLong').textContent=draft.filter(v=>v.lineCount>=6).length;$('bibleChanged').textContent=draft.filter(v=>v.changed).length;};input.onkeydown=e=>{if(e.isComposing)return;if(e.code==='Enter'&&YebaeonKeys.leftAlt()){e.preventDefault();split(index,input.selectionStart);}else if(e.code==='Backspace'&&!input.selectionStart&&!input.selectionEnd&&index>0){e.preventDefault();merge(index);}else if(e.code==='Escape'){e.preventDefault();e.stopPropagation();editing=-1;bibleView='slides';render();}};card.append(input);if(editing===index)setTimeout(()=>input.focus(),0);}
 card.append(canvas,caption);card.ondblclick=e=>{if(e.target.closest('textarea,button'))return;quickBible(index,m);};card.onkeydown=e=>{if(e.key==='Enter'&&e.target===card){e.preventDefault();quickBible(index,m);}};
 const actions=document.createElement('div');actions.className='bible-actions';for(const [name,action,disabled] of [['빠른 편집',()=>quickBible(index,m),false],['앞 장에 합치기',()=>merge(index),index===0],['나누기',()=>split(index),false]]){const button=document.createElement('button');button.textContent=name;button.disabled=disabled;button.onclick=action;actions.append(button);}card.append(actions);root.append(card);redraw();});
 $('bibleCount').textContent=draft.length;$('bibleLong').textContent=long;$('bibleChanged').textContent=changed;$('bibleAdd').textContent=`말씀 ${draft.length}장 추가`;$('bibleAdd').disabled=draft.length===0;}
 function layoutValue(value,m){const lines=B.wrap(value.text,m.rect.w,m.measure,$('bibleWrap').checked),text=lines.join('\n'),data=PP6Render.layout(m.ctx,{runs:[{text,style:m.style}],emptyStyle:m.style},m.rect);return {text,lines:data.lines.length,overflow:data.overflow};}
 function quickBible(index,m){const value=draft[index],dialog=$('bibleQuickDialog'),input=$('bibleQuickText'),canvas=$('bibleQuickCanvas');$('bibleQuickTitle').textContent='빠른 편집 · '+B.reference(value);input.value=value.text;canvas.width=960;canvas.height=Math.round(960*E.model().height/E.model().width);
 const draw=()=>{const data=layoutValue(value,m);$('bibleQuickOverflow').textContent=data.lines+'줄'+(data.overflow?' · 글상자 넘침':'');PP6Render.fit(canvas,E.model(),640);PP6Render.draw(canvas,E.model(),E.bibleSlide({text:data.text,reference:B.reference(value)},template()),new Map());};
 input.oninput=()=>{value.text=input.value;value.manual=true;value.changed=true;draw();};input.onkeydown=e=>{if(e.isComposing)return;if(e.code==='Enter'&&YebaeonKeys.leftAlt()){e.preventDefault();dialog.close();split(index,input.selectionStart);}else if(e.code==='Backspace'&&!input.selectionStart&&!input.selectionEnd&&index>0){e.preventDefault();dialog.close();merge(index);}};
 $('bibleQuickSplit').onclick=()=>{dialog.close();split(index,input.selectionStart);};$('bibleQuickMerge').disabled=index===0;$('bibleQuickMerge').onclick=()=>{dialog.close();merge(index);};dialog.onclose=()=>render();if(!dialog.open)dialog.showModal();input.focus();draw();}
 function split(index,offset){const item=draft[index];if(offset===undefined){const lines=item.text.split('\n');if(lines.length>1)offset=lines.slice(0,Math.ceil(lines.length/2)).join('\n').length;else{const middle=Math.floor(item.text.length/2);offset=item.text.indexOf(' ',middle);if(offset<0)offset=middle;}}if(offset<=0||offset>=item.text.length){$('resourceMessage').textContent='나눌 글 사이에 커서를 놓으세요.';return;}draft.splice(index,1,{...item,text:item.text.slice(0,offset).trimEnd(),changed:true,manual:true},{...item,text:item.text.slice(offset).trimStart(),changed:true,manual:true});editing=-1;render();}
 function merge(index){if(index<=0)return;const a=draft[index-1],b=draft[index];draft.splice(index-1,2,{...a,text:a.text+'\n'+b.text,end:b.end,changed:true,manual:true});editing=-1;render();}
 function close(){clearTimeout(queryTimer);buildSequence++;$('biblePanel').hidden=true;}
 function requestBuild(){clearTimeout(queryTimer);if(draft.some(x=>x.manual)&&!confirm('직접 고친 말씀 미리보기를 다시 만들까요?'))return;build();}
 $('bibleViewSlides').onclick=()=>{bibleView='slides';editing=-1;render();};$('bibleViewReflow').onclick=()=>{bibleView='reflow';editing=-1;render();};$('bibleQuickClose').onclick=()=>$('bibleQuickDialog').close();$('resourceOpen').onclick=toggleBible;$('resourceClose').onclick=close;$('bibleCancel').onclick=close;$('bibleTargetChange').onclick=()=>{close();E.status('넣을 문서와 슬라이드를 선택한 뒤 말씀을 다시 여세요.');};$('bibleQuery').onchange=requestBuild;let queryTimer;$('bibleQuery').oninput=()=>{clearTimeout(queryTimer);if(!draft.some(x=>x.manual))queryTimer=setTimeout(build,350);};$('bibleTemplate').onchange=requestBuild;$('bibleWrap').onchange=requestBuild;
 document.querySelectorAll('[data-bible-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.bibleFilter;document.querySelectorAll('[data-bible-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});
 $('bibleAdd').onclick=async()=>{try{if(target.key!==E.state().key||target.index!==E.selected())throw new Error('넣을 문서나 슬라이드가 바뀌었습니다. 넣을 곳을 다시 선택하세요.');const m=await metrics();const values=draft.map(v=>({text:B.wrap(v.text,m.rect.w,m.measure,$('bibleWrap').checked).join('\n'),reference:B.reference(v)}));E.addBible(values,template());draft=[];resetBibleTemplate=true;close();E.setView('slides');}catch(error){$('resourceMessage').textContent=error.message;}};
 $('templateSelect').onchange=async()=>{const key=E.state().key,token=++templateApplySequence;try{const value=templates.find(x=>x.id===$('templateSelect').value);if(value){await ensureTemplate(value);if(token!==templateApplySequence)return;if(key!==E.state().key)throw new Error('문서가 바뀌었습니다. 템플릿을 다시 선택하세요.');E.applyTemplate(value);const slides=P.slides(E.model()),indices=E.selection.values().map(Number);for(const i of indices.length?indices:slides.map((_,i)=>i))knownFormats.set(P.templateFormat(slides[i]),templateName(value));while(knownFormats.size>256)knownFormats.delete(knownFormats.keys().next().value);}}catch(error){E.status(error.message);}finally{if(token===templateApplySequence){$('templateSelect').value='';updateTemplateLabels().catch(e=>E.status(e.message));}}};
 async function showMedia(){if(!E.ready()||!YebaeonCloud.needUser())return;try{await boot();$('mediaDrawer').hidden=false;fillMedia();$('mediaQuery').focus();}catch(error){E.status(error.message);}}
 function fillMedia(){const query=$('mediaQuery').value.normalize('NFC').toLowerCase(),root=$('mediaGrid');root.replaceChildren();for(const item of catalog.media.filter(x=>x.name.normalize('NFC').toLowerCase().includes(query))){const button=document.createElement('button');button.draggable=true;button.title=item.source;const img=document.createElement('img');img.src='/resources/'+item.file;img.alt='';img.loading='lazy';const label=document.createElement('span');label.textContent=item.name;button.append(img,label);button.ondragstart=e=>{mediaDrag=item;e.dataTransfer.setData('text/plain',item.source);e.dataTransfer.effectAllowed='copy';};button.ondragend=()=>mediaDrag=null;button.onclick=()=>E.setBackground(item.source);root.append(button);}}
 $('mediaOpen').onclick=toggleMedia;$('mediaClose').onclick=()=>$('mediaDrawer').hidden=true;$('mediaQuery').oninput=fillMedia;$('serverStatus').onclick=()=>window.open('/status','_blank','noopener');
 for(const event of ['yebaeonrender','yebaeonselection'])window.addEventListener(event,()=>updateTemplateLabels().catch(e=>E.status(e.message)));
 window.addEventListener('yebaeonsession',event=>{if(event.detail.authenticated)boot().catch(e=>E.status(e.message));else{catalog=null;mediaFiles.clear();knownFormats.clear();PP6Render.clear();}});
 function toggleBible(){if(!$('biblePanel').hidden){close();E.setView('slides');return;}$('mediaDrawer').hidden=true;return show();}
 function toggleMedia(){if(!$('mediaDrawer').hidden){$('mediaDrawer').hidden=true;E.setView('slides');return;}close();return showMedia();}
 window.YebaeonResources={async bulletinMaterials(){await boot();if(!bible)bible=await(await resource('bible.json')).json();const t=templates.find(x=>x.id===DEFAULT_BIBLE_TEMPLATE_ID);if(!t)throw new Error('기본 말씀 템플릿을 찾지 못했습니다.');await ensureTemplate(t);return {bible,template:t};},boot,media,showBible:show,showMedia,toggleBible,toggleMedia,draggedMedia:()=>mediaDrag,closeBible:close};
})();
