(function(){'use strict';const $=id=>document.getElementById(id);let busy=false,catalog=null;const time=x=>x?new Date(x).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'}):'기록 없음';const fmt=x=>Number(x||0).toLocaleString('ko-KR');
async function request(path,options={}){const r=await fetch(path,{cache:'no-store',credentials:'same-origin',...options});if(!r.ok){const data=await r.json().catch(()=>({}));const e=new Error(data.message||'서버에 연결하지 못했습니다.');e.status=r.status;throw e;}return r.json();}
function rows(id,data,columns){const body=$(id);body.replaceChildren();for(const item of data){const row=document.createElement('tr');for(const value of columns(item)){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}body.append(row);}if(!data.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=columns({}).length;cell.textContent='아직 기록이 없습니다.';row.append(cell);body.append(row);}}
// 저장소 표: 문서·재생목록·이전 버전, 이미지 전체(중복 없는 원본)와 폴더별 경로.
const labels={currentDocuments:'현재 문서',currentPlaylists:'현재 재생목록',documentHistory:'문서 이전 버전',playlistHistory:'재생목록 이전 버전',images:'이미지 원본(중복 제외)'};
function storageRows(storage){const list=Object.entries(labels).filter(([key])=>storage[key]).map(([key,label])=>({label,...storage[key]}));for(const f of storage.imageFolders||[])list.push({label:`  └ ${f.folder} 폴더 경로`,count:f.count,bytes:f.bytes});rows('storage',list,x=>[x.label,fmt(x.count),(Number(x.bytes||0)/1024/1024).toFixed(2)+' MB']);}
async function refresh(){if(busy||document.hidden)return;busy=true;try{const s=await request('/api/status');$('login').hidden=true;$('dashboard').hidden=false;$('count').textContent=fmt(s.documents);$('bytes').textContent=(s.bytes/1024/1024).toFixed(1)+' MB';$('playlists').textContent=fmt(s.playlists);$('latest').textContent='최근 문서 저장: '+time(s.latestUploadAt);$('observed').textContent='마지막 확인 '+time(s.observedAt);rows('recent',s.recent,x=>[x.path,x.version,x.author,time(x.updatedAt),'확인 중…']);Array.from($('recent').children).forEach((row,i)=>{if(s.recent[i])window.YebaeonUsage.show(row.lastChild,s.recent[i],false);});if(s.storage){storageRows(s.storage);$('storageTotal').textContent='원본 합계 '+(s.storage.trackedBytes/1024/1024).toFixed(2)+' MB';}rows('sync',s.sync,x=>[x.author,time(x.connectedAt),time(x.comparedAt)]);$('message').textContent='서버 저장 기록을 확인했습니다.';if(!catalog){try{catalog=await request('/resources/catalog.json');}catch(_){}}if(catalog){$('baseline').textContent=`이름 인덱스 ${fmt(s.catalogDocuments)}개 · 원본 미업로드 ${fmt(s.unavailableDocuments)}개`; $('resources').textContent=`폰트 ${catalog.fonts.length}종 · 템플릿 ${catalog.templateFiles}개 파일 / ${catalog.templates}개 슬라이드 · ${catalog.bible.name} ${fmt(catalog.bible.verses)}절 · 금요예배 이미지 ${catalog.media.length}개`;;if(catalog.storage)$('resources').textContent+=` · 배포 이미지 ${(catalog.storage.mediaBytes/1024/1024).toFixed(2)} MB · 폰트 ${(catalog.storage.fontBytes/1024/1024).toFixed(2)} MB (별도 정적 자료)`;}else $('resources').textContent='자료 목록을 불러오지 못했습니다. 다음 갱신에서 다시 확인합니다.';}
catch(e){$('message').textContent=e.message;if(e.status===401){$('login').hidden=false;$('dashboard').hidden=true;}}finally{busy=false;}}
$('login').onsubmit=async e=>{e.preventDefault();try{await request('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('name').value,password:$('password').value,remember:true})});await refresh();}catch(err){$('message').textContent=err.message;}finally{$('password').value='';}};$('refresh').onclick=refresh;$('storageRefresh').onclick=async()=>{const button=$('storageRefresh');button.disabled=true;try{const s=await request('/api/status?details=1');storageRows(s.storage);$('storageTotal').textContent='원본 합계 '+(s.storage.trackedBytes/1024/1024).toFixed(2)+' MB · 상세 확인 '+time(s.observedAt);$('storagePanel').hidden=false;}catch(e){$('message').textContent=e.message;}finally{button.disabled=false;}};// 미리보기 일괄 만들기: 폴더별 경로 목록(쪽 단위) → 이미 있는 미리보기 확인 → 없는 것만 원본을 받아 만들어 올린다. 동시에 3개.
let stopThumbs=false;$('thumbnailStop').onclick=()=>{stopThumbs=true;$('thumbnailProgress').textContent='멈추는 중…';};
$('thumbnailBatch').onclick=async()=>{const button=$('thumbnailBatch'),say=t=>$('thumbnailProgress').textContent=t;button.disabled=true;$('thumbnailStop').hidden=false;stopThumbs=false;
 try{const hashes=new Set();for(const folder of ['Images','YebaeOn']){let after=null;do{const page=await request('/api/media/paths?'+new URLSearchParams({folder,...after?{after}:{}}));for(const p of page.paths)hashes.add(p.sha256);after=page.next;say(`그림 목록 확인 중… ${fmt(hashes.size)}개`);}while(after&&!stopThumbs);}
  const all=[...hashes],have=await window.YebaeonThumbnails.existing(all),todo=all.filter(h=>!have.has(h));let done=0,failed=0;say(`미리보기 없는 그림 ${fmt(todo.length)}개 / 전체 ${fmt(all.length)}개`);
  const worker=async()=>{while(todo.length&&!stopThumbs){const sha=todo.shift();try{await window.YebaeonThumbnails.make(sha,null,true);done++;}catch(_){failed++;}say(`만드는 중 ${fmt(done+failed)} / ${fmt(done+failed+todo.length)}${failed?` · 실패 ${fmt(failed)}`:''}`);}};
  await Promise.all([worker(),worker(),worker()]);say(`${stopThumbs?'멈춤':'끝'} · 새로 만든 미리보기 ${fmt(done)}개${failed?` · 실패 ${fmt(failed)}개(다시 누르면 실패한 것만 다시 합니다)`:''} · 전체 ${fmt(all.length)}개 중 ${fmt(have.size+done)}개 있음`);}
 catch(e){say(e.message);}finally{button.disabled=false;$('thumbnailStop').hidden=true;}};
refresh();})();

