import {HttpError,json,method} from './http.mjs';
export async function activityRoute(request,env,user){
 method(request,['GET']);const url=new URL(request.url),scope=url.searchParams.get('scope')||'mine';if(!['mine','all'].includes(scope))throw new HttpError(400,'invalid_scope','이력 범위를 확인해 주세요.');
 let cursor=null;try{if(url.searchParams.has('cursor')){const raw=url.searchParams.get('cursor');if(raw.length>500)throw Error();cursor=JSON.parse(raw);if(cursor.node===undefined)cursor.node='';if(typeof cursor.node!=='string'||cursor.node.length>240)throw Error();if(typeof cursor.at!=='string'||cursor.at.length>40||!['document','playlist'].includes(cursor.kind)||typeof cursor.id!=='string'||!/^[0-9a-f-]{36}$/i.test(cursor.id)||!Number.isSafeInteger(cursor.version)||cursor.version<1)throw Error();}}catch{throw new HttpError(400,'invalid_cursor','이력을 새로고침해 주세요.');}
 const conditions=[],args=[];if(scope==='mine'){conditions.push('author=?');args.push(user.author);}if(cursor){conditions.push('(createdAt < ? OR (createdAt=? AND (kind > ? OR (kind=? AND (id > ? OR (id=? AND (node > ? OR (node=? AND version < ?))))))))');args.push(cursor.at,cursor.at,cursor.kind,cursor.kind,cursor.id,cursor.id,cursor.node,cursor.node,cursor.version);}
 const rows=(await env.DB.prepare(`SELECT * FROM (SELECT 'document' AS kind,d.id,d.path,'' AS node,v.version,v.author,v.created_at AS createdAt FROM yebaeon_versions v JOIN yebaeon_documents d ON d.id=v.document_id UNION ALL SELECT 'playlist' AS kind,p.id,p.path,'' AS node,v.version,v.author,v.created_at AS createdAt FROM yebaeon_playlist_versions v JOIN yebaeon_playlists p ON p.id=v.library_id WHERE NOT EXISTS(SELECT 1 FROM yebaeon_playlist_node_versions n WHERE n.library_id=v.library_id AND n.file_version=v.version) UNION ALL SELECT 'playlist' AS kind,n.library_id AS id,n.name AS path,n.node_id AS node,n.version,n.author,n.created_at AS createdAt FROM yebaeon_playlist_node_versions n) ${conditions.length?'WHERE '+conditions.join(' AND '):''} ORDER BY createdAt DESC,kind ASC,id ASC,node ASC,version DESC LIMIT 51`).bind(...args).all()).results;
 const last=rows[49];return json({items:rows.slice(0,50),next:rows.length>50?JSON.stringify({at:last.createdAt,kind:last.kind,id:last.id,node:last.node,version:last.version}):null});
}

